'use strict';

const {test,expect}=require('@playwright/test');
const APP='/Multiverse_Wheel_V8_1326_Real_Repo_Images.html?e2e=v24';

async function load(page){await page.goto(APP);await expect(page.getByRole('heading',{name:'Choose where the story begins'})).toBeVisible();await expect.poll(()=>page.evaluate(()=>game?.state?.v24?.schemaVersion)).toBe(24);}
async function seed(page,family='speed-race'){
  const data=await page.evaluate(family=>{
    game.state.characterReady=true;const party=DATA.characters.slice(0,2).map(c=>c.id);game.state.party=[...party];for(const id of party)game.v8Party(id);game.ensureV21();game.ensureV22();game.ensureV23();game.ensureV24();game.state.credits=12000;Object.assign(game.state.v18.wallet,{salvage:1000,cosmicFragments:200,voidMarks:20,bountySeals:20});for(const id of party){const rec=game.state.v19.records[id];if(rec){rec.status='active';Object.assign(rec.axes,{loyalty:80,trust:82,respect:80,friendship:76,resentment:2,rivalry:5});}}
    const engine=new MultiverseDomain.ActivityCircuitEngine(),created=engine.createActivity(game.state,{sourceKey:`e2e:v24:${family}`,sourceType:'test',family,universe:game.state.v16.currentUniverse||'Earth-Prime',venue:'E2E Circuit',difficulty:1,heat:88,label:family==='speed-race'?'E2E Velocity Cup':'E2E Championship'});game.save();return{party,activityId:created.activity.id};
  },family);await page.evaluate(()=>game.closeTitleV13(true));await expect(page.locator('#v24-activity-beacon')).toBeVisible();return data;
}
async function openActivities(page){await page.locator('[data-v24-open]').click();await expect(page.locator('.v24-head')).toBeVisible();await expect(page.locator('[data-v16-world-tab="activities"]')).toHaveClass(/active/);}
async function enter(page,id,companionId=''){await page.locator(`[data-v24-plan="${id}"]`).click();await expect(page.locator(`[data-v24-planner="${id}"]`)).toBeVisible();await page.locator(`[data-v24-planner="${id}"] [data-v24-style]`).selectOption('technical');if(companionId)await page.locator(`[data-v24-planner="${id}"] [data-v24-companion]`).selectOption(companionId);await page.locator(`[data-v24-enter="${id}"]`).click();await expect(page.locator('.v24-active')).toBeVisible();}
async function complete(page){await page.evaluate(()=>{let guard=0;while(game.state.v24.activeActivityId&&guard++<30){const activity=game.state.v24.activities[game.state.v24.activeActivityId],segment=activity.segments[activity.segmentIndex];game.state.spin++;game.recordOutcomeV19(segment.events[0],'win',null);}});}

test('V24 Journey 1 — Activities surface exposes races and circuit events',async({page})=>{await load(page);const seeded=await seed(page,'speed-race');await openActivities(page);await expect(page.locator(`[data-v24-plan="${seeded.activityId}"]`)).toBeVisible();await expect(page.locator('.v24-activity-card').filter({hasText:'E2E Velocity Cup'})).toBeVisible();});

test('V24 Journey 2 — race entry uses V18 Credits and companion planning',async({page})=>{await load(page);const seeded=await seed(page,'speed-race');await openActivities(page);const before=await page.evaluate(()=>game.state.credits);await enter(page,seeded.activityId,seeded.party[0]);const after=await page.evaluate(id=>({credits:game.state.credits,status:game.state.v24.activities[id].status,companion:game.state.v24.activities[id].planning.companionId}),seeded.activityId);expect(after.credits).toBeLessThan(before);expect(after.status).toBe('active');expect(after.companion).toBe(seeded.party[0]);});

test('V24 Journey 3 — ordinary Wheel outcomes complete a speed race and produce placement',async({page})=>{await load(page);const seeded=await seed(page,'speed-race');await openActivities(page);await enter(page,seeded.activityId);await complete(page);const result=await page.evaluate(id=>({status:game.state.v24.activities[id].status,rank:game.state.v24.activities[id].rank,points:game.state.v24.season.points}),seeded.activityId);expect(result.status).toBe('completed');expect(result.rank).toBeGreaterThanOrEqual(1);expect(result.rank).toBeLessThanOrEqual(4);expect(result.points).toBeGreaterThan(0);});

test('V24 Journey 4 — combat tournament remains Wheel/battle driven rather than a second combat engine',async({page})=>{await load(page);const seeded=await seed(page,'combat-tournament');await openActivities(page);await enter(page,seeded.activityId);const signals=await page.evaluate(id=>game.state.v24.activities[id].segments.flatMap(s=>s.events),seeded.activityId);expect(signals).toContain('battle');expect(signals).toContain('boss');await complete(page);await expect.poll(()=>page.evaluate(id=>game.state.v24.activities[id].status,seeded.activityId)).toBe('completed');});

test('V24 Journey 5 — active V23 operations and V24 activities are mutually exclusive',async({page})=>{await load(page);const seeded=await seed(page,'speed-race');const blocked=await page.evaluate(id=>{game.state.v23.activeOperationId='synthetic-operation';const before=game.state.credits,result=new MultiverseDomain.ActivityCircuitEngine().beginActivity(game.state,id);game.state.v23.activeOperationId='';return{ok:result.ok,before,after:game.state.credits,error:result.error};},seeded.activityId);expect(blocked.ok).toBe(false);expect(blocked.after).toBe(blocked.before);expect(blocked.error).toContain('V23 operation');});

test('V24 Journey 6 — Activities coexists with Operations, Civilians, Factions, and Economy without console errors',async({page})=>{const errors=[];page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});page.on('pageerror',err=>errors.push(err.message));await load(page);await seed(page);await openActivities(page);await page.locator('[data-v16-world-tab="operations"]').click();await expect(page.locator('.v23-head')).toBeVisible();await page.locator('[data-v16-world-tab="civilians"]').click();await expect(page.locator('.v22-head')).toBeVisible();await page.locator('[data-v16-world-tab="factions"]').click();await expect(page.locator('.v21-subnav')).toBeVisible();await page.locator('[data-v16-world-close]').click();await page.locator('[data-v18-economy-open]').click();await expect(page.locator('.v20-head')).toBeVisible();expect(errors).toEqual([]);});
