'use strict';

const {test,expect}=require('@playwright/test');
const APP='/Multiverse_Wheel_V8_1326_Real_Repo_Images.html?e2e=v25';

async function load(page){await page.goto(APP);await expect(page.getByRole('heading',{name:'Choose where the story begins'})).toBeVisible();await expect.poll(()=>page.evaluate(()=>game?.state?.v25?.schemaVersion)).toBe(25);}
async function seed(page,family='reality-fracture'){
  const data=await page.evaluate(family=>{
    game.state.characterReady=true;const party=DATA.characters.slice(0,2).map(c=>c.id);game.state.party=[...party];for(const id of party)game.v8Party(id);game.ensureV21();game.ensureV22();game.ensureV23();game.ensureV24();game.ensureV25();game.state.credits=16000;Object.assign(game.state.v18.wallet,{salvage:1200,cosmicFragments:220,voidMarks:20,bountySeals:20});for(const id of party){const rec=game.state.v19.records[id];if(rec){rec.status='active';Object.assign(rec.axes,{loyalty:80,trust:82,respect:80,friendship:76,resentment:2,fear:4});}}
    const world=Object.values(game.state.v16.universes)[0];world.stability=34;world.corruption=72;world.threat=78;const engine=new MultiverseDomain.CrisisArcEngine(),created=engine.createCrisis(game.state,{sourceKey:`e2e:v25:${family}`,sourceType:'test',family,primaryUniverse:world.name,universeIds:[world.name],severity:72,label:family==='reality-fracture'?'E2E Reality Cascade':'E2E Crisis Arc'});game.save();return{party,crisisId:created.crisis.id,worldId:world.id};
  },family);await page.evaluate(()=>game.closeTitleV13(true));await expect(page.locator('#v25-crisis-beacon')).toBeVisible();return data;
}
async function openCrises(page){await page.locator('[data-v25-open]').click();await expect(page.locator('.v25-head')).toBeVisible();await expect(page.locator('[data-v16-world-tab="crises"]')).toHaveClass(/active/);}
async function start(page,id,allyId='',support=0,posture='adaptive'){await page.locator(`[data-v25-plan="${id}"]`).click();await expect(page.locator(`[data-v25-planner="${id}"]`)).toBeVisible();await page.locator(`[data-v25-planner="${id}"] [data-v25-posture]`).selectOption(posture);await page.locator(`[data-v25-planner="${id}"] [data-v25-support]`).selectOption(String(support));if(allyId)await page.locator(`[data-v25-planner="${id}"] [data-v25-ally][value="${allyId}"]`).check();await page.locator(`[data-v25-start="${id}"]`).click();await expect(page.locator('.v25-active')).toBeVisible();}
async function complete(page){await page.evaluate(()=>{let guard=0;while(game.state.v25.activeCrisisId&&guard++<30){const crisis=game.state.v25.crises[game.state.v25.activeCrisisId],phase=crisis.phases[crisis.phaseIndex];game.state.spin++;game.recordOutcomeV19(phase.events[0],'win',null);}});}

test('V25 Journey 1 — Crisis Command exposes persistent macro emergencies',async({page})=>{await load(page);const seeded=await seed(page);await openCrises(page);await expect(page.locator(`[data-v25-plan="${seeded.crisisId}"]`)).toBeVisible();await expect(page.locator('.v25-crisis-card').filter({hasText:'E2E Reality Cascade'})).toBeVisible();});

test('V25 Journey 2 — response mobilization uses V18 resources and V19 crisis-team planning',async({page})=>{await load(page);const seeded=await seed(page);await openCrises(page);const before=await page.evaluate(()=>({credits:game.state.credits,salvage:game.state.v18.wallet.salvage}));await start(page,seeded.crisisId,seeded.party[0],2,'containment');const after=await page.evaluate(id=>({credits:game.state.credits,salvage:game.state.v18.wallet.salvage,status:game.state.v25.crises[id].status,allies:game.state.v25.crises[id].response.allyIds}),seeded.crisisId);expect(after.credits).toBeLessThan(before.credits);expect(after.salvage).toBeLessThan(before.salvage);expect(after.status).toBe('active');expect(after.allies).toContain(seeded.party[0]);});

test('V25 Journey 3 — ordinary Wheel outcomes resolve all five phases and stabilize V16 world state',async({page})=>{await load(page);const seeded=await seed(page);const before=await page.evaluate(id=>{const w=game.state.v16.universes[id];return{stability:w.stability,corruption:w.corruption,threat:w.threat};},seeded.worldId);await openCrises(page);await start(page,seeded.crisisId,seeded.party[0],1,'stabilization');await complete(page);const after=await page.evaluate(({crisisId,worldId})=>{const c=game.state.v25.crises[crisisId],w=game.state.v16.universes[worldId];return{status:c.status,phase:c.phaseIndex,stability:w.stability,corruption:w.corruption,threat:w.threat,resolved:game.state.v25.stats.resolved};},seeded);expect(after.status).toBe('resolved');expect(after.phase).toBe(4);expect(after.stability).toBeGreaterThan(before.stability);expect(after.corruption).toBeLessThan(before.corruption);expect(after.threat).toBeLessThan(before.threat);expect(after.resolved).toBeGreaterThan(0);});

test('V25 Journey 4 — failed crisis responses expose a recovery path instead of deleting worlds',async({page})=>{await load(page);const seeded=await seed(page);await openCrises(page);await start(page,seeded.crisisId,seeded.party[0],0,'counterstrike');await page.evaluate(id=>{const e=new MultiverseDomain.CrisisArcEngine(),c=game.state.v25.crises[id];let guard=0;while(c.status==='active'&&guard++<20){const p=c.phases[c.phaseIndex];e.processEvent(game.state,{id:`e2e-v25-loss-${guard}`,type:p.events[0],outcome:'loss'},Array.from(CHAR.values()));}game.save();game.renderWorldV16('crises');},seeded.crisisId);await expect(page.locator('.v25-failed')).toContainText('E2E Reality Cascade');await page.locator(`[data-v25-reopen="${seeded.crisisId}"]`).click();await expect(page.locator(`[data-v25-planner="${seeded.crisisId}"]`)).toBeVisible();const world=await page.evaluate(id=>game.state.v16.universes[id],seeded.worldId);expect(world.stability).toBeGreaterThanOrEqual(8);});

test('V25 Journey 5 — a macro crisis can remain active while a V24 activity runs underneath it',async({page})=>{await load(page);const seeded=await seed(page);await openCrises(page);await start(page,seeded.crisisId,seeded.party[0],0,'adaptive');const coexist=await page.evaluate(()=>{const a=new MultiverseDomain.ActivityCircuitEngine(),created=a.createActivity(game.state,{sourceKey:'e2e:v25:coexist-activity',sourceType:'test',family:'speed-race',universe:game.state.v16.currentUniverse,venue:'Crisis Relief Circuit',difficulty:1,heat:70}),started=a.beginActivity(game.state,created.activity.id,{style:'balanced'});return{crisis:game.state.v25.activeCrisisId,activity:game.state.v24.activeActivityId,ok:started.ok};});expect(coexist.ok).toBe(true);expect(coexist.crisis).toBeTruthy();expect(coexist.activity).toBeTruthy();});

test('V25 Journey 6 — Crises coexists with Activities, Operations, Civilians, Factions, and Economy without console errors',async({page})=>{const errors=[];page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});page.on('pageerror',err=>errors.push(err.message));await load(page);await seed(page);await openCrises(page);await page.locator('[data-v16-world-tab="activities"]').click();await expect(page.locator('.v24-head')).toBeVisible();await page.locator('[data-v16-world-tab="operations"]').click();await expect(page.locator('.v23-head')).toBeVisible();await page.locator('[data-v16-world-tab="civilians"]').click();await expect(page.locator('.v22-head')).toBeVisible();await page.locator('[data-v16-world-tab="factions"]').click();await expect(page.locator('.v21-subnav')).toBeVisible();await page.locator('[data-v16-world-close]').click();await page.locator('[data-v18-economy-open]').click();await expect(page.locator('.v20-head')).toBeVisible();expect(errors).toEqual([]);});
