'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
require('../js/domain/v13-engine.js');
require('../js/domain/v14-engine.js');
require('../js/domain/v15-engine.js');
require('../js/domain/v16-engine.js');
require('../js/domain/v17-engine.js');
require('../js/domain/v18-engine.js');
require('../js/domain/v19-engine.js');
require('../js/domain/v20-engine.js');
const {FactionCampaignEngine}=require('../js/domain/v21-engine.js');
const {SettlementEngine}=require('../js/domain/v22-engine.js');
const {V23_SCHEMA_VERSION,TacticalOperationsEngine,migrateV23,OPERATION_FAMILIES_V23,APPROACHES_V23,SUPPLY_TIERS_V23}=require('../js/domain/v23-engine.js');

const roster=[
  {id:'a',name:'Aegis',universe:'Earth-Prime',role:'support',tags:['healing','support','magic']},
  {id:'b',name:'Blitz',universe:'Earth-Prime',role:'weaponmaster',tags:['speed','martial']},
  {id:'c',name:'Cipher',universe:'Earth-Prime',role:'tactician',tags:['tech','strategy']}
];
const artifacts=[{id:'relic-a',name:'Chronicle Heart',powers:['time','memory'],bonuses:{mind:4,hax:3}}];

function makeState(seed=23001){
  const state=migrateV23({seed,spin:13,credits:12000,customCharacter:{codename:'Validator',homeworld:'Earth-Prime',stats:{skill:72}},party:['a','b'],kits:[],artifacts:['relic-a'],lootInventory:[{id:'gear-a',name:'Riftblade',kind:'equipment',slot:'weapon',rarity:'rare',bonuses:{might:5,skill:3},tags:['weapon'],baseValue:80}],equipment:{weapon:'gear-a'},balanceMode:'roguelite'},artifacts,roster);
  Object.assign(state.v18.wallet,{salvage:1200,cosmicFragments:240,voidMarks:20,bountySeals:20});
  for(const f of Object.values(state.v16.factions))f.reputation=75;
  for(const id of state.party){const rec=state.v19.records[id];if(rec){Object.assign(rec.axes,{loyalty:75,trust:78,respect:76,friendship:72,resentment:4,fear:5,rivalry:10});rec.status='active';}}
  return state;
}
function factionSetup(state){const f=new FactionCampaignEngine(),ids=Object.keys(state.v16.factions),id=ids[0];if(state.v21.primaryFactionId!==id){const joined=f.joinFaction(state,id,roster);assert.equal(joined.ok,true);}Object.assign(state.v21.memberships[id],{rank:5,rankXp:300,authority:70});const t=Object.values(state.v21.territories)[0];t.controllerFactionId=id;t.contested=false;return{f,id,ids,t};}
function frontSetup(state){const setup=factionSetup(state),{f,id,ids}=setup,other=ids.find(x=>x!==id);assert.ok(other);state.v16.factions[id].relations=state.v16.factions[id].relations||{};state.v16.factions[other].relations=state.v16.factions[other].relations||{};state.v16.factions[id].relations[other]=-70;state.v16.factions[other].relations[id]=-70;f.ensureFronts(state);const front=Object.values(state.v21.fronts).find(x=>[x.attackerId,x.defenderId].includes(id)&&[x.attackerId,x.defenderId].includes(other));assert.ok(front,'V21 should create a front only after a real hostile faction relation exists');return{...setup,other,front};}
function manual(state,family='reconnaissance',extra={}){const e=new TacticalOperationsEngine(),key=`test:${family}:${Object.keys(state.v23.operations).length}:${state.spin}`;const r=e.createOperation(state,{sourceKey:key,sourceType:'test',family,urgency:70,...extra});assert.equal(r.ok,true);return state.v23.operations[r.operation.id];}
function deploy(state,op,plan={}){const e=new TacticalOperationsEngine(),r=e.beginOperation(state,op.id,{approach:'adaptive',allyIds:['a'],supplyCommitment:0,priority:'balanced',...plan});assert.equal(r.ok,true);return e;}
function complete(state,e,op){let guard=0;while((op=e.activeOperation(state))&&guard++<30){const stage=op.stages[op.stageIndex];const r=e.processEvent(state,{id:`complete-${op.id}-${guard}`,type:stage.events[0],outcome:stage.requiredOutcome||'win'},roster);if(r?.operationComplete)return r;}throw new Error('operation did not complete');}

test('1. V23 migration is idempotent',()=>{const state=makeState(),engine=new TacticalOperationsEngine(),before=JSON.stringify(state);engine.ensure(state,artifacts,roster);assert.equal(state.v23.schemaVersion,V23_SCHEMA_VERSION);assert.equal(JSON.stringify(state),before);});
test('2. V22 civilian state survives V23 migration',()=>{const state=makeState();const before=JSON.stringify(state.v22);migrateV23(state,artifacts,roster);assert.equal(JSON.stringify(state.v22),before);});
test('3. V23 catalog covers the planned mission families',()=>{for(const id of ['extraction','rescue','escort','sabotage','reconnaissance','interception','artifact-recovery','stronghold-defense','civilian-evacuation','counter-infiltration','warfront-breakthrough','leadership-capture','route-stabilization'])assert.ok(OPERATION_FAMILIES_V23[id]);assert.ok(Object.keys(OPERATION_FAMILIES_V23).length>=13);});
test('4. operation generation is deterministic from persistent sources',()=>{const a=makeState(88),b=makeState(88);assert.deepEqual(a.v23.operations,b.v23.operations);});
test('5. active V21 campaigns can source operations',()=>{const state=makeState(),{f,id}=factionSetup(state),c=f.createCampaign(state,id,'border-war');assert.equal(c.ok,true);const e=new TacticalOperationsEngine(),created=e.discoverOperations(state,20);assert.ok(created.some(op=>op.sourceKey===`campaign:${c.campaign.id}`));});
test('6. active V21 fronts can source operations',()=>{const state=makeState(),{front}=frontSetup(state),e=new TacticalOperationsEngine();e.discoverOperations(state,20);assert.ok(Object.values(state.v23.operations).some(op=>op.sourceType==='front'&&op.frontId===front.id));});
test('7. V22 civilian crises can source evacuation operations',()=>{const state=makeState(),e=new TacticalOperationsEngine(),s=Object.values(state.v22.settlements)[0];s.status='crisis';s.displaced=Math.max(150,Math.round(s.population*.2));e.discoverOperations(state,20);assert.ok(Object.values(state.v23.operations).some(op=>op.settlementId===s.id&&op.family==='civilian-evacuation'));});
test('8. V21 stronghold sieges can source defense operations',()=>{const state=makeState(),{f,id,t}=factionSetup(state),built=f.buildStronghold(state,{territoryId:t.id,factionId:id});assert.equal(built.ok,true);const hold=state.v21.strongholds[built.stronghold.id];hold.underSiege=true;hold.status='threatened';new TacticalOperationsEngine().discoverOperations(state,20);assert.ok(Object.values(state.v23.operations).some(op=>op.strongholdId===hold.id&&op.family==='stronghold-defense'));});
test('9. stolen V20 relics can source artifact recovery',()=>{const state=makeState(),e=new TacticalOperationsEngine(),r=state.v20.relics['relic-a'];r.status='stolen';r.stolenBy='nemesis-x';e.discoverOperations(state,20);assert.ok(Object.values(state.v23.operations).some(op=>op.relicId==='relic-a'&&op.family==='artifact-recovery'));});
test('10. planning choices do not spend V18 resources',()=>{const state=makeState(),op=manual(state),e=new TacticalOperationsEngine(),before={credits:state.credits,salvage:state.v18.wallet.salvage},r=e.planOperation(state,op.id,{approach:'stealth',allyIds:['a','b'],supplyCommitment:3,priority:'team'});assert.equal(r.ok,true);assert.deepEqual({credits:state.credits,salvage:state.v18.wallet.salvage},before);});
test('11. strained V19 allies can refuse deployment without spending resources',()=>{const state=makeState(),op=manual(state),e=new TacticalOperationsEngine();state.v19.records.a.axes.resentment=90;const before=state.credits,r=e.beginOperation(state,op.id,{allyIds:['a'],supplyCommitment:2});assert.equal(r.ok,false);assert.equal(state.credits,before);});
test('12. deployment spends the authoritative V18 wallet once',()=>{const state=makeState(),op=manual(state),e=new TacticalOperationsEngine(),before={credits:state.credits,salvage:state.v18.wallet.salvage},r=e.beginOperation(state,op.id,{allyIds:['a'],supplyCommitment:2});assert.equal(r.ok,true);assert.equal(state.credits,before.credits-SUPPLY_TIERS_V23[2].cost.credits);assert.equal(state.v18.wallet.salvage,before.salvage-SUPPLY_TIERS_V23[2].cost.salvage);});
test('13. only one operation can be active at a time',()=>{const state=makeState(),a=manual(state,'rescue'),b=manual(state,'escort'),e=deploy(state,a);const r=e.beginOperation(state,b.id,{allyIds:['b']});assert.equal(r.ok,false);assert.equal(b.status,'available');});
test('14. matching Wheel events progress the active mission stage',()=>{const state=makeState(),op=manual(state),e=deploy(state,op),stage=op.stages[0],before=stage.progress;e.processEvent(state,{id:'match',type:stage.events[0],outcome:'win'},roster);assert.ok(stage.progress>before);});
test('15. unrelated Wheel events do not progress mission stages',()=>{const state=makeState(),op=manual(state),e=deploy(state,op),stage=op.stages[0],before=stage.progress;e.processEvent(state,{id:'no-match',type:'totally-unrelated',outcome:'win'},roster);assert.equal(stage.progress,before);});
test('16. duplicate Wheel event IDs cannot double-progress operations',()=>{const state=makeState(),op=manual(state),e=deploy(state,op),stage=op.stages[0],ctx={id:'dupe-op',type:stage.events[0],outcome:'win'};e.processEvent(state,ctx,roster);const after=stage.progress;e.processEvent(state,ctx,roster);assert.equal(stage.progress,after);});
test('17. losses create recoverable mission stress before failure',()=>{const state=makeState(),op=manual(state,'interception'),e=deploy(state,op),stage=op.stages[0],before=op.stress,r=e.processEvent(state,{id:'setback-1',type:stage.events[0],outcome:'loss'},roster);assert.equal(r.setback,true);assert.ok(op.stress>before);assert.equal(op.status,'active');});
test('18. extreme repeated setbacks can fail an operation without deleting its source systems',()=>{const state=makeState(),op=manual(state,'interception'),e=deploy(state,op),territories=Object.keys(state.v21.territories).length;let i=0;while(op.status==='active'&&i++<20){const stage=op.stages[op.stageIndex];e.processEvent(state,{id:`loss-${i}`,type:stage.events[0],outcome:'loss'},roster);}assert.equal(op.status,'failed');assert.equal(Object.keys(state.v21.territories).length,territories);});
test('19. multi-stage operations advance in Intel-to-Extraction order',()=>{const state=makeState(),op=manual(state,'rescue'),e=deploy(state,op);assert.equal(op.stages[0].label,'Intel');e.processEvent(state,{id:'stage-one',type:op.stages[0].events[0],outcome:'win'},roster);assert.equal(op.stages[0].status,'completed');assert.equal(op.stages[1].label,'Approach');assert.equal(op.stages[1].status,'active');});
test('20. completing Extraction resolves the operation and clears active focus',()=>{const state=makeState(),op=manual(state,'escort'),e=deploy(state,op),r=complete(state,e,op);assert.equal(r.success,true);assert.equal(op.status,'completed');assert.equal(state.v23.activeOperationId,'');});
test('21. operation planning odds and damage stay inside V23 caps',()=>{const state=makeState(),{f,id,t}=factionSetup(state),op=manual(state,'warfront-breakthrough',{factionId:id,territoryId:t.id}),e=new TacticalOperationsEngine();const hold=f.buildStronghold(state,{territoryId:t.id,factionId:id});if(hold.ok)f.assignSpecialist(state,hold.stronghold.id,'b','defense-commander');const specialist=Object.keys(state.v21.assignments)[0]||'';const r=e.planOperation(state,op.id,{approach:'direct',allyIds:['a','b'],specialistId:specialist,factionSupport:true,relicId:'relic-a',supplyCommitment:3,priority:'objective'});assert.equal(r.ok,true);assert.ok(r.modifiers.odds>=-.06&&r.modifiers.odds<=.06);assert.ok(r.modifiers.damage>=-.08&&r.modifiers.damage<=.08);});
test('22. V19 relationships react to mission deployment and success',()=>{const state=makeState(),op=manual(state),before=state.v19.records.a.axes.trust,e=deploy(state,op);complete(state,e,op);assert.ok(state.v19.records.a.axes.trust>before);});
test('23. successful missions reward existing V18 Credits and Salvage',()=>{const state=makeState(),op=manual(state),e=deploy(state,op),afterCost={credits:state.credits,salvage:state.v18.wallet.salvage};complete(state,e,op);assert.ok(state.credits>afterCost.credits);assert.ok(state.v18.wallet.salvage>afterCost.salvage);});
test('24. selected V20 relic support gains bounded Bond on mission success',()=>{const state=makeState(),op=manual(state),e=deploy(state,op,{relicId:'relic-a'}),before=state.v20.relics['relic-a'].bond;complete(state,e,op);assert.ok(state.v20.relics['relic-a'].bond>before);assert.ok(state.v20.relics['relic-a'].bond<=100);});
test('25. successful faction operations feed V21 Authority and rank XP',()=>{const state=makeState(),{id,t}=factionSetup(state),op=manual(state,'reconnaissance',{factionId:id,territoryId:t.id}),e=deploy(state,op),before={authority:state.v21.memberships[id].authority,xp:state.v21.memberships[id].rankXp};complete(state,e,op);assert.ok(state.v21.memberships[id].authority>=before.authority);assert.ok(state.v21.memberships[id].rankXp>=before.xp);});
test('26. warfront aftermath moves pressure supply and morale only in bounded steps',()=>{const state=makeState(),{id,front}=frontSetup(state);front.attackerId=id;const op=manual(state,'warfront-breakthrough',{factionId:id,frontId:front.id,territoryId:front.territoryId}),e=deploy(state,op),before={pressure:front.pressure,supply:front.supply,morale:front.morale};complete(state,e,op);assert.ok(Math.abs(front.pressure-before.pressure)<=4);assert.ok(Math.abs(front.supply-before.supply)<=3);assert.ok(Math.abs(front.morale-before.morale)<=3);});
test('27. civilian operations write recovery back into V22 settlement state',()=>{const state=makeState(),s=Object.values(state.v22.settlements)[0];s.displaced=200;s.population=Math.max(300,s.population);const op=manual(state,'civilian-evacuation',{settlementId:s.id,territoryId:s.territoryId,universe:s.universe}),e=deploy(state,op,{priority:'civilians'}),before={displaced:s.displaced,opinion:s.playerOpinion};complete(state,e,op);assert.ok(s.displaced<before.displaced);assert.ok(s.playerOpinion>before.opinion);assert.ok(state.v23.stats.civiliansRescued>0);});
test('28. failed stronghold defense cannot delete or zero a V21 stronghold',()=>{const state=makeState(),{f,id,t}=factionSetup(state),built=f.buildStronghold(state,{territoryId:t.id,factionId:id});assert.equal(built.ok,true);const hold=state.v21.strongholds[built.stronghold.id];hold.integrity=24;const op=manual(state,'stronghold-defense',{strongholdId:hold.id,territoryId:t.id,factionId:id}),e=deploy(state,op);e.abortOperation(state,op.id,roster);assert.ok(state.v21.strongholds[hold.id]);assert.ok(hold.integrity>=20);});
test('29. offline operation catch-up is capped and never auto-completes a mission',()=>{const state=makeState(),op=manual(state),e=deploy(state,op);state.v23.lastWorldTick=0;state.v16.clock.tick=20;const result=e.catchUp(state,6);assert.equal(result.ticks,6);assert.equal(op.status,'active');assert.ok(op.stress<=90);});
test('30. summary access is side-effect free after V23 migration',()=>{const state=makeState(),e=new TacticalOperationsEngine(),before=JSON.stringify(state.v23);e.summary(state);e.summary(state);assert.equal(JSON.stringify(state.v23),before);});
test('31. explicit withdrawal is a recoverable failure and preserves the operation history',()=>{const state=makeState(),op=manual(state),e=deploy(state,op),r=e.abortOperation(state,op.id,roster);assert.equal(r.ok,true);assert.equal(op.status,'failed');assert.ok(state.v23.operationHistory.some(x=>x.id===op.id));});
test('32. failed operations can be reopened and replanned for recovery',()=>{const state=makeState(),op=manual(state),e=deploy(state,op);e.abortOperation(state,op.id,roster);const r=e.retryOperation(state,op.id);assert.equal(r.ok,true);assert.equal(op.status,'available');assert.equal(op.stageIndex,0);assert.ok(op.stress<=30);assert.equal(op.planning.locked,false);});
test('33. V23 approach and supply catalogs remain complete',()=>{assert.ok(Object.keys(APPROACHES_V23).length>=4);assert.equal(Object.keys(SUPPLY_TIERS_V23).length,4);});
