'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
require('../js/domain/v13-engine.js');
require('../js/domain/v14-engine.js');
require('../js/domain/v15-engine.js');
require('../js/domain/v16-engine.js');
require('../js/domain/v17-engine.js');
require('../js/domain/v18-engine.js');
require('../js/domain/v19-engine.js');
require('../js/domain/v20-engine.js');
require('../js/domain/v21-engine.js');
require('../js/domain/v22-engine.js');
require('../js/domain/v23-engine.js');
const {V24_SCHEMA_VERSION,ActivityCircuitEngine,migrateV24,ACTIVITY_FAMILIES_V24,ACTIVITY_STYLES_V24}=require('../js/domain/v24-engine.js');

const roster=[{id:'a',name:'Aegis',universe:'Earth-Prime',role:'support',tags:['healing','support']},{id:'b',name:'Blitz',universe:'Earth-Prime',role:'weaponmaster',tags:['speed','martial']}];
const artifacts=[{id:'relic-a',name:'Chronicle Heart',powers:['time'],bonuses:{mind:4}}];
function makeState(seed=24001){const state=migrateV24({seed,spin:15,credits:12000,customCharacter:{codename:'Circuit',homeworld:'Earth-Prime',stats:{might:78,defense:76,speed:88,skill:86,mind:80,energy:82,hax:74}},party:['a','b'],artifacts:['relic-a'],kits:[],lootInventory:[],equipment:{}},artifacts,roster);Object.assign(state.v18.wallet,{salvage:1200,cosmicFragments:200,voidMarks:20,bountySeals:20});for(const id of state.party){const rec=state.v19.records[id];if(rec){rec.status='active';Object.assign(rec.axes,{loyalty:78,trust:80,respect:79,friendship:76,resentment:3,rivalry:8});}}return state;}
function manual(state,family='speed-race',extra={}){const e=new ActivityCircuitEngine(),r=e.createActivity(state,{sourceKey:`test:${family}:${Object.keys(state.v24.activities).length}`,sourceType:'test',family,universe:'Earth-Prime',venue:'Test Circuit',difficulty:2,heat:70,...extra});assert.equal(r.ok,true);return state.v24.activities[r.activity.id];}
function enter(state,activity,plan={}){const e=new ActivityCircuitEngine(),r=e.beginActivity(state,activity.id,{style:'balanced',...plan});assert.equal(r.ok,true);return e;}
function finish(state,e){let guard=0;while(state.v24.activeActivityId&&guard++<30){const a=state.v24.activities[state.v24.activeActivityId],segment=a.segments[a.segmentIndex];e.processEvent(state,{id:`finish-${a.id}-${guard}`,type:segment.events[0],outcome:'win'},roster);}assert.ok(guard<30);}

test('1. V24 migration is idempotent',()=>{const state=makeState(),e=new ActivityCircuitEngine(),before=JSON.stringify(state);e.ensure(state,artifacts,roster);assert.equal(state.v24.schemaVersion,V24_SCHEMA_VERSION);assert.equal(JSON.stringify(state),before);});
test('2. V23 state survives V24 migration',()=>{const state=makeState(),before=JSON.stringify(state.v23);migrateV24(state,artifacts,roster);assert.equal(JSON.stringify(state.v23),before);});
test('3. catalog includes races tournaments trials hunts community and faction events',()=>{for(const id of ['speed-race','portal-rally','combat-tournament','arena-exhibition','survival-gauntlet','relic-trial','treasure-hunt','bounty-pursuit','rescue-drill','civilian-cup','stronghold-games','faction-grand-prix'])assert.ok(ACTIVITY_FAMILIES_V24[id]);assert.equal(Object.keys(ACTIVITY_FAMILIES_V24).length,12);});
test('4. competition style catalog is complete',()=>{for(const id of ['balanced','aggressive','technical','endurance'])assert.ok(ACTIVITY_STYLES_V24[id]);});
test('5. deterministic discovery matches the same saved world',()=>{const a=makeState(1234),b=makeState(1234),e=new ActivityCircuitEngine();assert.deepEqual(e.summary(a).available,e.summary(b).available);});
test('6. creating an activity twice from one source is rejected',()=>{const state=makeState(),e=new ActivityCircuitEngine(),key='same-source',a=e.createActivity(state,{sourceKey:key,family:'speed-race'}),b=e.createActivity(state,{sourceKey:key,family:'speed-race'});assert.equal(a.ok,true);assert.equal(b.ok,false);});
test('7. planning never spends credits',()=>{const state=makeState(),a=manual(state),e=new ActivityCircuitEngine(),before=state.credits,r=e.planActivity(state,a.id,{style:'technical',companionId:'a',relicId:'relic-a'});assert.equal(r.ok,true);assert.equal(state.credits,before);});
test('8. entry spends only the existing V18 Credits wallet',()=>{const state=makeState(),a=manual(state),before=state.credits;enter(state,a);assert.equal(state.credits,before-a.entryCost);});
test('9. insufficient credits reject entry without mutation',()=>{const state=makeState(),a=manual(state),e=new ActivityCircuitEngine();state.credits=0;const before=JSON.stringify(a),r=e.beginActivity(state,a.id);assert.equal(r.ok,false);assert.equal(JSON.stringify(a),before);});
test('10. active V23 operations block activity entry',()=>{const state=makeState(),a=manual(state),e=new ActivityCircuitEngine();state.v23.activeOperationId='operation-focus';const before=state.credits,r=e.beginActivity(state,a.id);assert.equal(r.ok,false);assert.equal(state.credits,before);});
test('11. only one activity can be active',()=>{const state=makeState(),a=manual(state),b=manual(state,'portal-rally'),e=enter(state,a),r=e.beginActivity(state,b.id);assert.equal(r.ok,false);assert.equal(b.status,'available');});
test('12. unrelated Wheel events do not advance a segment',()=>{const state=makeState(),a=manual(state),e=enter(state,a),segment=a.segments[0],before=segment.progress;e.processEvent(state,{id:'unrelated',type:'not-an-event',outcome:'win'},roster);assert.equal(segment.progress,before);});
test('13. matching Wheel events advance activity segments',()=>{const state=makeState(),a=manual(state),e=enter(state,a),segment=a.segments[0];e.processEvent(state,{id:'matching',type:segment.events[0],outcome:'win'},roster);assert.ok(segment.progress>0);});
test('14. duplicate event IDs cannot double score or progress',()=>{const state=makeState(),a=manual(state),e=enter(state,a),segment=a.segments[0],ctx={id:'dupe',type:segment.events[0],outcome:'win'};e.processEvent(state,ctx,roster);const after={score:a.score,progress:segment.progress};e.processEvent(state,ctx,roster);assert.deepEqual({score:a.score,progress:segment.progress},after);});
test('15. losses create setbacks but keep the activity playable',()=>{const state=makeState(),a=manual(state),e=enter(state,a),segment=a.segments[0];e.processEvent(state,{id:'loss',type:segment.events[0],outcome:'loss'},roster);assert.equal(a.status,'active');assert.equal(a.failures,1);});
test('16. a speed race resolves to a bounded rank',()=>{const state=makeState(),a=manual(state,'speed-race'),e=enter(state,a);finish(state,e);assert.equal(a.status,'completed');assert.ok(a.rank>=1&&a.rank<=4);});
test('17. a combat tournament uses ordinary battle signals and resolves',()=>{const state=makeState(),a=manual(state,'combat-tournament'),e=enter(state,a);finish(state,e);assert.equal(a.status,'completed');assert.ok(a.segments.some(s=>s.events.includes('battle')));});
test('18. completion awards only existing economy resources',()=>{const state=makeState(),a=manual(state),e=enter(state,a),afterEntry={credits:state.credits,salvage:state.v18.wallet.salvage};finish(state,e);assert.ok(state.credits>=afterEntry.credits);assert.ok(state.v18.wallet.salvage>=afterEntry.salvage);assert.equal(state.v24.wallet,undefined);});
test('19. circuit score is non-spendable ranking state',()=>{const state=makeState(),a=manual(state),e=enter(state,a);finish(state,e);assert.ok(state.v24.season.points>0);assert.equal(state.v18.wallet.circuitPoints,undefined);});
test('20. companion participation changes existing V19 relationship axes',()=>{const state=makeState(),a=manual(state),before=state.v19.records.a.axes.friendship,e=enter(state,a,{companionId:'a'});finish(state,e);assert.ok(state.v19.records.a.axes.friendship>before);});
test('21. unavailable companions cannot enter and spend nothing',()=>{const state=makeState(),a=manual(state),e=new ActivityCircuitEngine();state.v19.records.a.status='defected';const before=state.credits,r=e.beginActivity(state,a.id,{companionId:'a'});assert.equal(r.ok,false);assert.equal(state.credits,before);});
test('22. podium relic support feeds existing V20 Bond only',()=>{const state=makeState(),a=manual(state,'relic-trial',{difficulty:1}),before=state.v20.relics['relic-a'].bond,e=enter(state,a,{relicId:'relic-a'});finish(state,e);if(a.rank<=2)assert.ok(state.v20.relics['relic-a'].bond>before);else assert.equal(state.v20.relics['relic-a'].bond,before);});
test('23. settlement hosted podiums improve V22 morale and opinion',()=>{const state=makeState(),s=Object.values(state.v22.settlements)[0];assert.ok(s);const a=manual(state,'civilian-cup',{settlementId:s.id,universe:s.universe,difficulty:1}),before={morale:s.morale,opinion:s.playerOpinion},e=enter(state,a);finish(state,e);if(a.rank<=3){assert.ok(s.morale>=before.morale);assert.ok(s.playerOpinion>=before.opinion);}});
test('24. faction hosted podiums use existing V21 membership authority',()=>{const state=makeState(),factionId=Object.keys(state.v16.factions)[0];state.v21.primaryFactionId=factionId;state.v21.memberships[factionId]={factionId,status:'member',rank:3,rankXp:0,authority:40,history:[]};const a=manual(state,'faction-grand-prix',{hostFactionId:factionId,difficulty:1}),before=state.v21.memberships[factionId].authority,e=enter(state,a);finish(state,e);if(a.rank<=3)assert.ok(state.v21.memberships[factionId].authority>=before);});
test('25. withdrawal preserves history and does not refund the entry fee',()=>{const state=makeState(),a=manual(state),before=state.credits,e=enter(state,a),afterEntry=state.credits,r=e.withdrawActivity(state,a.id);assert.equal(r.ok,true);assert.equal(a.status,'withdrawn');assert.equal(state.credits,afterEntry);assert.equal(afterEntry,before-a.entryCost);assert.ok(state.v24.history.some(x=>x.id===a.id));});
test('26. summary and rendering-oriented access do not progress activity state',()=>{const state=makeState(),a=manual(state),e=enter(state,a),before=JSON.stringify(state.v24);e.summary(state);e.summary(state);assert.equal(JSON.stringify(state.v24),before);});
test('27. offline catch-up discovers but never auto-completes activities',()=>{const state=makeState(),a=manual(state),e=enter(state,a);state.v16.clock.tick+=50;e.catchUp(state,6);assert.equal(a.status,'active');assert.equal(a.segmentIndex,0);});
test('28. season tiers are bounded informational rankings',()=>{const e=new ActivityCircuitEngine();assert.equal(e.seasonTier(0),'Rookie');assert.equal(e.seasonTier(60),'Challenger');assert.equal(e.seasonTier(500),'Legend');});
