'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
require('../js/domain/v13-engine.js');
require('../js/domain/v14-engine.js');
require('../js/domain/v15-engine.js');
require('../js/domain/v16-engine.js');
require('../js/domain/v17-engine.js');
require('../js/domain/v18-engine.js');
require('../js/domain/v19-engine.js');
require('../js/domain/v20-engine.js');
require('../js/domain/v21-engine.js');
require('../js/domain/v22-engine.js');
require('../js/domain/v23-engine.js');
require('../js/domain/v24-engine.js');
const {V25_SCHEMA_VERSION,CrisisArcEngine,migrateV25,CRISIS_FAMILIES_V25,CRISIS_POSTURES_V25,CRISIS_SUPPORT_TIERS_V25}=require('../js/domain/v25-engine.js');

const roster=[{id:'a',name:'Aegis',universe:'Earth-Prime',role:'support',tags:['healing','support']},{id:'b',name:'Blitz',universe:'Earth-Prime',role:'weaponmaster',tags:['speed','martial']}];
const artifacts=[{id:'relic-a',name:'Chronicle Heart',powers:['time'],bonuses:{mind:4}}];
function makeState(seed=25001){const state=migrateV25({seed,spin:18,credits:16000,customCharacter:{codename:'Crisis',homeworld:'Earth-Prime',stats:{might:82,defense:80,speed:84,skill:88,mind:90,energy:86,hax:80}},party:['a','b'],artifacts:['relic-a'],kits:[],lootInventory:[],equipment:{}},artifacts,roster);Object.assign(state.v18.wallet,{salvage:1400,cosmicFragments:240,voidMarks:20,bountySeals:20});for(const id of state.party){const rec=state.v19.records[id];if(rec){rec.status='active';Object.assign(rec.axes,{loyalty:80,trust:82,respect:80,friendship:76,resentment:2,fear:4});}}return state;}
function manual(state,family='reality-fracture',extra={}){const e=new CrisisArcEngine(),r=e.createCrisis(state,{sourceKey:`test:${family}:${Object.keys(state.v25.crises).length}`,sourceType:'test',family,primaryUniverse:'Earth-Prime',universeIds:['Earth-Prime'],severity:72,...extra});assert.equal(r.ok,true);return state.v25.crises[r.crisis.id];}
function begin(state,crisis,plan={}){const e=new CrisisArcEngine(),r=e.beginResponse(state,crisis.id,{posture:'adaptive',supportTier:0,allyIds:['a'],...plan});assert.equal(r.ok,true);return e;}
function finish(state,e){let guard=0;while(state.v25.activeCrisisId&&guard++<30){const c=state.v25.crises[state.v25.activeCrisisId],phase=c.phases[c.phaseIndex];e.processEvent(state,{id:`finish-${c.id}-${guard}`,type:phase.events[0],outcome:'win'},roster);}assert.ok(guard<30);}

test('1. V25 migration is idempotent',()=>{const state=makeState(),e=new CrisisArcEngine(),before=JSON.stringify(state);e.ensure(state,artifacts,roster);assert.equal(state.v25.schemaVersion,V25_SCHEMA_VERSION);assert.equal(JSON.stringify(state),before);});
test('2. V24 activity state survives V25 migration',()=>{const state=makeState(),before=JSON.stringify(state.v24);migrateV25(state,artifacts,roster);assert.equal(JSON.stringify(state.v24),before);});
test('3. crisis catalog covers ten macro emergency families',()=>{for(const id of ['reality-fracture','corruption-surge','invasion-wave','temporal-storm','relic-cascade','faction-world-war','refugee-exodus','stronghold-breach','nemesis-uprising','convergence-event'])assert.ok(CRISIS_FAMILIES_V25[id]);assert.equal(Object.keys(CRISIS_FAMILIES_V25).length,10);});
test('4. response posture and V18 support catalogs are complete',()=>{for(const id of ['adaptive','containment','evacuation','counterstrike','stabilization','coalition'])assert.ok(CRISIS_POSTURES_V25[id]);assert.equal(Object.keys(CRISIS_SUPPORT_TIERS_V25).length,4);});
test('5. low V16 stability deterministically discovers a reality fracture',()=>{const state=makeState(101),world=Object.values(state.v16.universes)[0],e=new CrisisArcEngine();world.stability=20;world.corruption=15;world.threat=30;e.discoverCrises(state,20);assert.ok(Object.values(state.v25.crises).some(c=>c.family==='reality-fracture'&&c.primaryUniverse===world.name));});
test('6. high V16 corruption and threat can source separate crisis arcs',()=>{const state=makeState(102),world=Object.values(state.v16.universes)[0],e=new CrisisArcEngine();world.stability=70;world.corruption=80;world.threat=88;e.discoverCrises(state,20);const families=new Set(Object.values(state.v25.crises).map(c=>c.family));assert.ok(families.has('corruption-surge'));assert.ok(families.has('invasion-wave'));});
test('7. severe V22 displacement can source a refugee exodus',()=>{const state=makeState(103),s=Object.values(state.v22.settlements)[0],e=new CrisisArcEngine();s.population=Math.max(1000,s.population);s.displaced=Math.round(s.population*.25);s.status='crisis';e.discoverCrises(state,20);assert.ok(Object.values(state.v25.crises).some(c=>c.family==='refugee-exodus'&&c.settlementIds.includes(s.id)));});
test('8. repeated creation from one crisis source is rejected',()=>{const state=makeState(),e=new CrisisArcEngine(),a=e.createCrisis(state,{sourceKey:'same-crisis',family:'reality-fracture'}),b=e.createCrisis(state,{sourceKey:'same-crisis',family:'reality-fracture'});assert.equal(a.ok,true);assert.equal(b.ok,false);});
test('9. response planning spends no V18 resources',()=>{const state=makeState(),c=manual(state),e=new CrisisArcEngine(),before={credits:state.credits,salvage:state.v18.wallet.salvage},r=e.planResponse(state,c.id,{posture:'containment',supportTier:3,allyIds:['a'],relicId:'relic-a'});assert.equal(r.ok,true);assert.deepEqual({credits:state.credits,salvage:state.v18.wallet.salvage},before);});
test('10. invalid V19 allies reject planning without spending',()=>{const state=makeState(),c=manual(state),e=new CrisisArcEngine();state.v19.records.a.status='defected';const before=state.credits,r=e.beginResponse(state,c.id,{allyIds:['a'],supportTier:2});assert.equal(r.ok,false);assert.equal(state.credits,before);});
test('11. crisis mobilization spends the authoritative V18 wallet once',()=>{const state=makeState(),c=manual(state),before={credits:state.credits,salvage:state.v18.wallet.salvage,fragments:state.v18.wallet.cosmicFragments};begin(state,c,{supportTier:2});assert.equal(state.credits,before.credits-CRISIS_SUPPORT_TIERS_V25[2].cost.credits);assert.equal(state.v18.wallet.salvage,before.salvage-CRISIS_SUPPORT_TIERS_V25[2].cost.salvage);assert.equal(state.v18.wallet.cosmicFragments,before.fragments-CRISIS_SUPPORT_TIERS_V25[2].cost.cosmicFragments);});
test('12. insufficient resources reject mobilization without activating the crisis',()=>{const state=makeState(),c=manual(state),e=new CrisisArcEngine();state.credits=0;state.v18.wallet.salvage=0;const r=e.beginResponse(state,c.id,{supportTier:3});assert.equal(r.ok,false);assert.equal(c.status,'watching');assert.equal(state.v25.activeCrisisId,'');});
test('13. Coalition Response requires an existing faction relationship',()=>{const state=makeState(),c=manual(state),e=new CrisisArcEngine();state.v21.primaryFactionId='';state.v16.factions={};const r=e.planResponse(state,c.id,{posture:'coalition'});assert.equal(r.ok,false);});
test('14. only one crisis can hold active Command focus',()=>{const state=makeState(),a=manual(state),b=manual(state,'invasion-wave'),e=begin(state,a),r=e.beginResponse(state,b.id);assert.equal(r.ok,false);assert.equal(b.status,'watching');});
test('15. V25 macro response can coexist with an active V23 operation',()=>{const state=makeState(),c=manual(state);state.v23.activeOperationId='operation-x';const e=new CrisisArcEngine(),r=e.beginResponse(state,c.id,{supportTier:0});assert.equal(r.ok,true);});
test('16. V25 macro response can coexist with an active V24 activity',()=>{const state=makeState(),c=manual(state);state.v24.activeActivityId='activity-x';const e=new CrisisArcEngine(),r=e.beginResponse(state,c.id,{supportTier:0});assert.equal(r.ok,true);});
test('17. unrelated Wheel events do not progress a crisis phase',()=>{const state=makeState(),c=manual(state),e=begin(state,c),phase=c.phases[0],before=phase.progress;e.processEvent(state,{id:'unrelated',type:'not-real',outcome:'win'},roster);assert.equal(phase.progress,before);});
test('18. matching Wheel events progress the active crisis phase',()=>{const state=makeState(),c=manual(state),e=begin(state,c),phase=c.phases[0];e.processEvent(state,{id:'matching',type:phase.events[0],outcome:'win'},roster);assert.ok(phase.progress>0);});
test('19. duplicate event IDs cannot double-progress or change momentum',()=>{const state=makeState(),c=manual(state),e=begin(state,c),phase=c.phases[0],ctx={id:'dupe-v25',type:phase.events[0],outcome:'win'};e.processEvent(state,ctx,roster);const after={progress:phase.progress,momentum:c.momentum};e.processEvent(state,ctx,roster);assert.deepEqual({progress:phase.progress,momentum:c.momentum},after);});
test('20. setbacks raise bounded pressure while keeping the crisis recoverable',()=>{const state=makeState(),c=manual(state),e=begin(state,c),phase=c.phases[0],before=c.pressure,r=e.processEvent(state,{id:'setback',type:phase.events[0],outcome:'loss'},roster);assert.equal(r.setback,true);assert.ok(c.pressure>before);assert.equal(c.status,'active');assert.ok(c.pressure<=100);});
test('21. repeated severe setbacks fail a response without erasing the world',()=>{const state=makeState(),world=Object.values(state.v16.universes)[0],c=manual(state,'reality-fracture',{primaryUniverse:world.name,universeIds:[world.name]}),e=begin(state,c,{posture:'counterstrike'});let i=0;while(c.status==='active'&&i++<20){const phase=c.phases[c.phaseIndex];e.processEvent(state,{id:`loss-${i}`,type:phase.events[0],outcome:'loss'},roster);}assert.equal(c.status,'failed');assert.ok(world.stability>=8);assert.ok(state.v25.crises[c.id]);});
test('22. five crisis phases advance from Warning through Resolution',()=>{const state=makeState(),c=manual(state),e=begin(state,c);assert.equal(c.phases[0].label,'Warning');finish(state,e);assert.equal(c.status,'resolved');assert.equal(c.phases[4].label,'Resolution');assert.ok(c.phases.every(p=>p.status==='completed'));});
test('23. successful crisis resolution rewards only existing V18 resources',()=>{const state=makeState(),c=manual(state),e=begin(state,c),afterCost={credits:state.credits,salvage:state.v18.wallet.salvage};finish(state,e);assert.ok(state.credits>afterCost.credits);assert.ok(state.v18.wallet.salvage>afterCost.salvage);assert.equal(state.v25.wallet,undefined);});
test('24. success writes bounded recovery into V16 world state',()=>{const state=makeState(),world=Object.values(state.v16.universes)[0];world.stability=35;world.corruption=74;world.threat=80;const before={...world},c=manual(state,'corruption-surge',{primaryUniverse:world.name,universeIds:[world.name]}),e=begin(state,c);finish(state,e);assert.ok(world.stability>before.stability);assert.ok(world.corruption<before.corruption);assert.ok(world.threat<before.threat);assert.ok(world.stability<=100&&world.corruption>=0&&world.threat>=0);});
test('25. settlement-linked crisis success protects displaced civilians through V22 state',()=>{const state=makeState(),s=Object.values(state.v22.settlements)[0];s.population=Math.max(1000,s.population);s.displaced=240;const before={displaced:s.displaced,morale:s.morale},c=manual(state,'refugee-exodus',{primaryUniverse:s.universe,universeIds:[s.universe],settlementIds:[s.id]}),e=begin(state,c,{posture:'evacuation'});finish(state,e);assert.ok(s.displaced<before.displaced);assert.ok(s.morale>=before.morale);assert.ok(state.v25.stats.civiliansProtected>0);});
test('26. failed stronghold breach preserves a recoverable V21 integrity floor',()=>{const state=makeState();state.v21.strongholds['hold-a']={id:'hold-a',name:'Aegis Hold',universe:'Earth-Prime',integrity:24,supply:40,morale:45,status:'threatened',underSiege:true};const c=manual(state,'stronghold-breach',{strongholdIds:['hold-a']}),e=begin(state,c,{posture:'counterstrike'});let i=0;while(c.status==='active'&&i++<20){const phase=c.phases[c.phaseIndex];e.processEvent(state,{id:`hold-loss-${i}`,type:phase.events[0],outcome:'loss'},roster);}assert.equal(c.status,'failed');assert.ok(state.v21.strongholds['hold-a'].integrity>=20);});
test('27. relic-supported resolution feeds existing V20 bond purity and corruption',()=>{const state=makeState(),r=state.v20.relics['relic-a'],before={bond:r.bond,purity:r.purity,corruption:r.corruption},c=manual(state,'relic-cascade',{relicIds:['relic-a']}),e=begin(state,c,{relicId:'relic-a'});finish(state,e);assert.ok(r.bond>=before.bond);assert.ok(r.purity>=before.purity);assert.ok(r.corruption<=before.corruption);});
test('28. crisis team success changes existing V19 trust and respect',()=>{const state=makeState(),before={trust:state.v19.records.a.axes.trust,respect:state.v19.records.a.axes.respect},c=manual(state),e=begin(state,c,{allyIds:['a']});finish(state,e);assert.ok(state.v19.records.a.axes.trust>before.trust);assert.ok(state.v19.records.a.axes.respect>before.respect);});
test('29. faction-coordinated resolution uses existing V21 Authority',()=>{const state=makeState(),factionId=Object.keys(state.v16.factions)[0];state.v21.primaryFactionId=factionId;state.v21.memberships[factionId]={factionId,status:'member',rank:3,rankXp:0,authority:40,history:[]};const before=state.v21.memberships[factionId].authority,c=manual(state,'faction-world-war',{factionIds:[factionId]}),e=begin(state,c,{posture:'coalition',factionId});finish(state,e);assert.ok(state.v21.memberships[factionId].authority>=before);});
test('30. stand down preserves phase progress and never refunds support costs',()=>{const state=makeState(),c=manual(state),e=begin(state,c,{supportTier:1}),afterCost=state.credits,phase=c.phases[0];e.processEvent(state,{id:'partial',type:phase.events[0],outcome:'win'},roster);const progress=phase.progress,r=e.standDownResponse(state,c.id);assert.equal(r.ok,true);assert.equal(c.status,'watching');assert.equal(c.phases[0].progress,progress);assert.equal(state.credits,afterCost);});
test('31. failed crisis can be reopened with pressure and severity recovery caps',()=>{const state=makeState(),c=manual(state),e=begin(state,c,{posture:'counterstrike'});let i=0;while(c.status==='active'&&i++<20){const phase=c.phases[c.phaseIndex];e.processEvent(state,{id:`fail-reopen-${i}`,type:phase.events[0],outcome:'loss'},roster);}const r=e.retryCrisis(state,c.id);assert.equal(r.ok,true);assert.equal(c.status,'watching');assert.ok(c.pressure<=65);assert.ok(c.severity<=90);assert.equal(c.phaseIndex,0);});
test('32. offline catch-up escalates but never auto-resolves or auto-fails a response',()=>{const state=makeState(),c=manual(state),e=begin(state,c);state.v16.clock.tick+=50;e.catchUp(state,6);assert.equal(c.status,'active');assert.equal(c.phaseIndex,0);assert.ok(c.severity<=98);assert.ok(c.pressure<=96);});
test('33. two severe universes can source a convergence event',()=>{const state=makeState(25033),worldEngine=new MultiverseDomain.LivingMultiverseEngine(),first=Object.values(state.v16.universes)[0],second=worldEngine.touchUniverse(state,'Earth-Alt');first.stability=25;second.corruption=78;second.threat=75;new CrisisArcEngine().discoverCrises(state,20);assert.ok(Object.values(state.v25.crises).some(c=>c.family==='convergence-event'&&c.universeIds.length>=2));});
test('34. summary access never progresses crisis state',()=>{const state=makeState(),c=manual(state),e=begin(state,c),before=JSON.stringify(state.v25);e.summary(state);e.summary(state);assert.equal(JSON.stringify(state.v25),before);});
