'use strict';

(function attachV18Engine(root){
  const V18_SCHEMA_VERSION=18;
  const MAX_TRANSACTIONS=160;
  const MAX_CONTRACTS=24;
  const STAT_KEYS=['might','defense','speed','skill','mind','energy','hax'];
  const RARITY_TIERS=[
    {id:'common',label:'Common',mult:1,salvage:3},{id:'uncommon',label:'Uncommon',mult:1.25,salvage:5},
    {id:'rare',label:'Rare',mult:1.65,salvage:8},{id:'epic',label:'Epic',mult:2.25,salvage:12},
    {id:'legendary',label:'Legendary',mult:3.2,salvage:18},{id:'mythic',label:'Mythic',mult:4.5,salvage:26},
    {id:'divine',label:'Divine',mult:6.5,salvage:38},{id:'forbidden',label:'Forbidden',mult:8.5,salvage:52}
  ];
  const CURRENCIES={
    credits:{label:'Credits',symbol:'¢'},cosmicFragments:{label:'Cosmic Fragments',symbol:'✦'},salvage:{label:'Salvage',symbol:'⚙'},
    voidMarks:{label:'Void Marks',symbol:'◈'},bountySeals:{label:'Bounty Seals',symbol:'◆'}
  };
  const VENDORS={
    general:{label:'Crossroads Exchange',price:1,rarity:0},quartermaster:{label:'Faction Quartermaster',price:.92,rarity:1},
    forge:{label:'Fracture Forge',price:.96,rarity:1},relic:{label:'Relic Broker',price:1.08,rarity:2},
    black:{label:'Interdimensional Black Market',price:1.18,rarity:3},arena:{label:'Arena Broker',price:1.04,rarity:1}
  };
  const EQUIPMENT_TEMPLATES=[
    {slot:'weapon',names:['Riftblade','Starbreaker','Chronal Edge','Null Lance'],tags:['weapon','martial']},
    {slot:'armor',names:['Voidguard Plate','Reality Weave','Aegis Mantle','Fracture Shell'],tags:['defense','armor']},
    {slot:'focus',names:['Paradox Lens','Astral Focus','Signal Crown','Archive Prism'],tags:['tech','magic']},
    {slot:'charm',names:['Horizon Sigil','Echo Charm','Dawn Seal','Veil Token'],tags:['support','willpower']}
  ];
  const RECIPES={
    'field-forge':{label:'Field Forge',cost:{salvage:12,cosmicFragments:1},minRarity:1,forbidden:false},
    masterwork:{label:'Masterwork Forge',cost:{salvage:24,cosmicFragments:3},minRarity:2,forbidden:false},
    forbidden:{label:'Forbidden Craft',cost:{salvage:18,cosmicFragments:2,voidMarks:3},minRarity:7,forbidden:true}
  };
  const CONTRACT_TYPES={
    bounty:{label:'Bounty Contract',events:['battle','boss'],outcome:'win',min:1,max:2},
    salvage:{label:'Salvage Contract',events:['hazard'],min:1,max:2},
    courier:{label:'Route Courier',events:['travel'],min:1,max:2},
    relic:{label:'Relic Procurement',events:['artifact'],min:1,max:1},
    commerce:{label:'Trade Commission',events:['purchase','sale','craft'],min:1,max:2}
  };

  const clone=value=>value===undefined?undefined:JSON.parse(JSON.stringify(value));
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
  const normalize=value=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'unknown';
  const hash32=value=>{if(root.MultiverseDomain?.hash32)return root.MultiverseDomain.hash32(String(value));let hash=2166136261;for(const char of String(value)){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return hash>>>0;};
  const rngFrom=key=>{let x=hash32(key)||0x9e3779b9;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};};
  const choose=(list,rng)=>list[Math.floor(rng()*list.length)%list.length];
  const rarityIndex=id=>Math.max(0,RARITY_TIERS.findIndex(tier=>tier.id===id));
  const rarityFromRoll=(roll,bonus=0)=>RARITY_TIERS[clamp((roll>.995?6:roll>.975?5:roll>.92?4:roll>.78?3:roll>.55?2:roll>.28?1:0)+bonus,0,6)].id;
  const canonical=value=>root.MultiverseDomain?.canonicalUniverse?.(value)||String(value||'Unknown');

  class EconomyCraftingEngine{
    ensure(state={},artifacts=[]){
      if(root.MultiverseDomain?.migrateV17)root.MultiverseDomain.migrateV17(state,[]);
      state.credits=Math.max(0,Math.round(Number(state.credits||0)));state.lootInventory=Array.isArray(state.lootInventory)?state.lootInventory:[];state.equipment=state.equipment&&typeof state.equipment==='object'?state.equipment:{};
      state.v18||={};const v18=state.v18;v18.schemaVersion=V18_SCHEMA_VERSION;state.v18Version=V18_SCHEMA_VERSION;state.schemaVersion=Math.max(Number(state.schemaVersion||0),V18_SCHEMA_VERSION);
      v18.wallet={credits:state.credits,cosmicFragments:0,salvage:0,voidMarks:0,bountySeals:0,...(v18.wallet||{})};v18.wallet.credits=state.credits;
      v18.markets=v18.markets&&typeof v18.markets==='object'?v18.markets:{};v18.transactions=Array.isArray(v18.transactions)?v18.transactions.slice(-MAX_TRANSACTIONS):[];
      v18.artifactEvolution=v18.artifactEvolution&&typeof v18.artifactEvolution==='object'?v18.artifactEvolution:{};v18.craftCounter=Math.max(0,Number(v18.craftCounter||0));
      v18.contracts=Array.isArray(v18.contracts)?v18.contracts.slice(-MAX_CONTRACTS):[];v18.contractHistory=Array.isArray(v18.contractHistory)?v18.contractHistory.slice(-80):[];
      v18.auctions=v18.auctions&&typeof v18.auctions==='object'?v18.auctions:{};v18.stats={bought:0,sold:0,crafted:0,salvaged:0,transmuted:0,enchanted:0,artifactFusions:0,contractsCompleted:0,auctionWins:0,...(v18.stats||{})};
      this.syncArtifactEvolution(state,artifacts);this.ensureContracts(state);return state;
    }
    wallet(state){this.ensure(state);state.v18.wallet.credits=state.credits;return clone(state.v18.wallet);}
    addCurrency(state,key,amount){this.ensure(state);if(!CURRENCIES[key])return 0;const value=Math.round(Number(amount)||0);if(key==='credits'){state.credits=Math.max(0,state.credits+value);state.v18.wallet.credits=state.credits;return state.credits;}state.v18.wallet[key]=Math.max(0,Math.round(Number(state.v18.wallet[key]||0))+value);return state.v18.wallet[key];}
    canPay(state,cost={}){this.ensure(state);return Object.entries(cost).every(([key,value])=>(key==='credits'?state.credits:Number(state.v18.wallet[key]||0))>=Number(value||0));}
    pay(state,cost={}){if(!this.canPay(state,cost))return false;for(const [key,value] of Object.entries(cost))this.addCurrency(state,key,-Number(value||0));return true;}
    vendorFor(locationId=''){const map={'black-market':'black',laboratory':'forge',warfront':'quartermaster',archive':'relic',shrine':'relic',arena':'arena',sanctuary':'quartermaster'};return map[String(locationId||'')]||'general';}
    marketKey(state){const world=canonical(state.v16?.currentUniverse||'Unknown'),location=state.v17&&root.MultiverseDomain?.RealityRulesEngine?new root.MultiverseDomain.RealityRulesEngine().currentLocationRecord(state):null;return`${normalize(world)}:${location?.id||'crossroads'}`;}
    marketContext(state){const key=this.marketKey(state),[worldId,locationId]=key.split(':'),world=state.v16?.universes?.[worldId]||{stability:75,corruption:10,threat:15},vendor=this.vendorFor(locationId),rep=Object.values(state.v16?.factions||{}).reduce((best,f)=>Math.max(best,Number(f.reputation||0)),-100);return{key,worldId,locationId,world,vendor,rep};}
    marketPrice(state,base,rarity='common',kind='equipment',vendorId='general'){
      const ctx=this.marketContext(state),vendor=VENDORS[vendorId]||VENDORS.general,market=state.v18.markets[ctx.key],demand=Number(market?.demand?.[kind]||0),tier=RARITY_TIERS[rarityIndex(rarity)]||RARITY_TIERS[0];
      const pressure=1+Number(ctx.world.threat||0)*.0025+Number(ctx.world.corruption||0)*.002-Number(ctx.world.stability||0)*.0012+demand*.035-Math.max(-40,ctx.rep)*.0012;
      return Math.max(1,Math.round(Number(base||1)*tier.mult*vendor.price*clamp(pressure,.72,1.65)));
    }
    equipment(state,{rarity='common',seed='',forbidden=false}={}){
      const rng=rngFrom(`${state.seed||0}|v18|gear|${seed}|${state.v18.craftCounter}`),template=choose(EQUIPMENT_TEMPLATES,rng),tier=RARITY_TIERS[rarityIndex(rarity)],count=1+Math.min(2,Math.floor(rarityIndex(rarity)/2)),bonuses={},stats=STAT_KEYS.slice();
      for(let i=0;i<count;i++){const index=Math.floor(rng()*stats.length),stat=stats.splice(index,1)[0];bonuses[stat]=2+rarityIndex(rarity)+Math.floor(rng()*Math.max(2,rarityIndex(rarity)+2));}
      const name=`${forbidden?'Forbidden ':''}${choose(template.names,rng)}`,id=`gear-${hash32(`${state.seed}|${seed}|${name}|${state.v18.craftCounter}`).toString(36)}`;
      return{id,name,kind:'equipment',slot:template.slot,rarity,bonuses,tags:[...template.tags,...(forbidden?['cursed','forbidden']:[])],cursed:Boolean(forbidden),crafted:Boolean(seed.includes('craft')),enchant:0,baseValue:45+rarityIndex(rarity)*28};
    }
    artifactRarity(artifact={}){const power=(artifact.powers||[]).length,bonus=Object.values(artifact.bonuses||{}).reduce((sum,v)=>sum+Math.abs(Number(v)||0),0),score=power*4+bonus;return score>=70?'divine':score>=50?'mythic':score>=34?'legendary':score>=22?'epic':score>=14?'rare':score>=7?'uncommon':'common';}
    syncArtifactEvolution(state,artifacts=[]){const ids=new Set((state.artifacts||[]).map(String));for(const id of ids){const asset=(artifacts||[]).find(item=>String(item.id)===id),existing=state.v18.artifactEvolution[id]||{};state.v18.artifactEvolution[id]={artifactId:id,rarity:existing.rarity||this.artifactRarity(asset||{}),level:Math.max(1,Number(existing.level||1)),xp:Math.max(0,Number(existing.xp||0)),fusions:Math.max(0,Number(existing.fusions||0))};}return state.v18.artifactEvolution;}
    rotateMarket(state,artifacts=[]){
      this.ensure(state,artifacts);const ctx=this.marketContext(state),rotation=Math.floor(Number(state.v16?.clock?.tick||0)/3),current=state.v18.markets[ctx.key];if(current?.rotation===rotation)return current;const vendor=VENDORS[ctx.vendor],rng=rngFrom(`${state.seed||0}|v18|market|${ctx.key}|${rotation}`),offers=[];
      for(let i=0;i<5;i++){let rarity=rarityFromRoll(rng(),vendor.rarity);if(ctx.vendor==='black'&&rng()>.72)rarity='forbidden';const gear=this.equipment(state,{rarity,seed:`market:${ctx.key}:${rotation}:${i}`,forbidden:rarity==='forbidden'}),price=this.marketPrice(state,gear.baseValue,rarity,'equipment',ctx.vendor);offers.push({...gear,offerId:`offer-${rotation}-g${i}`,price,currency:ctx.vendor==='black'&&rarity==='forbidden'?'voidMarks':'credits'});}
      const candidates=(artifacts||[]).filter(asset=>!(state.artifacts||[]).includes(asset.id));for(let i=0;i<Math.min(2,candidates.length);i++){const asset=candidates[Math.floor(rng()*candidates.length)],rarity=this.artifactRarity(asset),base=100+(asset.powers||[]).length*18,price=this.marketPrice(state,base,rarity,'artifact',ctx.vendor);offers.push({offerId:`offer-${rotation}-a${i}`,kind:'artifact',artifactId:asset.id,name:asset.name,rarity,price,currency:ctx.vendor==='black'?'cosmicFragments':'credits'});}
      offers.push({offerId:`offer-${rotation}-m1`,kind:'material',name:'Salvage Crate',rarity:'uncommon',price:this.marketPrice(state,55,'uncommon','material',ctx.vendor),currency:'credits',grant:{salvage:8}});
      offers.push({offerId:`offer-${rotation}-m2`,kind:'material',name:'Cosmic Fragment Cache',rarity:'rare',price:this.marketPrice(state,90,'rare','material',ctx.vendor),currency:'credits',grant:{cosmicFragments:2}});
      const market=state.v18.markets[ctx.key]={key:ctx.key,vendor:ctx.vendor,vendorLabel:vendor.label,rotation,offers,demand:{equipment:0,artifact:0,material:0,...(current?.demand||{})},transactions:Number(current?.transactions||0)};this.ensureAuction(state,market,artifacts);return market;
    }
    record(state,type,detail={}){const entry={id:`tx-${Date.now().toString(36)}-${state.v18.transactions.length}`,at:Date.now(),tick:Number(state.v16?.clock?.tick||0),type,...clone(detail)};state.v18.transactions.push(entry);state.v18.transactions=state.v18.transactions.slice(-MAX_TRANSACTIONS);return entry;}
    buy(state,offer,artifacts=[]){
      this.ensure(state,artifacts);if(!offer)return{ok:false,error:'Offer is unavailable.'};const currency=offer.currency||'credits',cost={[currency]:Math.max(0,Math.round(Number(offer.price||0)))};if(offer.kind==='artifact'&&(state.artifacts||[]).length>=6&&!state.artifacts.includes(offer.artifactId))return{ok:false,error:'Artifact inventory is full. Sell or fuse a relic first.'};if(!this.pay(state,cost))return{ok:false,error:`Not enough ${CURRENCIES[currency]?.label||currency}.`};
      let grant=null;if(offer.kind==='equipment'){if(state.lootInventory.length>=24){this.addCurrency(state,currency,cost[currency]);return{ok:false,error:'Equipment inventory is full.'};}state.lootInventory.push(clone(offer));grant={kind:'equipment',id:offer.id};}
      else if(offer.kind==='artifact')grant={kind:'artifact',id:offer.artifactId};else if(offer.kind==='material'){for(const [key,value] of Object.entries(offer.grant||{}))this.addCurrency(state,key,value);grant={kind:'material',...offer.grant};}
      const ctx=this.marketContext(state),market=state.v18.markets[ctx.key];if(market){market.demand[offer.kind]=(market.demand[offer.kind]||0)+1;market.transactions++;market.offers=market.offers.filter(item=>item.offerId!==offer.offerId);}state.v18.stats.bought++;this.record(state,'purchase',{name:offer.name,currency,amount:cost[currency],kind:offer.kind});this.progressContracts(state,{type:'purchase',outcome:'success'});return{ok:true,grant,cost,name:offer.name};
    }
    sellEquipment(state,itemId){this.ensure(state);const index=state.lootInventory.findIndex(item=>item.id===itemId);if(index<0)return{ok:false,error:'Equipment not found.'};const item=state.lootInventory[index],equipped=Object.entries(state.equipment).find(([,id])=>id===item.id);if(equipped)delete state.equipment[equipped[0]];state.lootInventory.splice(index,1);const value=Math.max(5,Math.round(this.marketPrice(state,item.baseValue||40,item.rarity,'equipment',this.marketContext(state).vendor)*.45));this.addCurrency(state,'credits',value);this.addCurrency(state,'salvage',Math.max(1,Math.floor((RARITY_TIERS[rarityIndex(item.rarity)]?.salvage||3)/3)));state.v18.stats.sold++;this.record(state,'sale',{name:item.name,currency:'credits',amount:value,kind:'equipment'});this.progressContracts(state,{type:'sale',outcome:'success'});return{ok:true,value};}
    sellArtifact(state,artifactId,artifacts=[]){this.ensure(state,artifacts);const index=(state.artifacts||[]).indexOf(artifactId);if(index<0)return{ok:false,error:'Artifact not owned.'};const asset=(artifacts||[]).find(item=>item.id===artifactId)||{id:artifactId,name:artifactId,powers:[],bonuses:{}},evo=state.v18.artifactEvolution[artifactId],rarity=evo?.rarity||this.artifactRarity(asset),value=Math.max(25,Math.round(this.marketPrice(state,100+(asset.powers||[]).length*18,rarity,'artifact',this.marketContext(state).vendor)*.42));state.artifacts.splice(index,1);delete state.v18.artifactEvolution[artifactId];this.addCurrency(state,'credits',value);this.addCurrency(state,'cosmicFragments',Math.max(1,Math.floor(rarityIndex(rarity)/2)));state.v18.stats.sold++;this.record(state,'sale',{name:asset.name,currency:'credits',amount:value,kind:'artifact'});this.progressContracts(state,{type:'sale',outcome:'success'});return{ok:true,value,rarity};}
    equip(state,itemId){this.ensure(state);const item=state.lootInventory.find(record=>record.id===itemId);if(!item)return{ok:false,error:'Equipment not found.'};state.equipment[item.slot]=item.id;return{ok:true,item:clone(item)};}
    salvageEquipment(state,itemId){this.ensure(state);const index=state.lootInventory.findIndex(item=>item.id===itemId);if(index<0)return{ok:false,error:'Equipment not found.'};const item=state.lootInventory[index],equipped=Object.entries(state.equipment).find(([,id])=>id===item.id);if(equipped)delete state.equipment[equipped[0]];state.lootInventory.splice(index,1);const amount=(RARITY_TIERS[rarityIndex(item.rarity)]?.salvage||3)+Object.keys(item.bonuses||{}).length;this.addCurrency(state,'salvage',amount);state.v18.stats.salvaged++;this.record(state,'salvage',{name:item.name,amount});return{ok:true,amount};}
    craft(state,recipeId){this.ensure(state);const recipe=RECIPES[recipeId];if(!recipe)return{ok:false,error:'Unknown recipe.'};if(state.lootInventory.length>=24)return{ok:false,error:'Equipment inventory is full.'};if(!this.pay(state,recipe.cost))return{ok:false,error:'Required crafting materials are missing.'};state.v18.craftCounter++;const roll=rngFrom(`${state.seed}|v18|craft|${state.v18.craftCounter}|${recipeId}`)(),rarity=recipe.forbidden?'forbidden':RARITY_TIERS[clamp(Math.max(recipe.minRarity,rarityIndex(rarityFromRoll(roll,1))),0,5)].id,item=this.equipment(state,{rarity,seed:`craft:${recipeId}:${state.v18.craftCounter}`,forbidden:recipe.forbidden});state.lootInventory.push(item);if(recipe.forbidden){const world=state.v16?.universes?.[normalize(canonical(state.v16?.currentUniverse))];if(world)world.corruption=clamp(Number(world.corruption||0)+4,0,100);}state.v18.stats.crafted++;this.record(state,'craft',{name:item.name,recipe:recipeId,rarity});this.progressContracts(state,{type:'craft',outcome:'success'});return{ok:true,item:clone(item),cost:clone(recipe.cost)};}
    enchant(state,itemId){this.ensure(state);const item=state.lootInventory.find(record=>record.id===itemId);if(!item)return{ok:false,error:'Equipment not found.'};const cost={salvage:8,cosmicFragments:1};if(!this.pay(state,cost))return{ok:false,error:'Need 8 Salvage and 1 Cosmic Fragment.'};const keys=Object.keys(item.bonuses||{}),key=keys[hash32(`${item.id}|enchant|${item.enchant||0}`)%Math.max(1,keys.length)]||STAT_KEYS[0];item.bonuses[key]=(item.bonuses[key]||0)+2;item.enchant=Math.min(5,Number(item.enchant||0)+1);if(item.enchant===3&&rarityIndex(item.rarity)<6)item.rarity=RARITY_TIERS[rarityIndex(item.rarity)+1].id;state.v18.stats.enchanted++;this.record(state,'enchant',{name:item.name,level:item.enchant});return{ok:true,item:clone(item)};}
    transmute(state,itemId){this.ensure(state);const item=state.lootInventory.find(record=>record.id===itemId);if(!item)return{ok:false,error:'Equipment not found.'};const cost={salvage:5,cosmicFragments:1};if(!this.pay(state,cost))return{ok:false,error:'Need 5 Salvage and 1 Cosmic Fragment.'};const total=Object.values(item.bonuses||{}).reduce((sum,value)=>sum+Number(value||0),0),rng=rngFrom(`${state.seed}|transmute|${item.id}|${state.v18.stats.transmuted}`),count=Math.max(1,Object.keys(item.bonuses||{}).length),available=STAT_KEYS.slice(),bonuses={};let left=total;for(let i=0;i<count;i++){const stat=available.splice(Math.floor(rng()*available.length),1)[0],value=i===count-1?left:Math.max(1,Math.floor(left/(count-i)));bonuses[stat]=value;left-=value;}item.bonuses=bonuses;state.v18.stats.transmuted++;this.record(state,'transmute',{name:item.name});return{ok:true,item:clone(item)};}
    fuseArtifacts(state,primaryId,secondaryId,artifacts=[]){this.ensure(state,artifacts);if(!primaryId||primaryId===secondaryId)return{ok:false,error:'Choose two different artifacts.'};const a=(state.artifacts||[]).indexOf(primaryId),b=(state.artifacts||[]).indexOf(secondaryId);if(a<0||b<0)return{ok:false,error:'Both artifacts must be owned.'};const cost={cosmicFragments:2,salvage:10};if(!this.pay(state,cost))return{ok:false,error:'Need 2 Cosmic Fragments and 10 Salvage.'};state.artifacts.splice(b,1);const evo=state.v18.artifactEvolution[primaryId]||{artifactId:primaryId,rarity:'rare',level:1,xp:0,fusions:0};evo.level=Math.min(8,evo.level+1);evo.fusions++;evo.xp+=100;state.v18.artifactEvolution[primaryId]=evo;delete state.v18.artifactEvolution[secondaryId];this.addCurrency(state,'cosmicFragments',1);state.v18.stats.artifactFusions++;this.record(state,'artifact-fusion',{primaryId,secondaryId,level:evo.level});return{ok:true,evolution:clone(evo),removed:secondaryId};}
    artifactEvolutionBonuses(state){this.ensure(state);const out=Object.fromEntries(STAT_KEYS.map(key=>[key,0]));for(const evo of Object.values(state.v18.artifactEvolution)){const level=Math.max(1,Number(evo.level||1));if(level<=1)continue;const first=STAT_KEYS[hash32(`${evo.artifactId}|a`)%STAT_KEYS.length],second=STAT_KEYS[hash32(`${evo.artifactId}|b`)%STAT_KEYS.length];out[first]+=level-1;if(second!==first)out[second]+=Math.floor((level-1)/2);}return out;}
    equippedBonuses(state){this.ensure(state);const ids=new Set(Object.values(state.equipment||{})),out=Object.fromEntries(STAT_KEYS.map(key=>[key,0])),tags=new Set();for(const item of state.lootInventory.filter(record=>ids.has(record.id))){for(const [key,value] of Object.entries(item.bonuses||{}))if(STAT_KEYS.includes(key))out[key]+=Number(value||0);for(const tag of item.tags||[])tags.add(tag);}return{stats:out,tags:[...tags]};}
    eventReward(state,{type='',outcome='',difficulty='normal'}={}){this.ensure(state);if(outcome==='loss')return{};const scale={story:.75,normal:1,heroic:1.15,cosmic:1.35,impossible:1.6}[difficulty]||1,reward={};if(type==='battle'){reward.credits=Math.round(35*scale);reward.bountySeals=1;}else if(type==='boss'){reward.credits=Math.round(90*scale);reward.cosmicFragments=2;reward.bountySeals=2;}else if(type==='hazard'){reward.salvage=4;}else if(type==='rare'){reward.cosmicFragments=1;if(Number(state.v16?.universes?.[normalize(canonical(state.v16?.currentUniverse))]?.corruption||0)>45)reward.voidMarks=1;}else if(type==='artifact'){reward.credits=20;}else if(type==='training'){reward.salvage=2;}else return{};for(const [key,value] of Object.entries(reward))this.addCurrency(state,key,value);this.record(state,'event-income',{eventType:type,reward});return reward;}
    contractId(state,type,index){return`contract-${hash32(`${state.seed}|${state.v16?.clock?.tick||0}|${type}|${index}|${state.v18.contractHistory.length}`).toString(36)}`;}
    ensureContracts(state){const offered=state.v18.contracts.filter(item=>item.status==='offered'),active=state.v18.contracts.filter(item=>item.status==='active');if(offered.length>=3||active.length>=3)return state.v18.contracts;const types=Object.keys(CONTRACT_TYPES),rng=rngFrom(`${state.seed}|v18|contracts|${state.v16?.clock?.tick||0}|${state.v18.contractHistory.length}`);for(let i=offered.length;i<3;i++){const type=choose(types,rng),def=CONTRACT_TYPES[type],target=def.min+Math.floor(rng()*(def.max-def.min+1)),contract={id:this.contractId(state,type,i),type,label:def.label,objective:`Complete ${target} ${type} objective${target===1?'':'s'}.`,events:def.events.slice(),requiredOutcome:def.outcome||'',target,progress:0,status:'offered',reward:{credits:70+target*30,bountySeals:type==='bounty'?2:1,cosmicFragments:type==='relic'||type==='courier'?1:0,salvage:type==='salvage'?6:0},createdTick:Number(state.v16?.clock?.tick||0)};state.v18.contracts.push(contract);}state.v18.contracts=state.v18.contracts.slice(-MAX_CONTRACTS);return state.v18.contracts;}
    acceptContract(state,id){this.ensure(state);const contract=state.v18.contracts.find(item=>item.id===id);if(!contract||contract.status!=='offered')return{ok:false,error:'Contract is unavailable.'};if(state.v18.contracts.filter(item=>item.status==='active').length>=3)return{ok:false,error:'Three contracts are already active.'};contract.status='active';return{ok:true,contract:clone(contract)};}
    progressContracts(state,context={}){this.ensure(state);const completed=[];for(const contract of state.v18.contracts.filter(item=>item.status==='active')){if(!contract.events.includes(context.type))continue;if(contract.requiredOutcome&&contract.requiredOutcome!==context.outcome)continue;contract.progress=Math.min(contract.target,contract.progress+1);if(contract.progress>=contract.target){contract.status='completed';for(const [key,value] of Object.entries(contract.reward))if(value)this.addCurrency(state,key,value);state.v18.stats.contractsCompleted++;state.v18.contractHistory.push(clone(contract));completed.push(clone(contract));}}this.ensureContracts(state);return completed;}
    ensureAuction(state,market,artifacts=[]){const key=market.key,rotation=market.rotation,current=state.v18.auctions[key];if(current?.rotation===rotation)return current;const rng=rngFrom(`${state.seed}|v18|auction|${key}|${rotation}`),candidates=(artifacts||[]).filter(item=>!(state.artifacts||[]).includes(item.id));let lot;if(candidates.length&&rng()>.35){const asset=choose(candidates,rng),rarity=this.artifactRarity(asset),floor=this.marketPrice(state,90+(asset.powers||[]).length*20,rarity,'artifact',market.vendor);lot={kind:'artifact',artifactId:asset.id,name:asset.name,rarity};lot.floor=floor;}else{const rarity=rarityFromRoll(rng(),2),item=this.equipment(state,{rarity,seed:`auction:${key}:${rotation}`});lot={...item,floor:this.marketPrice(state,item.baseValue,rarity,'equipment',market.vendor)};}lot.rotation=rotation;lot.currentBid=Math.max(1,Math.round(lot.floor*.7));lot.npcCeiling=Math.max(lot.currentBid+1,Math.round(lot.floor*(.82+rng()*.42)));lot.closed=false;state.v18.auctions[key]=lot;return lot;}
    bidAuction(state,amount,artifacts=[]){this.ensure(state,artifacts);const market=this.rotateMarket(state,artifacts),lot=state.v18.auctions[market.key];if(!lot||lot.closed)return{ok:false,error:'No active auction.'};const bid=Math.max(lot.currentBid+1,Math.round(Number(amount)||0));if(state.credits<bid)return{ok:false,error:'Not enough Credits for that bid.'};lot.currentBid=bid;if(bid<lot.npcCeiling)return{ok:true,won:false,currentBid:bid,message:'A rival bidder immediately topped the offer.'};this.addCurrency(state,'credits',-bid);lot.closed=true;let grant;if(lot.kind==='equipment'){if(state.lootInventory.length>=24){this.addCurrency(state,'credits',bid);lot.closed=false;return{ok:false,error:'Equipment inventory is full.'};}state.lootInventory.push(clone(lot));grant={kind:'equipment',id:lot.id};}else{if((state.artifacts||[]).length>=6){this.addCurrency(state,'credits',bid);lot.closed=false;return{ok:false,error:'Artifact inventory is full.'};}grant={kind:'artifact',id:lot.artifactId};}state.v18.stats.auctionWins++;this.record(state,'auction-win',{name:lot.name,amount:bid});return{ok:true,won:true,currentBid:bid,grant};}
    summary(state,artifacts=[]){this.ensure(state,artifacts);const market=this.rotateMarket(state,artifacts),ctx=this.marketContext(state),equipped=this.equippedBonuses(state);return{wallet:this.wallet(state),market:clone(market),auction:clone(state.v18.auctions[ctx.key]),vendor:clone(VENDORS[ctx.vendor]),inventory:state.lootInventory.map(clone),equipment:clone(state.equipment),artifactEvolution:clone(state.v18.artifactEvolution),contracts:state.v18.contracts.map(clone),equipped,stats:clone(state.v18.stats)};}
  }

  function migrateV18(state={},artifacts=[]){return new EconomyCraftingEngine().ensure(state,artifacts);}
  const api={V18_SCHEMA_VERSION,RARITY_TIERS,CURRENCIES,VENDORS,RECIPES,CONTRACT_TYPES,EconomyCraftingEngine,migrateV18};
  root.MultiverseDomain=Object.assign(root.MultiverseDomain||{},api);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:window);
