'use strict';

(function attachV19Engine(root){
  const V19_SCHEMA_VERSION=19,MAX_MEMORIES=180,MAX_MOMENTS=32,MAX_GUESTS=4;
  const AXES=['loyalty','trust','respect','friendship','rivalry','fear','resentment'];
  const STATUS=['active','bench','guest','departed','defected','dead'];
  const TRAITS=['compassionate','disciplined','ambitious','rebellious','cautious','honorable','pragmatic','vengeful'];
  const QUESTS={
    protector:{label:'Keep Them Standing',events:['hazard','battle'],outcome:'win',target:2},
    warrior:{label:'Prove It Together',events:['battle','boss'],outcome:'win',target:2},
    scholar:{label:'Learn the Impossible',events:['training','rare'],target:2},
    wanderer:{label:'See Another World',events:['travel'],target:2},
    relic:{label:'Find What Was Lost',events:['artifact'],target:1},
    bond:{label:'Choose the Team',events:['recruit','v14-saga','v13-universe'],target:2}
  };
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
  const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
  const hash32=value=>{if(root.MultiverseDomain?.hash32)return root.MultiverseDomain.hash32(String(value));let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
  const rngFrom=key=>{let x=hash32(key)||0x9e3779b9;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};};
  const canonical=v=>root.MultiverseDomain?.canonicalUniverse?.(v)||String(v||'Unknown');
  const keyFor=(a,b)=>[String(a),String(b)].sort().join('::');
  const normalize=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'unknown';
  const rosterMap=roster=>new Map((roster||[]).filter(Boolean).map(c=>[String(c.id||''),c]));

  class PartyConsequencesEngine{
    ensure(state={},roster=[]){
      if(root.MultiverseDomain?.migrateV18)root.MultiverseDomain.migrateV18(state,[]);
      state.v19||={};const v=state.v19;v.schemaVersion=V19_SCHEMA_VERSION;state.v19Version=V19_SCHEMA_VERSION;state.schemaVersion=Math.max(Number(state.schemaVersion||0),V19_SCHEMA_VERSION);
      v.records=v.records&&typeof v.records==='object'?v.records:{};v.pairs=v.pairs&&typeof v.pairs==='object'?v.pairs:{};v.benchIds=Array.isArray(v.benchIds)?[...new Set(v.benchIds.map(String))]:[];
      v.guests=Array.isArray(v.guests)?v.guests.slice(0,MAX_GUESTS):[];v.memories=Array.isArray(v.memories)?v.memories.slice(-MAX_MEMORIES):[];v.incidents=Array.isArray(v.incidents)?v.incidents.slice(-40):[];
      v.personalQuests=v.personalQuests&&typeof v.personalQuests==='object'?v.personalQuests:{};v.mentorBonds=v.mentorBonds&&typeof v.mentorBonds==='object'?v.mentorBonds:{};
      v.morale=clamp(v.morale??70,0,100);v.settings={permadeath:false,autoBenchWounded:false,...(v.settings||{})};v.bondSurge={stage:0,uses:0,active:false,...(v.bondSurge||{})};
      v.stats={arguments:0,reconciliations:0,refusals:0,departures:0,defections:0,deaths:0,rescues:0,scars:0,duoTriggers:0,personalQuests:0,...(v.stats||{})};
      const map=rosterMap(roster),known=new Set([...(state.party||[]),...v.benchIds,...v.guests.map(g=>g.id),...Object.keys(state.v13?.relationshipArcs||{})]);
      for(const id of known)if(id)this.record(state,id,map.get(String(id)));
      v.benchIds=v.benchIds.filter(id=>!state.party?.includes(id)&&v.records[id]&&!['departed','defected','dead'].includes(v.records[id].status));
      for(const id of state.party||[]){const r=this.record(state,id,map.get(String(id)));if(!['dead','departed','defected'].includes(r.status))r.status='active';}
      this.syncLegacy(state);this.ensurePairs(state,roster);this.ensurePersonalQuests(state,roster);return state;
    }
    profile(character={}){
      const seed=hash32(`${character.id||character.name}|v19-personality`),tags=new Set((character.tags||[]).map(x=>String(x).toLowerCase())),values={};TRAITS.forEach((trait,i)=>values[trait]=30+((seed>>>(i%4)*6)&31));
      if(tags.has('healing')||tags.has('support'))values.compassionate+=22;if(tags.has('strategy')||tags.has('genius'))values.disciplined+=18;if(tags.has('villain'))values.ambitious+=20;if(tags.has('chaos'))values.rebellious+=20;if(tags.has('detective'))values.cautious+=15;if(tags.has('martial'))values.honorable+=12;if(tags.has('tech'))values.pragmatic+=12;
      for(const k of TRAITS)values[k]=clamp(values[k],0,100);return{traits:values,role:String(character.role||'unknown'),universe:canonical(character.universe),tags:[...tags]};
    }
    record(state,id,character={}){
      id=String(id);const legacy=state.v13?.relationshipArcs?.[id],existing=state.v19.records[id]||{},base=legacy?.loyalty??existing.axes?.loyalty??50;
      const axes={loyalty:base,trust:50,respect:50,friendship:42,rivalry:8,fear:5,resentment:5,...(existing.axes||{})};if(legacy)axes.loyalty=legacy.loyalty;for(const k of AXES)axes[k]=clamp(axes[k],0,100);
      const status=STATUS.includes(existing.status)?existing.status:(legacy?.departed?'departed':state.party?.includes(id)?'active':'bench');
      const rec=state.v19.records[id]={id,name:String(character?.name||existing.name||id),universe:canonical(character?.universe||existing.universe||'Unknown'),axes,status,profile:existing.profile||this.profile(character),wounds:Array.isArray(existing.wounds)?existing.wounds:[],scars:Array.isArray(existing.scars)?existing.scars:[],moments:Array.isArray(existing.moments)?existing.moments.slice(0,MAX_MOMENTS):[],refusals:Number(existing.refusals||legacy?.refusals||0),defectedTo:existing.defectedTo||'',targetedBy:existing.targetedBy||'',joinedSpin:Number(existing.joinedSpin||state.spin||0)};
      return rec;
    }
    syncLegacy(state){for(const [id,rec] of Object.entries(state.v19.records)){const arc=state.v13?.relationshipArcs?.[id];if(arc){arc.loyalty=rec.axes.loyalty;arc.departed=['departed','defected','dead'].includes(rec.status);arc.refusals=Math.max(Number(arc.refusals||0),rec.refusals);}}return state;}
    adjust(state,id,changes={},reason='Relationship changed'){
      const r=this.record(state,id),before={...r.axes};for(const [axis,delta] of Object.entries(changes))if(AXES.includes(axis))r.axes[axis]=clamp(r.axes[axis]+Number(delta||0),0,100);
      const delta=Object.fromEntries(AXES.map(k=>[k,r.axes[k]-before[k]]).filter(([,v])=>v));if(Object.keys(delta).length){r.moments.unshift({spin:Number(state.spin||0),reason:String(reason),delta,axes:{...r.axes}});r.moments=r.moments.slice(0,MAX_MOMENTS);this.memory(state,{type:'relationship',title:`${r.name}: ${reason}`,detail:Object.entries(delta).map(([k,v])=>`${k} ${v>0?'+':''}${v}`).join(' • '),characterId:id});}this.syncLegacy(state);return r;
    }
    pair(state,a,b,roster=[]){const key=keyFor(a,b),existing=state.v19.pairs[key]||{},map=rosterMap(roster),ca=map.get(String(a))||{},cb=map.get(String(b))||{},pa=this.profile(ca),pb=this.profile(cb);if(existing.id)return existing;
      const overlap=pa.tags.filter(t=>pb.tags.includes(t)).length,roleBonus=pa.role!==pb.role?8:0,universe=pa.universe===pb.universe?8:0,traitDistance=TRAITS.reduce((sum,k)=>sum+Math.abs(pa.traits[k]-pb.traits[k]),0)/TRAITS.length,compat=clamp(55+overlap*4+roleBonus+universe-traitDistance*.18,10,95);
      return state.v19.pairs[key]={id:key,a:String(a),b:String(b),compatibility:Math.round(compat),trust:50,friendship:45,rivalry:Math.max(0,Math.round(35-compat*.25)),resentment:5,moments:[]};
    }
    ensurePairs(state,roster=[]){const ids=[...(state.party||[]),...state.v19.benchIds];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)this.pair(state,ids[i],ids[j],roster);return state.v19.pairs;}
    bondScore(state,a,b,roster=[]){const p=this.pair(state,a,b,roster);return clamp((p.compatibility+p.trust+p.friendship-p.rivalry-p.resentment)/3,0,100);}
    bestDuo(state,roster=[]){const ids=state.party||[],pairs=[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const score=this.bondScore(state,ids[i],ids[j],roster);pairs.push({a:ids[i],b:ids[j],score,pair:this.pair(state,ids[i],ids[j],roster)});}return pairs.sort((a,b)=>b.score-a.score)[0]||null;}
    combatModifier(state,roster=[]){this.ensure(state,roster);const active=(state.party||[]).map(id=>this.record(state,id,rosterMap(roster).get(id))).filter(r=>r.status==='active'),avg=k=>active.reduce((s,r)=>s+r.axes[k],0)/Math.max(1,active.length),wounds=active.reduce((s,r)=>s+r.wounds.length,0),duo=this.bestDuo(state,roster),morale=(state.v19.morale-50)*.0007,trust=(avg('trust')-50)*.00035,respect=(avg('respect')-50)*.00025,duoBonus=duo?.score>=70?(duo.score-65)*.0005:0,penalty=wounds*.006;return{odds:clamp(morale+trust+respect+duoBonus-penalty,-.09,.08),damage:clamp((avg('friendship')-50)*.0015+(duo?.score>=80?.06:0)-wounds*.02,-.12,.12),duo:clone(duo),morale:state.v19.morale};}
    assistDecision(state,id){const r=this.record(state,id);if(r.status!=='active')return{allowed:false,reason:'This ally is not in the active party.'};if(r.wounds.length>=2&&r.axes.trust<55){r.refusals++;state.v19.stats.refusals++;return{allowed:false,reason:'Injuries and low trust caused the ally to refuse.'};}if(r.axes.resentment>=65||r.axes.trust<25||r.axes.loyalty<22){r.refusals++;state.v19.stats.refusals++;return{allowed:false,reason:'The relationship is too strained for this assist.'};}return{allowed:true,costDelta:r.axes.friendship>=75?-5:0};}
    changeMorale(state,delta,reason='Party morale changed'){const before=state.v19.morale;state.v19.morale=clamp(before+Number(delta||0),0,100);if(Math.abs(state.v19.morale-before)>=4)this.memory(state,{type:'morale',title:reason,detail:`Morale ${before} → ${state.v19.morale}`});return state.v19.morale;}
    wound(state,id,severity='minor',cause='Hard encounter'){const r=this.record(state,id);if(['dead','departed','defected'].includes(r.status))return null;const wound={id:`w-${hash32(`${state.seed}|${id}|${state.spin}|${cause}|${r.wounds.length}`).toString(36)}`,severity,cause,spin:Number(state.spin||0)};r.wounds.push(wound);r.wounds=r.wounds.slice(-3);this.adjust(state,id,{fear:severity==='severe'?12:6,trust:-2},cause);if(r.wounds.length>=3){const old=r.wounds.shift();r.scars.push({...old,scarredAt:Number(state.spin||0)});r.scars=r.scars.slice(-6);state.v19.stats.scars++;}return wound;}
    healWound(state,id){const r=this.record(state,id);if(!r.wounds.length)return{ok:false,error:'No active wound.'};const wound=r.wounds.shift();this.adjust(state,id,{trust:3,friendship:2,fear:-3},'Wound treated');return{ok:true,wound};}
    bench(state,id){const r=this.record(state,id);if(r.status!=='active')return{ok:false,error:'Only active allies can be benched.'};state.party=state.party.filter(x=>x!==id);if(!state.v19.benchIds.includes(id))state.v19.benchIds.push(id);r.status='bench';this.memory(state,{type:'roster',title:`${r.name} moved to reserve`,characterId:id});return{ok:true,record:clone(r)};}
    activate(state,id,capacity=4){const r=this.record(state,id);if(r.status!=='bench')return{ok:false,error:'Only reserve allies can be activated.'};if((state.party||[]).length>=capacity)return{ok:false,error:'Active party is full.'};state.v19.benchIds=state.v19.benchIds.filter(x=>x!==id);state.party.push(id);r.status='active';this.memory(state,{type:'roster',title:`${r.name} returned to active duty`,characterId:id});return{ok:true,record:clone(r)};}
    addGuest(state,id,duration=3,character={}){if(state.v19.guests.length>=MAX_GUESTS)return{ok:false,error:'Guest roster is full.'};if(state.v19.guests.some(g=>g.id===id))return{ok:false,error:'Guest already present.'};const rec=this.record(state,id,character);rec.status='guest';const guest={id:String(id),expiresSpin:Number(state.spin||0)+Math.max(1,Number(duration||1))};state.v19.guests.push(guest);return{ok:true,guest};}
    expireGuests(state){const expired=[];state.v19.guests=state.v19.guests.filter(g=>{if(Number(state.spin||0)>=g.expiresSpin){const r=this.record(state,g.id);r.status='departed';expired.push(g.id);return false;}return true;});return expired;}
    onRecruit(state,id,character={}){const r=this.record(state,id,character);r.status='active';r.joinedSpin=Number(state.spin||0);this.adjust(state,id,{loyalty:5,trust:4,friendship:3},'Joined the team');this.ensurePersonalQuest(state,id,character);return r;}
    personalQuestKind(record){const p=record.profile||{};if(p.traits?.compassionate>=60)return'protector';if(p.role==='tactician'||p.traits?.disciplined>=65)return'scholar';if(p.traits?.rebellious>=65)return'wanderer';if(p.traits?.ambitious>=65)return'relic';if(p.role==='bruiser'||p.role==='weaponmaster')return'warrior';return'bond';}
    ensurePersonalQuest(state,id,character={}){if(state.v19.personalQuests[id]?.status&&state.v19.personalQuests[id].status!=='completed')return state.v19.personalQuests[id];const rec=this.record(state,id,character),kind=this.personalQuestKind(rec),def=QUESTS[kind];return state.v19.personalQuests[id]={id:`pq-${normalize(id)}-${kind}`,characterId:id,kind,label:def.label,events:def.events.slice(),requiredOutcome:def.outcome||'',target:def.target,progress:0,status:'active',startedSpin:Number(state.spin||0)};}
    ensurePersonalQuests(state,roster=[]){const map=rosterMap(roster);for(const id of [...(state.party||[]),...state.v19.benchIds])this.ensurePersonalQuest(state,id,map.get(id));return state.v19.personalQuests;}
    progressPersonalQuests(state,context={},roster=[]){const completed=[];for(const q of Object.values(state.v19.personalQuests)){if(q.status!=='active'||!q.events.includes(String(context.type||'')))continue;if(q.requiredOutcome&&q.requiredOutcome!==context.outcome)continue;q.progress=Math.min(q.target,q.progress+1);if(q.progress>=q.target){q.status='completed';q.completedSpin=Number(state.spin||0);this.adjust(state,q.characterId,{loyalty:8,trust:8,respect:8,friendship:6,resentment:-5},`Personal quest complete: ${q.label}`);state.v19.stats.personalQuests++;completed.push(clone(q));}}return completed;}
    mentorLesson(state,mentorId,studentId='hero'){const key=`${mentorId}::${studentId}`,m=state.v19.mentorBonds[key]||{mentorId:String(mentorId),studentId:String(studentId),lessons:0,respect:40,trust:40};m.lessons++;m.respect=clamp(m.respect+4,0,100);m.trust=clamp(m.trust+2,0,100);state.v19.mentorBonds[key]=m;return clone(m);}
    maybeArgument(state,roster=[]){if((state.party||[]).length<2||state.v19.morale>=62)return null;const duo=this.bestDuo(state,roster);if(!duo)return null;const p=this.pair(state,duo.a,duo.b,roster),chance=clamp((60-state.v19.morale)*.018+(50-p.compatibility)*.006,0,.6),rng=rngFrom(`${state.seed}|v19|argument|${state.spin}|${p.id}|${state.v19.stats.arguments}`);if(rng()>chance)return null;const a=this.record(state,p.a),b=this.record(state,p.b),incident={id:`arg-${hash32(`${state.seed}|${state.spin}|${p.id}`).toString(36)}`,type:'argument',a:p.a,b:p.b,title:`${a.name} and ${b.name} clash over the route`,status:'open',spin:Number(state.spin||0)};p.resentment=clamp(p.resentment+8,0,100);p.rivalry=clamp(p.rivalry+6,0,100);p.trust=clamp(p.trust-5,0,100);state.v19.incidents.push(incident);state.v19.stats.arguments++;this.changeMorale(state,-6,'A party argument damaged morale');return incident;}
    resolveIncident(state,id,choice='reconcile'){const incident=state.v19.incidents.find(x=>x.id===id&&x.status==='open');if(!incident)return{ok:false,error:'Incident is no longer open.'};const p=this.pair(state,incident.a,incident.b);incident.status='resolved';incident.choice=choice;if(choice==='reconcile'){p.trust=clamp(p.trust+9,0,100);p.friendship=clamp(p.friendship+8,0,100);p.resentment=clamp(p.resentment-10,0,100);this.adjust(state,incident.a,{trust:4,friendship:3,resentment:-4},'Reconciled after conflict');this.adjust(state,incident.b,{trust:4,friendship:3,resentment:-4},'Reconciled after conflict');this.changeMorale(state,8,'The team reconciled');state.v19.stats.reconciliations++;}else{const favored=choice==='side-a'?incident.a:incident.b,other=favored===incident.a?incident.b:incident.a;this.adjust(state,favored,{trust:5,respect:3},'The hero took their side');this.adjust(state,other,{trust:-7,resentment:8,rivalry:4},'The hero sided against them');this.changeMorale(state,-2,'The argument ended without consensus');}return{ok:true,incident:clone(incident)};}
    betrayalCheck(state,id,roster=[]){const r=this.record(state,id,rosterMap(roster).get(String(id)));if(r.status!=='active'||r.axes.loyalty>=28||r.axes.trust>=30||r.axes.resentment<65)return null;const rng=rngFrom(`${state.seed}|v19|betrayal|${state.spin}|${id}|${r.refusals}`);if(rng()>.45)return null;const hostile=Object.values(state.v16?.factions||{}).sort((a,b)=>Number(a.reputation||0)-Number(b.reputation||0))[0];r.status='defected';r.defectedTo=hostile?.id||'unknown';state.party=state.party.filter(x=>x!==id);state.v19.stats.defections++;this.changeMorale(state,-18,`${r.name} defected`);this.memory(state,{type:'betrayal',title:`${r.name} betrayed the party`,detail:hostile?`Defected toward ${hostile.name}.`:'Left the route as an enemy.',characterId:id,weight:8});return clone(r);}
    severeConsequence(state,id,cause='Catastrophic defeat'){const r=this.record(state,id);if(!state.v19.settings.permadeath)return this.wound(state,id,'severe',cause);r.status='dead';state.party=state.party.filter(x=>x!==id);state.v19.benchIds=state.v19.benchIds.filter(x=>x!==id);state.v19.stats.deaths++;this.changeMorale(state,-25,`${r.name} died`);this.memory(state,{type:'death',title:`${r.name} died`,detail:cause,characterId:id,weight:10});return{dead:true,id};}
    applyOutcome(state,context={},roster=[]){this.ensure(state,roster);const active=[...(state.party||[])],type=String(context.type||''),outcome=String(context.outcome||'');if(outcome==='win'){this.changeMorale(state,type==='boss'?10:4,`${type==='boss'?'Boss':'Battle'} victory`);for(const id of active)this.adjust(state,id,{loyalty:type==='boss'?3:1,trust:2,respect:type==='boss'?4:2,friendship:1,fear:-1,resentment:-1},'Shared victory');}else if(outcome==='loss'){this.changeMorale(state,type==='boss'?-14:-7,'Defeat shook the party');for(const id of active){this.adjust(state,id,{trust:-2,fear:type==='boss'?7:4,respect:1,resentment:2},'Shared defeat');const roll=rngFrom(`${state.seed}|v19|wound|${state.spin}|${id}|${type}`)();if(roll<(type==='boss'?.35:.18))this.wound(state,id,type==='boss'?'severe':'minor',`${type||'Battle'} defeat`);this.betrayalCheck(state,id,roster);}}else if(type==='hazard'){this.changeMorale(state,-2,'The route remained dangerous');for(const id of active)this.adjust(state,id,{trust:1,fear:2},'Survived a hazard');}
      const quests=this.progressPersonalQuests(state,context,roster);const argument=this.maybeArgument(state,roster);this.expireGuests(state);this.syncLegacy(state);return{quests,argument};}
    storyEffect(state,effect={},reason='Story choice'){this.ensure(state);const changes={};if(Number(effect.hero||0)>0)Object.assign(changes,{trust:3,friendship:2,resentment:-2});if(Number(effect.villain||0)>0)Object.assign(changes,{fear:3,resentment:4,trust:-3});if(Number(effect.loyalty||0))changes.loyalty=Number(effect.loyalty);for(const id of state.party||[])this.adjust(state,id,changes,reason);return changes;}
    factionReaction(state,faction={}){this.ensure(state);const ethos=String(faction.ethos||''),affected=[];for(const id of state.party||[]){const r=this.record(state,id),t=r.profile.traits||{};let delta=0;if(ethos==='mercy')delta=(t.compassionate-50)/12;else if(ethos==='order')delta=(t.disciplined-t.rebellious)/16;else if(ethos==='freedom')delta=(t.rebellious-45)/12;else if(ethos==='ambition')delta=(t.ambitious-50)/12;else if(ethos==='knowledge')delta=(t.pragmatic+t.cautious-100)/20;if(Math.abs(delta)>=2){this.adjust(state,id,{trust:Math.round(delta),respect:Math.round(delta/2),resentment:Math.round(-delta/2)},`Faction alignment: ${faction.name||ethos}`);affected.push(id);}}return affected;}
    nemesisTarget(state,nemesisId){this.ensure(state);const candidates=(state.party||[]).map(id=>this.record(state,id)).sort((a,b)=>b.axes.friendship-a.axes.friendship||b.axes.loyalty-a.axes.loyalty);const target=candidates[0];if(!target)return null;target.targetedBy=String(nemesisId||'');this.adjust(state,target.id,{fear:4,friendship:2},'A nemesis targeted someone the hero cares about');return clone(target);}
    marketModifier(state){this.ensure(state);const active=(state.party||[]).map(id=>this.record(state,id));if(!active.length)return 0;const avgTrust=active.reduce((s,r)=>s+r.axes.trust,0)/active.length,avgFriend=active.reduce((s,r)=>s+r.axes.friendship,0)/active.length,rebellious=Math.max(...active.map(r=>r.profile.traits?.rebellious||0)),resentment=Math.max(...active.map(r=>r.axes.resentment));return clamp(-(avgTrust-50)*.0007-(avgFriend-50)*.0004-(rebellious>70?.025:0)+resentment*.00025,-.08,.1);}
    bondSurge(state,roster=[]){this.ensure(state,roster);const duo=this.bestDuo(state,roster),ready=Boolean(duo&&duo.score>=82&&state.v19.morale>=70);return{ready,duo:clone(duo),label:ready?'Resonant Ascension':'Bond dormant',statBonus:ready?4:0,damageBonus:ready?.08:0};}
    banter(state,roster=[],context='route'){this.ensure(state,roster);const ids=state.party||[];if(!ids.length)return[];const map=rosterMap(roster),seed=`${state.seed}|v19|banter|${state.spin}|${context}`;return ids.slice(0,3).map((id,i)=>{const r=this.record(state,id,map.get(id)),rng=rngFrom(`${seed}|${id}|${i}`),tone=r.axes.friendship>=70?'warm':r.axes.resentment>=55?'cold':r.axes.fear>=55?'uneasy':r.axes.rivalry>=50?'competitive':'steady',lines={warm:['We finish this together.','I trust the call.','Still here. Still with you.'],cold:['Do not make me regret staying.','I am watching what you choose.','This team is running out of excuses.'],uneasy:['Something about this route feels wrong.','Keep an exit open.','I would rather survive than prove a point.'],competitive:['Try to keep up.','I can do better than that.','Next win is mine.'],steady:['Route looks clear enough.','Ready when you are.','Let us keep moving.']};return{id,name:r.name,tone,text:lines[tone][Math.floor(rng()*lines[tone].length)]};});}
    ending(state){this.ensure(state);const records=Object.values(state.v19.records),living=records.filter(r=>!['dead','defected'].includes(r.status)),dead=records.filter(r=>r.status==='dead'),defected=records.filter(r=>r.status==='defected'),devoted=living.filter(r=>r.axes.friendship>=75&&r.axes.trust>=70),rivals=living.filter(r=>r.axes.rivalry>=60);let id='surviving-company',label='The Surviving Company',detail='The party reaches the end changed, but still connected.';if(dead.length>=2){id='scarred-victory';label='The Names They Carry';detail='Victory is measured against the people the route did not return.';}else if(defected.length>=2){id='fractured-alliance';label='The Fractured Alliance';detail='The multiverse survives, but betrayal defines the final memory.';}else if(devoted.length>=Math.max(2,living.length-1)){id='found-family';label='Found Across Worlds';detail='The party becomes a family stronger than the universes that separated them.';}else if(rivals.length>=2){id='legendary-rivals';label='Rivals to the Horizon';detail='Competition becomes the force that keeps the group moving forward.';}return{id,label,detail,morale:state.v19.morale,dead:dead.map(r=>r.id),defected:defected.map(r=>r.id),devoted:devoted.map(r=>r.id)};}
    memory(state,m={}){const entry={id:m.id||`pm-${hash32(`${state.seed}|${state.spin}|${m.title}|${state.v19.memories.length}`).toString(36)}`,spin:Number(state.spin||0),at:Date.now(),type:String(m.type||'party'),title:String(m.title||'The party remembered'),detail:String(m.detail||''),characterId:String(m.characterId||''),weight:Number(m.weight||3)};state.v19.memories.push(entry);state.v19.memories=state.v19.memories.slice(-MAX_MEMORIES);return entry;}
    summary(state,roster=[]){this.ensure(state,roster);const map=rosterMap(roster),active=(state.party||[]).map(id=>this.record(state,id,map.get(id))),bench=state.v19.benchIds.map(id=>this.record(state,id,map.get(id))),duo=this.bestDuo(state,roster),open=state.v19.incidents.filter(i=>i.status==='open');return{morale:state.v19.morale,active:active.map(clone),bench:bench.map(clone),guests:state.v19.guests.map(clone),duo:clone(duo),surge:this.bondSurge(state,roster),openIncidents:open.map(clone),personalQuests:clone(state.v19.personalQuests),mentorBonds:clone(state.v19.mentorBonds),ending:this.ending(state),memories:state.v19.memories.slice(-12).reverse().map(clone),stats:clone(state.v19.stats)};}
  }
  function migrateV19(state={},roster=[]){return new PartyConsequencesEngine().ensure(state,roster);}
  const api={V19_SCHEMA_VERSION,AXES,TRAITS,QUESTS,PartyConsequencesEngine,migrateV19};root.MultiverseDomain=Object.assign(root.MultiverseDomain||{},api);if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:window);
