'use strict';

(function attachV20Engine(root){
  const V20_SCHEMA_VERSION=20;
  const STAT_KEYS=['might','defense','speed','skill','mind','energy','hax'];
  const SET_DEFS={
    'rift-vanguard':{label:'Rift Vanguard',two:{might:3,speed:2},four:{might:4,defense:3},tags:['rift','assault']},
    'paradox-savant':{label:'Paradox Savant',two:{mind:3,energy:2},four:{hax:4,skill:3},tags:['relic','knowledge']},
    'world-warden':{label:'World Warden',two:{defense:3,mind:2},four:{defense:4,energy:3},tags:['guardian','stability']},
    'starbound-hunter':{label:'Starbound Hunter',two:{speed:3,skill:2},four:{skill:4,might:3},tags:['hunter','precision']},
    'void-covenant':{label:'Void Covenant',two:{hax:3,energy:2},four:{hax:5,might:2},tags:['void','forbidden']}
  };
  const PERSONALITIES={
    guardian:{label:'Guardian',favored:['defense','mind'],events:['battle','hazard'],temptation:'Protect at any cost.'},
    seeker:{label:'Seeker',favored:['mind','skill'],events:['travel','rare'],temptation:'No truth is forbidden.'},
    sovereign:{label:'Sovereign',favored:['might','hax'],events:['boss','faction'],temptation:'Power should answer to one will.'},
    trickster:{label:'Trickster',favored:['speed','hax'],events:['rare','travel'],temptation:'Rules exist to be bent.'},
    sage:{label:'Sage',favored:['mind','energy'],events:['training','artifact'],temptation:'Sacrifice certainty for knowledge.'},
    avenger:{label:'Avenger',favored:['might','skill'],events:['battle','boss'],temptation:'Never forgive a debt.'}
  };
  const RANKS=['Initiate','Familiar','Veteran','Masterwork','Signature','Ascendant'];
  const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
  const hash32=value=>{if(root.MultiverseDomain?.hash32)return root.MultiverseDomain.hash32(String(value));let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
  const normalize=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'unknown';
  const rngFrom=key=>{let x=hash32(key)||0x9e3779b9;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};};
  const choose=(list,rng)=>list[Math.floor(rng()*list.length)%list.length];
  const addStats=(out,src,scale=1)=>{for(const k of STAT_KEYS)out[k]=(out[k]||0)+Number(src?.[k]||0)*scale;return out;};
  const zeroStats=()=>Object.fromEntries(STAT_KEYS.map(k=>[k,0]));
  const currentWorld=state=>String(state.v16?.currentUniverse||state.customCharacter?.homeworld||'Unknown');
  const currentMarketKey=state=>{try{return new root.MultiverseDomain.EconomyCraftingEngine().marketKey(state);}catch{return`${normalize(currentWorld(state))}:crossroads`;}};

  class RelicMasteryEngine{
    ensure(state={},artifacts=[],roster=[]){
      if(root.MultiverseDomain?.migrateV19)root.MultiverseDomain.migrateV19(state,roster);
      state.v20||={};const v=state.v20;
      v.schemaVersion=V20_SCHEMA_VERSION;state.v20Version=V20_SCHEMA_VERSION;state.schemaVersion=Math.max(Number(state.schemaVersion||0),V20_SCHEMA_VERSION);
      v.gear=v.gear&&typeof v.gear==='object'?v.gear:{};
      v.relics=v.relics&&typeof v.relics==='object'?v.relics:{};
      v.vendorLoyalty=v.vendorLoyalty&&typeof v.vendorLoyalty==='object'?v.vendorLoyalty:{};
      v.disputes=Array.isArray(v.disputes)?v.disputes.slice(-40):[];
      v.chronicle=Array.isArray(v.chronicle)?v.chronicle.slice(-180):[];
      v.processedEvents=Array.isArray(v.processedEvents)?v.processedEvents.slice(-180):[];
      v.forgeCounter=Math.max(0,Number(v.forgeCounter||0));
      v.stats={masteryLevels:0,signatures:0,awakenedGear:0,setPiecesForged:0,reforges:0,relicAttunements:0,relicQuests:0,purifications:0,corruptions:0,relicAwakenings:0,relicThefts:0,relicRecoveries:0,disputes:0,vendorRanks:0,...(v.stats||{})};
      this.syncGear(state);this.syncRelics(state,artifacts);this.vendor(state);return state;
    }

    gearRecord(state,item={}){
      const id=String(item.id||'');if(!id)return null;const existing=state.v20.gear[id]||{},setId=existing.setId||item.v20SetId||this.defaultSet(item);
      const rec=state.v20.gear[id]={id,setId,xp:Math.max(0,Number(existing.xp||0)),level:clamp(existing.level||1,1,10),signatureName:String(existing.signatureName||''),awakened:Boolean(existing.awakened),history:Array.isArray(existing.history)?existing.history.slice(-20):[],ownerId:String(existing.ownerId||'hero')};
      if(rec.level>=10)rec.awakened=true;return rec;
    }
    syncGear(state){
      const ids=new Set();for(const item of state.lootInventory||[]){if(!item?.id)continue;ids.add(String(item.id));const r=this.gearRecord(state,item);item.v20SetId=r.setId;}
      for(const [id,r] of Object.entries(state.v20.gear))if(!ids.has(id))r.archived=true;else delete r.archived;return state.v20.gear;
    }
    defaultSet(item={}){if(item.cursed||item.tags?.includes('forbidden'))return'void-covenant';const ids=Object.keys(SET_DEFS).filter(id=>id!=='void-covenant');return ids[hash32(`${item.name}|${item.slot}|v20-set`)%ids.length];}
    masteryThreshold(level){return 24+Math.max(1,Number(level))*18;}
    rank(level){return RANKS[Math.min(RANKS.length-1,Math.floor((Math.max(1,level)-1)/2))];}
    displayName(state,item={}){const r=this.gearRecord(state,item);return r?.signatureName||item.name||item.id;}
    gainGearMastery(state,{type='battle',outcome='success'}={}){
      if(outcome==='loss')return[];const gain=type==='boss'?34:type==='battle'?16:type==='training'?10:5,leveled=[];const equipped=new Set(Object.values(state.equipment||{}));
      for(const item of (state.lootInventory||[]).filter(i=>equipped.has(i.id))){const r=this.gearRecord(state,item);r.xp+=gain;while(r.level<10&&r.xp>=this.masteryThreshold(r.level)){r.xp-=this.masteryThreshold(r.level);r.level++;state.v20.stats.masteryLevels++;leveled.push({id:r.id,level:r.level,name:this.displayName(state,item)});}if(r.level>=10&&!r.awakened){r.awakened=true;state.v20.stats.awakenedGear++;this.chronicle(state,'gear-awakened',`${this.displayName(state,item)} awakened`,`Mastery reached Level 10.`);}}
      return leveled;
    }
    masteryBonuses(state){
      const out=zeroStats(),equipped=new Set(Object.values(state.equipment||{}));for(const item of (state.lootInventory||[]).filter(i=>equipped.has(i.id))){const r=this.gearRecord(state,item),step=Math.floor((r.level-1)/2);for(const k of Object.keys(item.bonuses||{}))if(STAT_KEYS.includes(k))out[k]+=step;if(r.signatureName)out.skill+=1;if(r.awakened){const primary=Object.entries(item.bonuses||{}).sort((a,b)=>Number(b[1])-Number(a[1]))[0]?.[0];if(STAT_KEYS.includes(primary))out[primary]+=2;}}
      addStats(out,this.setBonuses(state).stats);return out;
    }
    setBonuses(state){
      const counts={},pieces={},equipped=new Set(Object.values(state.equipment||{}));for(const item of (state.lootInventory||[]).filter(i=>equipped.has(i.id))){const r=this.gearRecord(state,item);counts[r.setId]=(counts[r.setId]||0)+1;(pieces[r.setId]||=[]).push(item.id);}const stats=zeroStats(),active=[];
      for(const [id,count] of Object.entries(counts)){const def=this.setDefinition(state,id);if(!def)continue;const bonuses=zeroStats();if(count>=2)addStats(bonuses,def.two);if(count>=4)addStats(bonuses,def.four);addStats(stats,bonuses);active.push({id,label:def.label,count,bonuses,pieces:pieces[id]||[]});}return{stats,active};
    }
    setDefinition(state,id){if(SET_DEFS[id])return SET_DEFS[id];if(String(id).startsWith('faction:')){const faction=state.v16?.factions?.[String(id).slice(8)],ethos=faction?.ethos||'balance',map={mercy:{defense:3,mind:2},knowledge:{mind:3,hax:2},freedom:{speed:3,skill:2},order:{defense:3,might:2},balance:{energy:3,mind:2},ambition:{might:3,hax:2}};const two=map[ethos]||map.balance,four=Object.fromEntries(Object.entries(two).map(([k,v])=>[k,v+2]));return{label:`${faction?.name||'Faction'} Regalia`,two,four,tags:['faction',ethos]};}return null;}
    unlockedFactionSet(state){const best=Object.values(state.v16?.factions||{}).sort((a,b)=>Number(b.reputation||0)-Number(a.reputation||0))[0];return best&&Number(best.reputation||0)>=35?`faction:${best.id}`:'';}
    availableSets(state){const ids=Object.keys(SET_DEFS).filter(id=>id!=='void-covenant');const faction=this.unlockedFactionSet(state);if(faction)ids.push(faction);if(Number(state.v18?.wallet?.voidMarks||0)>=2)ids.push('void-covenant');return ids.map(id=>({id,...this.setDefinition(state,id)}));}
    forgeSetPiece(state,setId,slot='weapon'){
      this.ensure(state);if((state.lootInventory||[]).length>=24)return{ok:false,error:'Equipment inventory is full.'};const def=this.setDefinition(state,setId);if(!def)return{ok:false,error:'That equipment set is not unlocked.'};if(!this.availableSets(state).some(x=>x.id===setId))return{ok:false,error:'That set is still locked.'};const allowed=['weapon','armor','focus','charm'];if(!allowed.includes(slot))return{ok:false,error:'Unknown equipment slot.'};const cost={salvage:setId==='void-covenant'?18:26,cosmicFragments:4,...(setId==='void-covenant'?{voidMarks:2}:{})},econ=new root.MultiverseDomain.EconomyCraftingEngine();if(!econ.pay(state,cost))return{ok:false,error:'Required forge materials are missing.'};state.v20.forgeCounter++;const rng=rngFrom(`${state.seed}|v20|set|${setId}|${slot}|${state.v20.forgeCounter}`),statPool=STAT_KEYS.slice(),a=statPool.splice(Math.floor(rng()*statPool.length),1)[0],b=statPool[Math.floor(rng()*statPool.length)],item={id:`v20-${hash32(`${state.seed}|${setId}|${slot}|${state.v20.forgeCounter}`).toString(36)}`,name:`${def.label} ${slot[0].toUpperCase()+slot.slice(1)}`,kind:'equipment',slot,rarity:setId==='void-covenant'?'forbidden':'legendary',bonuses:{[a]:7,[b]:5},tags:[...(def.tags||[]),'v20-set'],cursed:setId==='void-covenant',crafted:true,enchant:0,baseValue:170,v20SetId:setId};state.lootInventory.push(item);this.gearRecord(state,item);state.v20.stats.setPiecesForged++;this.noteCommerce(state,'forge',170);this.chronicle(state,'set-forge',`Forged ${item.name}`,`A ${slot} piece of ${def.label}.`);return{ok:true,item:clone(item),cost};
    }
    reforgeSet(state,itemId,setId){this.ensure(state);const item=(state.lootInventory||[]).find(x=>x.id===itemId),def=this.setDefinition(state,setId);if(!item)return{ok:false,error:'Equipment not found.'};if(!def||!this.availableSets(state).some(x=>x.id===setId))return{ok:false,error:'That set is not unlocked.'};const econ=new root.MultiverseDomain.EconomyCraftingEngine(),cost={salvage:10,cosmicFragments:2};if(!econ.pay(state,cost))return{ok:false,error:'Need 10 Salvage and 2 Cosmic Fragments.'};const r=this.gearRecord(state,item);r.setId=setId;item.v20SetId=setId;r.history.push({spin:Number(state.spin||0),type:'reforge',setId});state.v20.stats.reforges++;this.chronicle(state,'reforge',`${this.displayName(state,item)} reforged`,`Bound to ${def.label}.`);return{ok:true,item:clone(item),setId};}
    nameSignature(state,itemId,name=''){this.ensure(state);const item=(state.lootInventory||[]).find(x=>x.id===itemId);if(!item)return{ok:false,error:'Equipment not found.'};const r=this.gearRecord(state,item);if(r.level<6)return{ok:false,error:'Mastery Level 6 is required before equipment can become a signature item.'};if(r.signatureName)return{ok:false,error:'This item already has a signature name.'};const hero=state.customCharacter?.codename||state.customCharacter?.name||'Wayfarer';r.signatureName=String(name||`${hero}'s ${item.name}`).slice(0,64);state.v20.stats.signatures++;this.chronicle(state,'signature',`${r.signatureName} became a signature weapon`,`Mastery Level ${r.level}.`);return{ok:true,name:r.signatureName};}

    personality(id){const keys=Object.keys(PERSONALITIES),key=keys[hash32(`${id}|v20-relic-mind`)%keys.length];return{id:key,...clone(PERSONALITIES[key])};}
    relicRecord(state,id,artifact={}){
      id=String(id);const existing=state.v20.relics[id]||{},p=existing.personality||this.personality(id);const owned=(state.artifacts||[]).includes(id),status=existing.status||(owned?'owned':'lost');
      const rec=state.v20.relics[id]={id,name:String(artifact?.name||existing.name||id),personality:p,bond:clamp(existing.bond??12,0,100),purity:clamp(existing.purity??75,0,100),corruption:clamp(existing.corruption??0,0,100),bearerId:String(existing.bearerId||''),status:owned&&status!=='stolen'?'owned':status,awakened:Boolean(existing.awakened),stolenBy:String(existing.stolenBy||''),stolenWorld:String(existing.stolenWorld||''),claimedBy:String(existing.claimedBy||''),disputedBy:Array.isArray(existing.disputedBy)?existing.disputedBy.slice(0,4):[],quest:existing.quest||this.makeRelicQuest(id,p),history:Array.isArray(existing.history)?existing.history.slice(-28):[],evolutionSnapshot:existing.evolutionSnapshot||null};return rec;
    }
    syncRelics(state,artifacts=[]){const map=new Map((artifacts||[]).map(a=>[String(a.id),a]));for(const id of state.artifacts||[])this.relicRecord(state,id,map.get(String(id)));for(const [id,r] of Object.entries(state.v20.relics)){if((state.artifacts||[]).includes(id)&&r.status!=='stolen')r.status='owned';else if(!['stolen','sold','consumed'].includes(r.status))r.status='lost';}return state.v20.relics;}
    makeRelicQuest(id,p=this.personality(id)){const target=p.id==='sovereign'||p.id==='avenger'?2:3;return{id:`rq-${hash32(`${id}|${p.id}`).toString(36)}`,label:{guardian:'Stand Between Worlds',seeker:'Trace the Impossible',sovereign:'Claim a Worthy Victory',trickster:'Break a Rule and Survive',sage:'Teach the Relic a New Truth',avenger:'Settle the Blood Debt'}[p.id]||'Awaken the Relic',events:p.events.slice(),target,progress:0,status:'active'};}
    attune(state,id,bearerId='hero',roster=[]){this.ensure(state,[],roster);const r=this.relicRecord(state,id);if(!(state.artifacts||[]).includes(id)||r.status==='stolen')return{ok:false,error:'That relic is not currently in your possession.'};if(bearerId!=='hero'){const rel=state.v19?.records?.[bearerId];if(!rel||!['active','bench'].includes(rel.status))return{ok:false,error:'That bearer is not part of the party.'};if(Number(rel.axes?.trust||0)<40)return{ok:false,error:'Trust 40 is required before an ally will accept attunement.'};}
      r.bearerId=String(bearerId);r.bond=clamp(r.bond+8,0,100);state.v20.stats.relicAttunements++;r.history.push({spin:Number(state.spin||0),type:'attune',bearerId});this.chronicle(state,'attune',`${r.name} attuned`,bearerId==='hero'?'The relic chose the hero.':`The relic chose ${state.v19?.records?.[bearerId]?.name||bearerId}.`);return{ok:true,relic:clone(r)};
    }
    relicBonuses(state){const out=zeroStats();for(const r of Object.values(state.v20.relics)){if(r.status!=='owned'||!r.bearerId)continue;const tier=Math.floor(r.bond/25),fav=r.personality.favored||[];for(const k of fav)out[k]+=tier;if(r.awakened)for(const k of fav)out[k]+=2;if(r.purity>=85)out.mind+=1;if(r.corruption>=50){out.hax+=Math.floor(r.corruption/30);out.defense-=Math.floor(r.corruption/40);}if(r.bearerId!=='hero'){const rel=state.v19?.records?.[r.bearerId];if(rel&&Number(rel.axes?.trust||0)>=70&&Number(rel.axes?.friendship||0)>=65)for(const k of fav)out[k]+=1;}}
      return out;
    }
    progressRelics(state,context={}){
      const completed=[],awakened=[];for(const id of state.artifacts||[]){const r=this.relicRecord(state,id),type=String(context.type||''),outcome=String(context.outcome||'');if(r.status!=='owned')continue;const gain=outcome==='win'?(type==='boss'?9:type==='battle'?5:3):outcome==='loss'?-1:2;r.bond=clamp(r.bond+gain,0,100);if(type==='forbidden'||context.forbidden){r.corruption=clamp(r.corruption+10,0,100);r.purity=clamp(r.purity-5,0,100);}if(outcome==='loss'){r.corruption=clamp(r.corruption+(type==='boss'?4:2),0,100);}if(r.quest?.status==='active'&&r.quest.events.includes(type)&&(outcome!=='loss'||type==='travel')){r.quest.progress=Math.min(r.quest.target,r.quest.progress+1);if(r.quest.progress>=r.quest.target){r.quest.status='completed';r.bond=clamp(r.bond+12,0,100);r.purity=clamp(r.purity+8,0,100);state.v20.stats.relicQuests++;completed.push(clone(r));this.chronicle(state,'relic-quest',`${r.name}: ${r.quest.label} complete`,`Bond ${Math.round(r.bond)} • Purity ${Math.round(r.purity)}.`);}}
        const evo=state.v18?.artifactEvolution?.[id];if(!r.awakened&&r.bond>=80&&r.purity>=55&&(r.quest?.status==='completed'||Number(evo?.level||1)>=4)){r.awakened=true;state.v20.stats.relicAwakenings++;awakened.push(clone(r));this.chronicle(state,'relic-awakened',`${r.name} awakened`,`${r.personality.label} resonance reached full expression.`);}}
      return{completed,awakened};
    }
    purify(state,id){this.ensure(state);const r=this.relicRecord(state,id);if(r.status!=='owned')return{ok:false,error:'Only an owned relic can be purified.'};if(r.corruption<=0)return{ok:false,error:'This relic has no corruption to purge.'};const econ=new root.MultiverseDomain.EconomyCraftingEngine(),cost={cosmicFragments:Math.max(1,Math.ceil(r.corruption/25)),salvage:6};if(!econ.pay(state,cost))return{ok:false,error:'Not enough purification materials.'};r.corruption=clamp(r.corruption-30,0,100);r.purity=clamp(r.purity+18,0,100);r.bond=clamp(r.bond+3,0,100);state.v20.stats.purifications++;this.chronicle(state,'purification',`${r.name} purified`,`Corruption fell to ${Math.round(r.corruption)}%.`);return{ok:true,relic:clone(r),cost};}
    embraceCorruption(state,id){this.ensure(state);const r=this.relicRecord(state,id);if(r.status!=='owned')return{ok:false,error:'Only an owned relic can answer the temptation.'};r.corruption=clamp(r.corruption+20,0,100);r.purity=clamp(r.purity-10,0,100);r.bond=clamp(r.bond+7,0,100);state.v20.stats.corruptions++;this.chronicle(state,'corruption',`${r.name} was allowed to feed`,r.personality.temptation);return{ok:true,relic:clone(r)};}
    claimArtifact(state,id,allyId){this.ensure(state);const r=this.relicRecord(state,id),rel=state.v19?.records?.[allyId];if(r.status!=='owned')return{ok:false,error:'Relic is not available.'};if(!rel||!['active','bench'].includes(rel.status))return{ok:false,error:'Ally is unavailable.'};r.claimedBy=String(allyId);r.bearerId=String(allyId);r.disputedBy=[];r.bond=clamp(r.bond+5,0,100);try{new root.MultiverseDomain.PartyConsequencesEngine().adjust(state,allyId,{trust:3,respect:3,friendship:2},`Entrusted with ${r.name}`);}catch{}this.chronicle(state,'relic-claim',`${rel.name} claimed ${r.name}`,'The party accepted the bond.');return{ok:true,relic:clone(r)};}
    maybeDispute(state,id){const r=this.relicRecord(state,id),active=(state.party||[]).map(x=>state.v19?.records?.[x]).filter(Boolean).filter(x=>Number(x.axes?.respect||0)>=55);if(r.status!=='owned'||active.length<2||r.claimedBy)return null;const sorted=active.sort((a,b)=>(Number(b.axes.friendship||0)+Number(b.axes.respect||0))-(Number(a.axes.friendship||0)+Number(a.axes.respect||0)));if(hash32(`${state.seed}|${id}|${state.spin}|dispute`)%100>=18)return null;r.disputedBy=sorted.slice(0,2).map(x=>x.id);const d={id:`d-${hash32(`${id}|${state.spin}`).toString(36)}`,artifactId:id,allies:r.disputedBy,status:'open',spin:Number(state.spin||0)};state.v20.disputes.push(d);state.v20.stats.disputes++;this.chronicle(state,'relic-dispute',`${r.name} divided the party`,`${sorted[0].name} and ${sorted[1].name} both believe they should carry it.`);return d;}
    resolveDispute(state,artifactId,winnerId){const d=[...state.v20.disputes].reverse().find(x=>x.artifactId===artifactId&&x.status==='open');if(!d||!d.allies.includes(winnerId))return{ok:false,error:'No matching open relic dispute.'};d.status='resolved';d.winnerId=winnerId;const r=this.relicRecord(state,artifactId);r.claimedBy=winnerId;r.bearerId=winnerId;r.disputedBy=[];try{const party=new root.MultiverseDomain.PartyConsequencesEngine();for(const id of d.allies)party.adjust(state,id,id===winnerId?{trust:2,respect:4}:{respect:-2,resentment:3},id===winnerId?`Won claim to ${r.name}`:`Lost claim to ${r.name}`);}catch{}return{ok:true,dispute:clone(d)};}
    maybeSteal(state,context={}){if(context.outcome!=='loss'||!['battle','boss'].includes(context.type))return null;const enemyId=String(context.enemyId||''),nemesis=state.v16?.nemeses?.[enemyId];if(!nemesis)return null;const candidates=(state.artifacts||[]).map(id=>this.relicRecord(state,id)).filter(r=>r.status==='owned'&&r.bond>=30);if(!candidates.length)return null;const rng=rngFrom(`${state.seed}|v20|theft|${state.spin}|${enemyId}`);if(!context.forceTheft&&rng()>(context.type==='boss'?.28:.14))return null;const r=choose(candidates,rng);r.evolutionSnapshot=clone(state.v18?.artifactEvolution?.[r.id]||null);state.artifacts=state.artifacts.filter(id=>id!==r.id);r.status='stolen';r.stolenBy=enemyId;r.stolenWorld=nemesis.universe||currentWorld(state);nemesis.stolenArtifacts=Array.isArray(nemesis.stolenArtifacts)?nemesis.stolenArtifacts:[];if(!nemesis.stolenArtifacts.includes(r.id))nemesis.stolenArtifacts.push(r.id);if(state.v16?.artifactOwners)state.v16.artifactOwners[r.id]={artifactId:r.id,ownerType:'nemesis',ownerId:enemyId,sinceTick:Number(state.v16.clock?.tick||0)};state.v20.stats.relicThefts++;this.chronicle(state,'relic-theft',`${nemesis.name||enemyId} stole ${r.name}`,`Last seen in ${r.stolenWorld}.`);return clone(r);}
    recoverFromNemesis(state,enemyId){const recovered=[];for(const r of Object.values(state.v20.relics).filter(x=>x.status==='stolen'&&x.stolenBy===String(enemyId))){if(!state.artifacts.includes(r.id))state.artifacts.push(r.id);r.status='owned';r.stolenBy='';r.stolenWorld='';if(r.evolutionSnapshot){state.v18.artifactEvolution[r.id]=clone(r.evolutionSnapshot);r.evolutionSnapshot=null;}if(state.v16?.artifactOwners)state.v16.artifactOwners[r.id]={artifactId:r.id,ownerType:'player',ownerId:'player',sinceTick:Number(state.v16.clock?.tick||0)};recovered.push(clone(r));state.v20.stats.relicRecoveries++;this.chronicle(state,'relic-recovery',`${r.name} recovered`,`Taken back from ${state.v16?.nemeses?.[enemyId]?.name||enemyId}.`);}const n=state.v16?.nemeses?.[enemyId];if(n)n.stolenArtifacts=(n.stolenArtifacts||[]).filter(id=>!recovered.some(r=>r.id===id));return recovered;}
    convergence(state){const awakened=Object.values(state.v20.relics).filter(r=>r.status==='owned'&&r.awakened&&r.bearerId),party=state.v19&&root.MultiverseDomain?.PartyConsequencesEngine?new root.MultiverseDomain.PartyConsequencesEngine():null,duo=party?.bestDuo(state,[]);const ready=Boolean(awakened.length&&Number(state.v19?.morale||0)>=75&&Number(duo?.score||0)>=82);return{ready,label:'Legacy Convergence',statBonus:ready?2:0,relic:awakened[0]||null,duo:clone(duo)};}
    processOutcome(state,context={},artifacts=[],roster=[]){this.ensure(state,artifacts,roster);const key=`${state.spin}:${context.type}:${context.outcome}:${context.enemyId||''}`;if(state.v20.processedEvents.includes(key))return null;state.v20.processedEvents.push(key);const leveled=this.gainGearMastery(state,context),relics=this.progressRelics(state,context),theft=this.maybeSteal(state,context),recovered=context.outcome==='win'&&context.enemyId?this.recoverFromNemesis(state,context.enemyId):[];for(const id of state.artifacts||[])this.maybeDispute(state,id);return{leveled,relics,theft,recovered,convergence:this.convergence(state)};}

    vendor(state,key=currentMarketKey(state)){const existing=state.v20.vendorLoyalty[key]||{},points=Math.max(0,Number(existing.points||0)),rank=points>=220?5:points>=140?4:points>=80?3:points>=35?2:points>=12?1:0;return state.v20.vendorLoyalty[key]={key,points,rank,transactions:Number(existing.transactions||0),lastType:String(existing.lastType||'')};}
    noteCommerce(state,type='trade',amount=0){const v=this.vendor(state),before=v.rank;v.points+=Math.max(1,Math.round(2+Math.min(12,Number(amount||0)/75)));v.transactions++;v.lastType=type;const next=this.vendor(state,v.key);if(next.rank>before){state.v20.stats.vendorRanks++;this.chronicle(state,'vendor-rank',`Vendor loyalty reached Rank ${next.rank}`,`${v.key} now offers stronger discounts and forge access.`);}return next;}
    vendorDiscount(state){const v=this.vendor(state),best=Object.values(state.v16?.factions||{}).reduce((m,f)=>Math.max(m,Number(f.reputation||0)),0);return clamp(v.rank*.02+Math.max(0,best-25)*.0008,0,.14);}
    discountedPrice(state,price){return Math.max(1,Math.round(Number(price||1)*(1-this.vendorDiscount(state))));}

    chronicle(state,type,title,detail=''){const entry={id:`v20-${hash32(`${type}|${title}|${state.spin}|${state.v20.chronicle.length}`).toString(36)}`,spin:Number(state.spin||0),tick:Number(state.v16?.clock?.tick||0),type:String(type),title:String(title).slice(0,120),detail:String(detail).slice(0,360)};state.v20.chronicle.push(entry);state.v20.chronicle=state.v20.chronicle.slice(-180);try{new root.MultiverseDomain.LivingMultiverseEngine().recordMemory(state,{type:'artifact',title:entry.title,detail:entry.detail,weight:5});}catch{}return entry;}
    epilogue(state){const sig=Object.values(state.v20.gear).filter(r=>r.signatureName).length,awake=Object.values(state.v20.relics).filter(r=>r.awakened).length,stolen=Object.values(state.v20.relics).filter(r=>r.status==='stolen').length,corrupt=Object.values(state.v20.relics).filter(r=>r.corruption>=65).length;if(stolen)return{id:'unfinished-recovery',title:'The Relics Still Call',text:`${stolen} bonded relic${stolen===1?' remains':'s remain'} somewhere in enemy hands. The ending leaves a route open.`};if(corrupt)return{id:'crowned-by-ruin',title:'Crowned by Ruin',text:'The hero won, but the relics learned the shape of their compromises.'};if(awake>=2&&sig>=1)return{id:'legacy-armory',title:'The Living Armory',text:'Signature equipment and awakened relics became a legacy that could outlive the timeline.'};if(awake)return{id:'relic-bond',title:'The Relic Remembers',text:'An awakened relic chose to carry this timeline forward in memory.'};return{id:'tools-of-the-road',title:'Tools of the Road',text:'The gear remained equipment rather than destiny—but every mark on it remembers the journey.'};}
    summary(state,artifacts=[],roster=[]){this.ensure(state,artifacts,roster);const gear=(state.lootInventory||[]).map(item=>({item:clone(item),mastery:clone(this.gearRecord(state,item)),equipped:Object.values(state.equipment||{}).includes(item.id)})),owned=(state.artifacts||[]).map(id=>clone(this.relicRecord(state,id,(artifacts||[]).find(a=>String(a.id)===String(id))))),stolen=Object.values(state.v20.relics).filter(r=>r.status==='stolen').map(clone),sets=this.setBonuses(state),vendor=clone(this.vendor(state));return{gear,relics:owned,stolen,sets,vendor,discount:this.vendorDiscount(state),availableSets:this.availableSets(state),convergence:this.convergence(state),disputes:state.v20.disputes.filter(d=>d.status==='open').map(clone),chronicle:state.v20.chronicle.slice(-20).map(clone),epilogue:this.epilogue(state),stats:clone(state.v20.stats)};}
  }

  function migrateV20(state={},artifacts=[],roster=[]){return new RelicMasteryEngine().ensure(state,artifacts,roster);}
  const api={V20_SCHEMA_VERSION,STAT_KEYS_V20:STAT_KEYS,SET_DEFS,RELIC_PERSONALITIES:PERSONALITIES,RelicMasteryEngine,migrateV20};
  root.MultiverseDomain=Object.assign(root.MultiverseDomain||{},api);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:window);
