'use strict';

(function attachV21Engine(root){
  const V21_SCHEMA_VERSION=21;
  const RANKS=[
    {level:1,id:'outsider',label:'Outsider',xp:0,rep:-100,authority:0},
    {level:2,id:'associate',label:'Associate',xp:20,rep:5,authority:0},
    {level:3,id:'operative',label:'Operative',xp:55,rep:15,authority:5},
    {level:4,id:'veteran',label:'Veteran',xp:105,rep:25,authority:10},
    {level:5,id:'captain',label:'Captain',xp:170,rep:35,authority:20},
    {level:6,id:'commander',label:'Commander',xp:250,rep:45,authority:30},
    {level:7,id:'champion',label:'Champion',xp:345,rep:60,authority:45},
    {level:8,id:'regent',label:'Regent',xp:455,rep:75,authority:60}
  ];
  const CAMPAIGN_DEFS={
    'border-war':{label:'Border War',summary:'Break an enemy push and decide what happens after the siege.',operations:[['travel'],['battle','boss'],['hazard','battle']],targets:[1,2,1],choices:['assault','diplomacy','withdraw']},
    liberation:{label:'Liberation Campaign',summary:'Undermine an occupation, rally local support, and decide who governs next.',operations:[['travel','rare'],['recruit','v14-saga'],['battle','boss']],targets:[1,2,2],choices:['local-rule','faction-rule','independent-cell']},
    'relic-crusade':{label:'Relic Crusade',summary:'Race rival powers for a relic whose ownership can change the political balance.',operations:[['rare','artifact'],['travel','hazard'],['artifact','boss']],targets:[1,1,1],choices:['return-relic','keep-relic','destroy-relic']},
    succession:{label:'Succession Crisis',summary:'A leadership vacuum turns faction politics into an operational crisis.',operations:[['rare','v14-saga'],['recruit','travel'],['battle','v14-saga']],targets:[1,1,1],choices:['support-reformer','support-hardliner','reconcile']},
    stabilization:{label:'Reality Stabilization',summary:'Secure a failing reality while specialists repair the systems holding it together.',operations:[['hazard'],['training','travel'],['battle','artifact']],targets:[2,1,1],choices:['stabilize','evacuate','seal-route']},
    schism:{label:'Faction Schism',summary:'An internal split forces the player to choose unity, a splinter cause, or independence.',operations:[['rare','recruit'],['v14-saga','travel'],['battle','boss']],targets:[1,1,1],choices:['reconcile','support-splinter','break-away']}
  };
  const FACILITY_DEFS={
    command:{label:'Command Center',cost:{credits:180,salvage:16,cosmicFragments:2},max:3,bonus:'campaign'},
    forge:{label:'Forge',cost:{credits:140,salvage:24,cosmicFragments:3},max:3,bonus:'forge'},
    vault:{label:'Relic Vault',cost:{credits:160,salvage:16,cosmicFragments:4},max:3,bonus:'relic'},
    medical:{label:'Medical Bay',cost:{credits:120,salvage:14,cosmicFragments:1},max:3,bonus:'medical'},
    training:{label:'Training Hall',cost:{credits:120,salvage:16,cosmicFragments:1},max:3,bonus:'training'},
    intelligence:{label:'Intelligence Wing',cost:{credits:170,salvage:18,cosmicFragments:2},max:3,bonus:'infiltration'},
    portal:{label:'Portal Nexus',cost:{credits:210,salvage:20,cosmicFragments:5},max:3,bonus:'travel'},
    quartermaster:{label:'Quartermaster',cost:{credits:130,salvage:18,cosmicFragments:1},max:3,bonus:'supply'},
    embassy:{label:'Embassy',cost:{credits:150,salvage:12,cosmicFragments:2},max:3,bonus:'diplomacy'},
    defense:{label:'Defense Grid',cost:{credits:190,salvage:26,cosmicFragments:2},max:3,bonus:'defense'}
  };
  const SPECIALIST_ROLES=['quartermaster','smith','relic-keeper','field-medic','intelligence-officer','diplomat','trainer','portal-engineer','archivist','defense-commander'];
  const TERRITORY_TYPES=['crossroads','metropolis','archive','warfront','sanctuary','laboratory','arena','shrine','black-market','fracture-zone'];
  const TECHNIQUES={guardian:'Guardian Intercept',archivist:'Archivist Countermeasure',liberator:'Liberator Breakthrough',imperial:'Imperial Formation',mystic:'Mystic Equilibrium',broker:'Broker Advantage'};
  const clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
  const normalize=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'unknown';
  const hash32=value=>{if(root.MultiverseDomain?.hash32)return root.MultiverseDomain.hash32(String(value));let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
  const rngFrom=key=>{let x=hash32(key)||0x9e3779b9;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;};};
  const choose=(list,rng)=>list[Math.floor(rng()*list.length)%Math.max(1,list.length)];
  const tick=state=>Number(state.v16?.clock?.tick||0);
  const worldName=state=>String(state.v16?.currentUniverse||state.customCharacter?.homeworld||'Earth-Prime');
  const factionList=state=>Object.values(state.v16?.factions||{});
  const costScale=(cost,level=1)=>Object.fromEntries(Object.entries(cost).map(([k,v])=>[k,Math.round(v*(1+Math.max(0,level-1)*.55))]));

  class FactionCampaignEngine{
    ensure(state={},artifacts=[],roster=[]){
      const needsBaseMigration=Number(state.v21?.schemaVersion||0)<V21_SCHEMA_VERSION;
      if(needsBaseMigration&&root.MultiverseDomain?.migrateV20)root.MultiverseDomain.migrateV20(state,artifacts,roster);
      state.v21||={};const v=state.v21;
      v.schemaVersion=V21_SCHEMA_VERSION;state.v21Version=V21_SCHEMA_VERSION;state.schemaVersion=Math.max(Number(state.schemaVersion||0),V21_SCHEMA_VERSION);
      v.memberships=v.memberships&&typeof v.memberships==='object'?v.memberships:{};
      v.primaryFactionId=String(v.primaryFactionId||'');
      v.campaigns=v.campaigns&&typeof v.campaigns==='object'?v.campaigns:{};
      v.campaignHistory=Array.isArray(v.campaignHistory)?v.campaignHistory.slice(-80):[];
      v.territories=v.territories&&typeof v.territories==='object'?v.territories:{};
      v.fronts=v.fronts&&typeof v.fronts==='object'?v.fronts:{};
      v.strongholds=v.strongholds&&typeof v.strongholds==='object'?v.strongholds:{};
      v.facilities=v.facilities&&typeof v.facilities==='object'?v.facilities:{};
      v.specialists=v.specialists&&typeof v.specialists==='object'?v.specialists:{};
      v.assignments=v.assignments&&typeof v.assignments==='object'?v.assignments:{};
      v.diplomacy=v.diplomacy&&typeof v.diplomacy==='object'?v.diplomacy:{};
      v.infiltration=v.infiltration&&typeof v.infiltration==='object'?v.infiltration:{};
      v.factionUnlocks=v.factionUnlocks&&typeof v.factionUnlocks==='object'?v.factionUnlocks:{};
      v.factionCrafting=v.factionCrafting&&typeof v.factionCrafting==='object'?v.factionCrafting:{};
      v.processedEvents=Array.isArray(v.processedEvents)?v.processedEvents.slice(-240):[];
      v.settings={autoAssignDefense:true,campaignHints:true,...(v.settings||{})};
      v.stats={factionsJoined:0,promotions:0,campaignsWon:0,campaignsLost:0,territoriesCaptured:0,territoriesLost:0,siegesWon:0,siegesLost:0,strongholdsBuilt:0,facilitiesBuilt:0,defections:0,infiltrations:0,alliancesBrokered:0,betrayals:0,...(v.stats||{})};
      v.ending=v.ending||null;
      for(const faction of factionList(state))if(v.memberships[faction.id])this.membership(state,faction.id);
      this.ensureTerritories(state);this.ensureFronts(state);this.syncDefectors(state);this.syncNemeses(state);return state;
    }

    membership(state,factionId){
      const faction=state.v16?.factions?.[String(factionId||'')];if(!faction)return null;
      const rec=state.v21.memberships[faction.id]||{};
      Object.assign(rec,{factionId:faction.id,status:String(rec.status||'neutral'),rank:clamp(rec.rank||1,1,8),rankXp:Math.max(0,Number(rec.rankXp||0)),authority:clamp(rec.authority||0,0,100),joinedTick:Number(rec.joinedTick||0),leftTick:Number(rec.leftTick||0),loyalty:clamp(rec.loyalty??50,0,100),cover:clamp(rec.cover??0,0,100),suspicion:clamp(rec.suspicion??0,0,100),declaredEnemy:Boolean(rec.declaredEnemy),history:Array.isArray(rec.history)?rec.history.slice(-60):[]});
      state.v21.memberships[faction.id]=rec;return rec;
    }
    history(state,rec,type,detail){rec.history.push({tick:tick(state),spin:Number(state.spin||0),type,detail:String(detail||'').slice(0,260)});rec.history=rec.history.slice(-60);}
    primaryMembership(state){return state.v21.primaryFactionId?this.membership(state,state.v21.primaryFactionId):null;}
    joinFaction(state,factionId,roster=[]){
      this.ensure(state,[],roster);const faction=state.v16.factions[String(factionId||'')];if(!faction)return{ok:false,error:'Unknown faction.'};const current=this.primaryMembership(state);if(current&&['member','allied'].includes(current.status)&&current.factionId!==faction.id)return{ok:false,error:'Leave or defect from your current primary faction first.'};if(Number(faction.reputation||0)<-10)return{ok:false,error:'This faction does not trust you enough to join.'};const rec=this.membership(state,faction.id),first=rec.status!=='member';rec.status='member';rec.declaredEnemy=false;rec.joinedTick=rec.joinedTick||tick(state);rec.leftTick=0;rec.loyalty=clamp(rec.loyalty+8,0,100);state.v21.primaryFactionId=faction.id;if(first)state.v21.stats.factionsJoined++;this.adjustAuthority(state,faction.id,4,'Joined the faction');this.addRankXp(state,faction.id,8,'Enlistment');this.history(state,rec,'join',`Joined ${faction.name}.`);this.partyReaction(state,faction.id,'join',roster);this.remember(state,'faction',`Joined ${faction.name}`,'A long-form faction allegiance began.',faction.id);return{ok:true,membership:clone(rec)};
    }
    leaveFaction(state,factionId=state.v21.primaryFactionId,roster=[]){
      this.ensure(state,[],roster);const rec=this.membership(state,factionId);if(!rec||!['member','allied'].includes(rec.status))return{ok:false,error:'You are not a member of that faction.'};rec.status='allied';rec.leftTick=tick(state);rec.loyalty=clamp(rec.loyalty-12,0,100);this.adjustAuthority(state,factionId,-12,'Left active service');if(state.v21.primaryFactionId===factionId)state.v21.primaryFactionId='';this.history(state,rec,'leave','Left active faction service without declaring war.');this.partyReaction(state,factionId,'leave',roster);return{ok:true,membership:clone(rec)};
    }
    defectFaction(state,fromId,toId,roster=[]){
      this.ensure(state,[],roster);const from=this.membership(state,fromId),to=state.v16.factions[String(toId||'')];if(!from||from.status!=='member')return{ok:false,error:'You can only defect from your active faction.'};if(!to||to.id===fromId)return{ok:false,error:'Choose a different valid faction.'};from.status='defected';from.leftTick=tick(state);from.declaredEnemy=true;from.loyalty=0;this.history(state,from,'defect',`Defected to ${to.name}.`);this.changeRelation(state,fromId,toId,-18);this.adjustFactionReputation(state,fromId,-35,'Faction defection');this.adjustFactionReputation(state,toId,12,'Accepted defector');state.v21.primaryFactionId='';state.v21.stats.defections++;state.v21.stats.betrayals++;const joined=this.joinFaction(state,toId,roster);if(joined.ok)this.adjustAuthority(state,toId,5,'High-risk defection');this.partyReaction(state,fromId,'betray',roster);this.remember(state,'faction',`Defected from ${state.v16.factions[fromId]?.name||fromId}`,`Joined ${to.name}; old loyalties became active political consequences.`,fromId);return{ok:joined.ok,from:clone(from),to:joined.membership};
    }
    beginInfiltration(state,factionId){
      this.ensure(state);const faction=state.v16.factions[String(factionId||'')];if(!faction)return{ok:false,error:'Unknown faction.'};if(state.v21.primaryFactionId===faction.id)return{ok:false,error:'You cannot infiltrate your own primary faction.'};const rec=this.membership(state,faction.id);rec.status='infiltrating';rec.cover=Math.max(rec.cover,55);rec.suspicion=Math.min(rec.suspicion,25);const old=state.v21.infiltration[faction.id]||{};state.v21.infiltration[faction.id]={factionId:faction.id,cover:clamp(old.cover??rec.cover,0,100),suspicion:clamp(old.suspicion??rec.suspicion,0,100),intel:clamp(old.intel??0,0,100),discovered:Boolean(old.discovered),missionsCompleted:Number(old.missionsCompleted||0)};state.v21.stats.infiltrations++;this.history(state,rec,'infiltration','Established a covert identity.');return{ok:true,infiltration:clone(state.v21.infiltration[faction.id])};
    }

    rankProgress(state,factionId){const rec=this.membership(state,factionId),faction=state.v16?.factions?.[factionId];if(!rec||!faction)return null;const next=RANKS[Math.min(7,rec.rank)]||null;return{rank:clone(RANKS[rec.rank-1]),next:clone(next),xp:rec.rankXp,reputation:Number(faction.reputation||0),authority:rec.authority,eligible:next?rec.rankXp>=next.xp&&Number(faction.reputation||0)>=next.rep&&rec.authority>=next.authority:false};}
    addRankXp(state,factionId,amount,reason='Contribution'){const rec=this.membership(state,factionId);if(!rec)return null;rec.rankXp=Math.max(0,rec.rankXp+Math.max(0,Number(amount||0)));this.history(state,rec,'rank-xp',`${reason}: +${Math.max(0,Number(amount||0))} XP.`);let promoted=false,steps=0;while(steps<RANKS.length-1){const result=this.promote(state,factionId);if(!result.ok)break;promoted=true;steps++;}return{membership:clone(rec),promoted};}
    promote(state,factionId){const rec=this.membership(state,factionId),progress=this.rankProgress(state,factionId);if(!rec||rec.rank>=8||!progress?.eligible)return{ok:false};rec.rank++;state.v21.stats.promotions++;this.adjustAuthority(state,factionId,4+rec.rank,'Promotion');this.history(state,rec,'promotion',`Promoted to ${RANKS[rec.rank-1].label}.`);state.v21.factionUnlocks[factionId]=this.factionGearUnlocks(state,factionId);return{ok:true,rank:clone(RANKS[rec.rank-1])};}
    authority(state,factionId){return this.membership(state,factionId)?.authority||0;}
    adjustAuthority(state,factionId,delta,reason='Authority changed'){const rec=this.membership(state,factionId);if(!rec)return 0;const before=rec.authority;rec.authority=clamp(before+Number(delta||0),0,100);if(rec.authority!==before)this.history(state,rec,'authority',`${reason}: ${before} → ${rec.authority}.`);return rec.authority;}

    ensureTerritories(state){
      const factions=factionList(state),fallback=factions[0]?.id||'',worlds=Object.values(state.v16?.universes||{}),routeTable=state.v17?.routes||{};
      for(const world of worlds){
        const routeKey=String(world.id||normalize(world.name));
        let routes=Array.isArray(routeTable[routeKey])?routeTable[routeKey]:[];
        if(!routes.length){
          const match=Object.values(routeTable).find(list=>Array.isArray(list)&&list.some(route=>String(route.universe||'')===String(world.name||'')));
          if(match)routes=match;
        }
        routes=routes.filter(route=>!route.secret||route.discovered||route.unlocked);
        if(!routes.length)routes=[{id:'crossroads',label:'Crossroads',routeId:`${world.id}:crossroads`,universe:world.name}];
        for(const route of routes){const id=String(route.routeId||`${world.id}:${route.id}`),old=state.v21.territories[id];if(old)continue;const rng=rngFrom(`${state.seed}|v21|territory|${id}`),controller=factions.length&&rng()>.34?factions[Math.floor(rng()*factions.length)%factions.length].id:null;state.v21.territories[id]={id,universe:String(route.universe||world.name),locationId:String(route.id||'crossroads'),type:TERRITORY_TYPES.includes(route.id)?route.id:'fracture-zone',controllerFactionId:controller||fallback||null,influence:Object.fromEntries(factions.map(f=>[f.id,clamp(Math.round((f.id===controller?58:12)+rng()*18),0,100)])),stability:clamp(Number(world.stability||75)+Math.round(rng()*10-5),0,100),fortification:Math.round(12+rng()*35),supply:Math.round(45+rng()*40),contested:Boolean(rng()>.72),campaignId:'',history:[]};}
      }
      return state.v21.territories;
    }
    territory(state,id){return state.v21.territories[String(id||'')]||null;}
    captureTerritory(state,territoryId,factionId){
      this.ensure(state);const territory=this.territory(state,territoryId),winner=state.v16.factions[String(factionId||'')];if(!territory||!winner)return{ok:false,error:'Invalid territory or faction.'};const previous=territory.controllerFactionId;if(previous===winner.id)return{ok:false,error:'That faction already controls this territory.'};territory.controllerFactionId=winner.id;territory.contested=false;territory.influence[winner.id]=clamp(Math.max(55,Number(territory.influence[winner.id]||0)+20),0,100);territory.fortification=clamp(territory.fortification-8,0,100);territory.history.push({tick:tick(state),from:previous,to:winner.id});territory.history=territory.history.slice(-30);winner.power=clamp(Number(winner.power||0)+3,1,100);winner.resources=clamp(Number(winner.resources||0)+2,0,100);if(previous&&state.v16.factions[previous]){state.v16.factions[previous].power=clamp(Number(state.v16.factions[previous].power||0)-3,1,100);state.v16.factions[previous].resources=clamp(Number(state.v16.factions[previous].resources||0)-2,0,100);}const player=state.v21.primaryFactionId;if(winner.id===player)state.v21.stats.territoriesCaptured++;else if(previous===player)state.v21.stats.territoriesLost++;this.remember(state,'faction',`${winner.name} captured ${territory.locationId}`,`${territory.universe} changed strategic control.`,winner.id);return{ok:true,territory:clone(territory),previous};
    }

    ensureFronts(state){
      const factions=factionList(state),territories=Object.values(state.v21.territories);for(let i=0;i<factions.length;i++)for(let j=i+1;j<factions.length;j++){const a=factions[i],b=factions[j],relation=Number(a.relations?.[b.id]||0);if(relation>-35)continue;const id=[a.id,b.id].sort().join('::'),old=state.v21.fronts[id];if(old)continue;const options=territories.filter(t=>[a.id,b.id].includes(t.controllerFactionId)),territory=options[hash32(`${state.seed}|front|${id}`)%Math.max(1,options.length)]||territories[0];state.v21.fronts[id]={id,universe:territory?.universe||worldName(state),territoryId:territory?.id||'',attackerId:a.power>=b.power?a.id:b.id,defenderId:a.power>=b.power?b.id:a.id,pressure:50,supply:60,morale:60,status:'active',objective:'Break the opposing supply line',lastResolvedTick:tick(state)};}
      return state.v21.fronts;
    }
    advanceFronts(state){
      this.ensure(state);const currentTick=tick(state),results=[];for(const front of Object.values(state.v21.fronts)){if(front.status!=='active'||front.lastResolvedTick>=currentTick)continue;const a=state.v16.factions[front.attackerId],d=state.v16.factions[front.defenderId];if(!a||!d)continue;const rng=rngFrom(`${state.seed}|v21|front|${front.id}|${currentTick}`),adv=((Number(a.resources||0)-Number(d.resources||0))/100)*4+(rng()-.5)*5;front.pressure=clamp(front.pressure+adv,10,90);front.supply=clamp(front.supply+(rng()-.48)*4,15,100);front.morale=clamp(front.morale+(rng()-.5)*3,20,100);front.lastResolvedTick=currentTick;const territory=this.territory(state,front.territoryId);if(territory){territory.contested=true;territory.supply=clamp(territory.supply+(front.pressure>65?-2:front.pressure<35?2:0),10,100);}results.push(clone(front));}return results;
    }

    createCampaign(state,factionId,type=''){this.ensure(state);const faction=state.v16.factions[String(factionId||'')];if(!faction)return{ok:false,error:'Unknown faction.'};const types=Object.keys(CAMPAIGN_DEFS),kind=CAMPAIGN_DEFS[type]?type:types[hash32(`${state.seed}|v21|campaign|${faction.id}|${tick(state)}|${Object.keys(state.v21.campaigns).length}`)%types.length],def=CAMPAIGN_DEFS[kind],index=Object.keys(state.v21.campaigns).length,id=`camp-${hash32(`${state.seed}|${faction.id}|${kind}|${index}`).toString(36)}`,enemies=factionList(state).filter(f=>f.id!==faction.id).sort((a,b)=>Number(faction.relations?.[a.id]||0)-Number(faction.relations?.[b.id]||0)),enemy=enemies[0],territories=Object.values(state.v21.territories).filter(t=>t.universe===worldName(state)),target=territories[hash32(`${id}|territory`)%Math.max(1,territories.length)]||Object.values(state.v21.territories)[0],objectives=def.operations.map((events,i)=>({id:`${id}-op${i+1}`,label:`Operation ${i+1}`,events:events.slice(),target:def.targets[i],progress:0,status:i===0?'active':'locked',requiredOutcome:events.some(e=>['battle','boss'].includes(e))?'win':''}));const campaign=state.v21.campaigns[id]={id,factionId:faction.id,type:kind,label:def.label,summary:def.summary,universe:target?.universe||worldName(state),territoryId:target?.id||'',status:'active',phase:'operations',phaseIndex:0,objective:objectives[0].id,objectives,choices:def.choices.slice(),progress:0,target:objectives.reduce((s,o)=>s+o.target,0),enemyFactionIds:enemy?[enemy.id]:[],rewards:{rankXp:55,authority:10,credits:180,resources:6},consequences:{},momentum:0,startedTick:tick(state),lastTick:tick(state)};if(target)target.campaignId=id;this.remember(state,'faction',`${faction.name}: ${def.label}`,def.summary,faction.id);return{ok:true,campaign};}
    campaign(state,id){return state.v21.campaigns[String(id||'')]||null;}
    activeCampaign(state,factionId=state.v21.primaryFactionId){return Object.values(state.v21.campaigns).find(c=>c.status==='active'&&(!factionId||c.factionId===factionId))||null;}
    progressCampaign(state,context={}){
      this.ensure(state);const results=[];for(const campaign of Object.values(state.v21.campaigns)){if(campaign.status!=='active'||campaign.phase!=='operations')continue;const objective=campaign.objectives[campaign.phaseIndex];if(!objective||objective.status!=='active'||!objective.events.includes(String(context.type||'')))continue;if(objective.requiredOutcome&&context.outcome!==objective.requiredOutcome)continue;if(context.factionId&&context.factionId!==campaign.factionId&&!context.allowCrossFaction)continue;objective.progress=clamp(objective.progress+Math.max(1,Number(context.amount||1)),0,objective.target);campaign.progress=campaign.objectives.reduce((s,o)=>s+o.progress,0);campaign.momentum=clamp(campaign.momentum+(context.outcome==='loss'?-8:6),-40,40);campaign.lastTick=tick(state);let completed=false;if(objective.progress>=objective.target){objective.status='completed';this.addRankXp(state,campaign.factionId,10+objective.target*3,`Campaign: ${campaign.label}`);this.adjustAuthority(state,campaign.factionId,2,'Campaign operation completed');if(campaign.phaseIndex<campaign.objectives.length-1){campaign.phaseIndex++;campaign.objectives[campaign.phaseIndex].status='active';campaign.objective=campaign.objectives[campaign.phaseIndex].id;}else{campaign.phase='decision';campaign.objective='strategic-decision';completed=true;}}results.push({campaignId:campaign.id,objective:clone(objective),operationComplete:completed});}return results;
    }
    resolveCampaignChoice(state,campaignId,choice,roster=[]){
      this.ensure(state,[],roster);const c=this.campaign(state,campaignId);if(!c||c.status!=='active')return{ok:false,error:'Campaign is not active.'};if(c.phase!=='decision')return{ok:false,error:'Complete the current operations first.'};if(!c.choices.includes(choice))return{ok:false,error:'Invalid campaign decision.'};const faction=state.v16.factions[c.factionId],enemy=state.v16.factions[c.enemyFactionIds[0]],success=c.momentum>=-15;let captured=false;if(success&&c.territoryId){const cap=this.captureTerritory(state,c.territoryId,c.factionId);captured=cap.ok;}if(choice.includes('diplomacy')||choice==='reconcile'){if(enemy)this.changeRelation(state,faction.id,enemy.id,18);state.v21.stats.alliancesBrokered++;}if(choice==='break-away'||choice==='independent-cell')this.adjustAuthority(state,c.factionId,8,'Independent campaign settlement');if(choice==='destroy-relic')this.adjustFactionReputation(state,c.factionId,-4,'Destroyed a disputed relic');if(success){c.status='won';state.v21.stats.campaignsWon++;this.addRankXp(state,c.factionId,c.rewards.rankXp,'Campaign victory');this.adjustAuthority(state,c.factionId,c.rewards.authority,'Campaign victory');this.addCurrency(state,'credits',c.rewards.credits);faction.resources=clamp(Number(faction.resources||0)+c.rewards.resources,0,100);}else{c.status='lost';state.v21.stats.campaignsLost++;this.adjustAuthority(state,c.factionId,-5,'Campaign defeat');faction.resources=clamp(Number(faction.resources||0)-4,0,100);}c.phase='aftermath';c.choice=choice;c.completedTick=tick(state);c.consequences={captured,success,choice};state.v21.campaignHistory.push(clone(c));state.v21.campaignHistory=state.v21.campaignHistory.slice(-80);if(c.territoryId&&state.v21.territories[c.territoryId]?.campaignId===c.id)state.v21.territories[c.territoryId].campaignId='';this.partyReaction(state,c.factionId,success?'campaign-win':'campaign-loss',roster);this.remember(state,'faction',`${faction.name} ${success?'won':'lost'} ${c.label}`,`${choice} shaped the aftermath.`,faction.id);return{ok:true,campaign:clone(c)};
    }

    stronghold(state,id){return state.v21.strongholds[String(id||'')]||null;}
    buildStronghold(state,options={}){
      this.ensure(state);const factionId=String(options.factionId||state.v21.primaryFactionId),faction=state.v16.factions[factionId],territory=this.territory(state,options.territoryId);if(!faction)return{ok:false,error:'A valid allied faction is required.'};if(!territory)return{ok:false,error:'Choose a valid territory.'};if(territory.controllerFactionId&&territory.controllerFactionId!==factionId)return{ok:false,error:'Hostile control must be resolved before construction.'};if(Object.values(state.v21.strongholds).some(s=>s.territoryId===territory.id&&s.status!=='destroyed'))return{ok:false,error:'This territory already has a stronghold.'};const rec=this.membership(state,factionId);if(!rec||rec.rank<3||rec.authority<10)return{ok:false,error:'Operative rank and 10 Authority are required.'};const cost={credits:450,salvage:42,cosmicFragments:6,...(options.type==='relic-vault'?{bountySeals:1}:{})};if(!this.pay(state,cost))return{ok:false,error:'Insufficient V18 construction resources.'};const id=`hold-${hash32(`${state.seed}|${territory.id}|${factionId}|${Object.keys(state.v21.strongholds).length}`).toString(36)}`,type=String(options.type||'player-outpost'),stronghold=state.v21.strongholds[id]={id,name:String(options.name||`${faction.name} ${type==='player-outpost'?'Outpost':'Stronghold'}`).slice(0,72),type,universe:territory.universe,locationId:territory.locationId,territoryId:territory.id,ownerFactionId:factionId,playerAligned:true,level:1,integrity:100,defense:30,supply:65,morale:70,facilities:[],specialists:[],underSiege:false,status:'safe',history:[{tick:tick(state),type:'built'}]};territory.controllerFactionId=factionId;territory.fortification=clamp(territory.fortification+12,0,100);state.v21.stats.strongholdsBuilt++;this.adjustAuthority(state,factionId,3,'Stronghold established');this.remember(state,'faction',`${stronghold.name} established`,`${territory.locationId} now has a recoverable player-aligned base.`,factionId);return{ok:true,stronghold:clone(stronghold),cost};
    }
    upgradeStronghold(state,id){const s=this.stronghold(state,id);if(!s)return{ok:false,error:'Stronghold not found.'};if(s.level>=5)return{ok:false,error:'Stronghold is already at maximum level.'};const cost=costScale({credits:240,salvage:28,cosmicFragments:3},s.level);if(!this.pay(state,cost))return{ok:false,error:'Insufficient upgrade resources.'};s.level++;s.defense=clamp(s.defense+8,0,100);s.supply=clamp(s.supply+8,0,100);s.integrity=clamp(s.integrity+15,0,100);s.history.push({tick:tick(state),type:'upgrade',level:s.level});return{ok:true,stronghold:clone(s),cost};}
    repairStronghold(state,id){const s=this.stronghold(state,id);if(!s)return{ok:false,error:'Stronghold not found.'};if(s.integrity>=100)return{ok:false,error:'Stronghold integrity is already full.'};const missing=100-s.integrity,cost={credits:Math.max(30,Math.round(missing*2)),salvage:Math.max(4,Math.ceil(missing/5))};if(!this.pay(state,cost))return{ok:false,error:'Insufficient repair resources.'};s.integrity=clamp(s.integrity+Math.max(20,Math.round(missing*.65)),0,100);if(s.integrity>25){s.status='safe';s.underSiege=false;}return{ok:true,stronghold:clone(s),cost};}
    buildFacility(state,strongholdId,facilityType){
      const s=this.stronghold(state,strongholdId),def=FACILITY_DEFS[facilityType];if(!s||!def)return{ok:false,error:'Invalid stronghold or facility.'};const key=`${s.id}:${facilityType}`,existing=state.v21.facilities[key];if(existing)return this.upgradeFacility(state,strongholdId,facilityType);const cost=costScale(def.cost,1);if(!this.pay(state,cost))return{ok:false,error:'Insufficient V18 facility resources.'};const facility=state.v21.facilities[key]={id:key,strongholdId:s.id,type:facilityType,label:def.label,level:1,maxLevel:def.max,bonus:def.bonus};if(!s.facilities.includes(key))s.facilities.push(key);state.v21.stats.facilitiesBuilt++;return{ok:true,facility:clone(facility),cost};
    }
    upgradeFacility(state,strongholdId,facilityType){const s=this.stronghold(state,strongholdId),def=FACILITY_DEFS[facilityType],key=`${strongholdId}:${facilityType}`,f=state.v21.facilities[key];if(!s||!def||!f)return{ok:false,error:'Build that facility first.'};if(f.level>=def.max)return{ok:false,error:'Facility is at maximum level.'};const cost=costScale(def.cost,f.level+1);if(!this.pay(state,cost))return{ok:false,error:'Insufficient V18 facility resources.'};f.level++;return{ok:true,facility:clone(f),cost};}
    facilityLevel(state,strongholdId,type){return Number(state.v21.facilities[`${strongholdId}:${type}`]?.level||0);}

    assignSpecialist(state,strongholdId,characterId,role){
      this.ensure(state);const s=this.stronghold(state,strongholdId),r=state.v19?.records?.[String(characterId||'')];if(!s)return{ok:false,error:'Stronghold not found.'};if(!r||['dead','departed','defected'].includes(r.status))return{ok:false,error:'That ally cannot be assigned.'};if(!SPECIALIST_ROLES.includes(role))return{ok:false,error:'Unknown specialist role.'};if(state.v21.assignments[characterId])this.unassignSpecialist(state,characterId);const assignment={characterId:String(characterId),strongholdId:s.id,role,assignedTick:tick(state)};state.v21.assignments[characterId]=assignment;state.v21.specialists[characterId]={characterId:String(characterId),role,strongholdId:s.id,source:'party'};if(!s.specialists.includes(String(characterId)))s.specialists.push(String(characterId));try{new root.MultiverseDomain.PartyConsequencesEngine().adjust(state,String(characterId),{respect:2,trust:1},`Assigned as ${role}`);}catch{}return{ok:true,assignment:clone(assignment)};
    }
    unassignSpecialist(state,characterId){const a=state.v21.assignments[String(characterId||'')];if(!a)return{ok:false,error:'No active assignment.'};const s=this.stronghold(state,a.strongholdId);if(s)s.specialists=s.specialists.filter(id=>id!==String(characterId));delete state.v21.assignments[String(characterId)];delete state.v21.specialists[String(characterId)];return{ok:true};}

    diplomacyOptions(state,factionId){
      this.ensure(state);const primary=state.v21.primaryFactionId,target=state.v16.factions[String(factionId||'')],ours=state.v16.factions[primary],rec=primary?this.membership(state,primary):null;if(!target||!ours||target.id===ours.id)return[];const relation=Number(ours.relations?.[target.id]||0),authority=rec?.authority||0,embassy=Math.max(0,...Object.values(state.v21.strongholds).filter(s=>s.playerAligned).map(s=>this.facilityLevel(state,s.id,'embassy')));return[
        {id:'alliance',label:'Propose Alliance',available:relation>=25&&authority>=35+Math.max(0,10-embassy*3),reason:'Requires warm relations and high Authority.'},
        {id:'ceasefire',label:'Propose Ceasefire',available:relation<=-20&&authority>=20,reason:'Requires a hostile relationship and 20 Authority.'},
        {id:'trade',label:'Trade Resources',available:relation>=-10&&Number(state.credits||0)>=120,reason:'Requires neutral relations and 120 Credits.'},
        {id:'threaten',label:'Threaten',available:authority>=30,reason:'Requires 30 Authority.'},
        {id:'betray',label:'Betray Agreement',available:relation>=35,reason:'Requires an existing cooperative relationship.'}
      ];
    }
    proposeTreaty(state,factionId,action){
      const primary=state.v21.primaryFactionId,ours=state.v16.factions[primary],target=state.v16.factions[String(factionId||'')];if(!ours||!target)return{ok:false,error:'A primary faction and valid target are required.'};const option=this.diplomacyOptions(state,factionId).find(o=>o.id===action);if(!option?.available)return{ok:false,error:option?.reason||'That proposal is unavailable.'};let delta=0;if(action==='alliance'){delta=30;state.v21.stats.alliancesBrokered++;this.adjustAuthority(state,primary,4,'Brokered an alliance');}else if(action==='ceasefire'){delta=22;state.v21.stats.alliancesBrokered++;}else if(action==='trade'){if(!this.pay(state,{credits:120}))return{ok:false,error:'Not enough Credits.'};delta=8;ours.resources=clamp(Number(ours.resources||0)+5,0,100);target.resources=clamp(Number(target.resources||0)+5,0,100);}else if(action==='threaten'){delta=-15;this.adjustAuthority(state,primary,2,'Coercive diplomacy');}else if(action==='betray'){delta=-55;state.v21.stats.betrayals++;this.adjustFactionReputation(state,primary,-8,'Betrayed an agreement');}this.changeRelation(state,primary,target.id,delta);state.v21.diplomacy[[primary,target.id].sort().join('::')]={factions:[primary,target.id],lastAction:action,lastTick:tick(state),relation:Number(ours.relations[target.id]||0)};this.remember(state,'faction',`${ours.name}: ${action}`,`${target.name} relations changed ${delta>=0?'+':''}${delta}.`,primary);return{ok:true,relation:Number(ours.relations[target.id]||0),action};
    }
    changeRelation(state,aId,bId,delta){const a=state.v16?.factions?.[aId],b=state.v16?.factions?.[bId];if(!a||!b||a.id===b.id)return null;const next=clamp(Number(a.relations?.[b.id]||0)+Number(delta||0),-100,100);a.relations=a.relations||{};b.relations=b.relations||{};a.relations[b.id]=next;b.relations[a.id]=next;return next;}
    adjustFactionReputation(state,factionId,delta,reason){try{return new root.MultiverseDomain.LivingMultiverseEngine().factionReputation(state,factionId,delta,reason);}catch{const f=state.v16?.factions?.[factionId];if(f)f.reputation=clamp(Number(f.reputation||0)+Number(delta||0),-100,100);return f;}}

    infiltrationOptions(state,factionId){const inf=state.v21.infiltration[String(factionId||'')];if(!inf||inf.discovered)return[];return['reconnaissance','sabotage','steal-plans','free-prisoners','manipulate-leadership','open-gates'].map((id,i)=>({id,risk:20+i*7,available:inf.cover>15&&inf.suspicion<90}));}
    resolveInfiltration(state,action,factionId=''){
      this.ensure(state);const id=String(factionId||Object.keys(state.v21.infiltration).find(k=>!state.v21.infiltration[k].discovered)||''),inf=state.v21.infiltration[id],option=this.infiltrationOptions(state,id).find(o=>o.id===action);if(!inf||!option?.available)return{ok:false,error:'No valid covert operation is available.'};const intelWing=Math.max(0,...Object.values(state.v21.strongholds).filter(s=>s.playerAligned).map(s=>this.facilityLevel(state,s.id,'intelligence'))),skill=Number(state.customCharacter?.stats?.skill||state.stats?.skill||50),score=inf.cover*.45+inf.intel*.22+skill*.18+intelWing*6-inf.suspicion*.3,roll=rngFrom(`${state.seed}|v21|infiltration|${id}|${action}|${inf.missionsCompleted}`)()*100,success=score+25>=roll+option.risk*.35;inf.missionsCompleted++;if(success){inf.intel=clamp(inf.intel+12+option.risk*.15,0,100);inf.cover=clamp(inf.cover-3,0,100);inf.suspicion=clamp(inf.suspicion+4,0,100);if(action==='sabotage'){const f=state.v16.factions[id];if(f)f.resources=clamp(Number(f.resources||0)-5,0,100);}if(action==='open-gates'){for(const s of Object.values(state.v21.strongholds).filter(x=>x.ownerFactionId===id))s.defense=clamp(s.defense-8,0,100);}this.addRankXp(state,state.v21.primaryFactionId,6,'Covert operation');}else{inf.cover=clamp(inf.cover-18,0,100);inf.suspicion=clamp(inf.suspicion+22,0,100);if(inf.suspicion>=90||inf.cover<=10){inf.discovered=true;const rec=this.membership(state,id);rec.status='enemy';rec.declaredEnemy=true;this.adjustFactionReputation(state,id,-25,'Infiltration exposed');this.createExposureNemesis(state,id);}}const rec=this.membership(state,id);if(rec){rec.cover=inf.cover;rec.suspicion=inf.suspicion;}return{ok:true,success,infiltration:clone(inf)};
    }

    beginSiege(state,strongholdId,attackerId){const s=this.stronghold(state,strongholdId),attacker=state.v16?.factions?.[String(attackerId||'')];if(!s||!attacker||attacker.id===s.ownerFactionId)return{ok:false,error:'Invalid siege.'};s.underSiege=true;s.status='under-siege';s.siege={attackerId:attacker.id,stage:0,stages:['preparation','approach','breach','champion','decision'],progress:0,startedTick:tick(state),history:[]};s.history.push({tick:tick(state),type:'siege-start',attackerId:attacker.id});return{ok:true,stronghold:clone(s)};}
    resolveSiegeStep(state,strongholdId,choice='direct-assault'){
      const s=this.stronghold(state,strongholdId);if(!s?.underSiege||!s.siege)return{ok:false,error:'Stronghold is not under siege.'};const valid=['direct-assault','stealth','sabotage','diplomacy','relic-breach','evacuate','surrender','scorched-retreat'];if(!valid.includes(choice))return{ok:false,error:'Unknown siege choice.'};const defense=this.strongholdDefenseModifier(state,strongholdId),attacker=state.v16.factions[s.siege.attackerId],rng=rngFrom(`${state.seed}|v21|siege|${s.id}|${s.siege.stage}|${choice}`),choiceBonus={stealth:5,sabotage:7,diplomacy:3,'relic-breach':8,evacuate:-4,surrender:-12,'scorched-retreat':-8,'direct-assault':4}[choice]||0,score=50+defense.odds*100+choiceBonus+(Number(s.supply||0)-50)*.12-(Number(attacker?.power||50)-50)*.2,won=score>=35+rng()*40;s.siege.history.push({stage:s.siege.stage,choice,won});if(won){s.siege.progress++;s.integrity=clamp(s.integrity-2,0,100);s.morale=clamp(s.morale+3,0,100);}else{s.integrity=clamp(s.integrity-(7+Math.round(rng()*7)),0,100);s.supply=clamp(s.supply-6,0,100);s.morale=clamp(s.morale-8,0,100);}s.siege.stage++;if(s.siege.stage>=s.siege.stages.length||s.integrity<=0||choice==='surrender'){const victory=s.siege.progress>=3&&s.integrity>0&&choice!=='surrender';s.underSiege=false;if(victory){s.status=s.integrity<45?'damaged':'safe';state.v21.stats.siegesWon++;this.addRankXp(state,s.ownerFactionId,25,'Stronghold defense');this.adjustAuthority(state,s.ownerFactionId,6,'Stronghold defended');}else{s.status='occupied';s.integrity=Math.max(1,s.integrity);state.v21.stats.siegesLost++;const t=this.territory(state,s.territoryId);if(t)t.controllerFactionId=attacker?.id||t.controllerFactionId;}return{ok:true,finished:true,victory,stronghold:clone(s)};}return{ok:true,finished:false,won,stronghold:clone(s)};
    }

    campaignCombatModifier(state){const c=this.activeCampaign(state),primary=this.primaryMembership(state);if(!c||!primary)return{odds:0,damage:0};const strongholds=Object.values(state.v21.strongholds).filter(s=>s.playerAligned&&s.status!=='occupied'),supply=strongholds.length?strongholds.reduce((n,s)=>n+Number(s.supply||0),0)/strongholds.length:50,odds=clamp(c.momentum*.0007+(supply-50)*.00025+primary.authority*.00008,-.06,.06),damage=clamp(c.momentum*.001+(supply-50)*.0005,-.08,.08);return{odds,damage};}
    strongholdDefenseModifier(state,strongholdId=''){const s=strongholdId?this.stronghold(state,strongholdId):Object.values(state.v21.strongholds).find(x=>x.playerAligned&&x.underSiege);if(!s)return{odds:0,damage:0};const grid=this.facilityLevel(state,s.id,'defense'),command=this.facilityLevel(state,s.id,'command'),specialist=s.specialists.some(id=>state.v21.specialists[id]?.role==='defense-commander')?1:0;return{odds:clamp((Number(s.defense||0)-50)*.00045+grid*.012+command*.004+specialist*.008,-.06,.06),damage:clamp(grid*.018+specialist*.012,0,.08)};}
    factionGearUnlocks(state,factionId){const rec=this.membership(state,factionId),f=state.v16?.factions?.[factionId];if(!rec||!f)return{regalia:false,setId:'',signature:false,technique:''};return{regalia:rec.rank>=4&&Number(f.reputation||0)>=35,setId:`faction:${factionId}`,signature:rec.rank>=6,technique:rec.rank>=5?(TECHNIQUES[f.archetype]||'Faction Technique'):''};}
    factionRelicObjectives(state,factionId){const f=state.v16?.factions?.[factionId];if(!f)return[];const ids=Object.keys(state.v20?.relics||{});return ids.filter(id=>hash32(`${factionId}|${id}|v21-relic`)%3===0).map(id=>({artifactId:id,factionId,classification:['sacred','strategic','forbidden','disputed','stolen'][hash32(`${id}|${factionId}`)%5],relic:clone(state.v20.relics[id])}));}
    resolveRelicObjective(state,factionId,artifactId,choice){const r=state.v20?.relics?.[artifactId],f=state.v16?.factions?.[factionId];if(!r||!f)return{ok:false,error:'Relic objective is unavailable.'};const valid=['return','keep','attune','purify','corrupt','destroy','rival'];if(!valid.includes(choice))return{ok:false,error:'Invalid relic choice.'};if(choice==='return'){r.status='lost';state.artifacts=(state.artifacts||[]).filter(id=>id!==artifactId);state.v16.artifactOwners[artifactId]={artifactId,ownerType:'faction',ownerId:factionId,sinceTick:tick(state)};this.adjustFactionReputation(state,factionId,12,'Returned a faction relic');}else if(choice==='keep'){this.adjustFactionReputation(state,factionId,-10,'Kept a faction relic');r.bond=clamp(Number(r.bond||0)+8,0,100);}else if(choice==='attune'){r.bearerId='hero';r.bond=clamp(Number(r.bond||0)+10,0,100);}else if(choice==='purify'){r.purity=clamp(Number(r.purity||0)+20,0,100);r.corruption=clamp(Number(r.corruption||0)-20,0,100);}else if(choice==='corrupt'){r.corruption=clamp(Number(r.corruption||0)+20,0,100);r.purity=clamp(Number(r.purity||0)-15,0,100);}else if(choice==='destroy'){r.status='consumed';state.artifacts=(state.artifacts||[]).filter(id=>id!==artifactId);state.v16.artifactOwners[artifactId]={artifactId,ownerType:'destroyed',ownerId:'none',sinceTick:tick(state)};this.adjustFactionReputation(state,factionId,-8,'Destroyed a disputed relic');}else{const rival=factionList(state).filter(x=>x.id!==factionId)[hash32(`${artifactId}|rival`)%Math.max(1,factionList(state).length-1)];if(rival){state.v16.artifactOwners[artifactId]={artifactId,ownerType:'faction',ownerId:rival.id,sinceTick:tick(state)};this.changeRelation(state,factionId,rival.id,-18);}}return{ok:true,relic:clone(r)};}

    processWorldTick(state){
      this.ensure(state);const current=tick(state),key=`world:${current}`;if(state.v21.processedEvents.includes(key))return null;state.v21.processedEvents.push(key);this.advanceFronts(state);const changed=[];for(const s of Object.values(state.v21.strongholds)){if(!s.playerAligned)continue;const territory=this.territory(state,s.territoryId),hostile=territory?.controllerFactionId&&territory.controllerFactionId!==s.ownerFactionId;if(s.underSiege||hostile){const loss=Math.min(4,1+(hash32(`${state.seed}|hold|${s.id}|${current}`)%4));s.integrity=clamp(s.integrity-loss,1,100);s.supply=clamp(s.supply-2,5,100);s.status=s.integrity<30?'compromised':s.underSiege?'under-siege':'threatened';changed.push(s.id);}else{s.integrity=clamp(s.integrity+1+this.facilityLevel(state,s.id,'defense'),1,100);s.supply=clamp(s.supply+1+this.facilityLevel(state,s.id,'quartermaster'),5,100);if(s.integrity>=55)s.status='safe';}}
      for(const c of Object.values(state.v21.campaigns).filter(x=>x.status==='active')){c.lastTick=current;if(c.phase==='operations')c.momentum=clamp(c.momentum-1,-40,40);}this.syncNemeses(state);return{tick:current,strongholdsChanged:changed};
    }
    processEvent(state,context={},roster=[]){
      this.ensure(state,[],roster);const id=String(context.id||`${state.spin}:${context.type}:${context.outcome||'resolved'}:${context.enemyId||''}`),key=`event:${id}`;if(state.v21.processedEvents.includes(key))return null;state.v21.processedEvents.push(key);const factionId=String(context.factionId||state.v21.primaryFactionId||''),campaigns=this.progressCampaign(state,{...context,factionId});if(factionId&&campaigns.length){const win=context.outcome!=='loss';this.addRankXp(state,factionId,win?4:1,`Operation ${context.type}`);this.adjustAuthority(state,factionId,win?1:0,'Campaign contribution');}if(context.factionQuestCompleted&&context.questFactionId){this.addRankXp(state,context.questFactionId,8,'V17 faction quest');this.adjustAuthority(state,context.questFactionId,1,'V17 faction quest');}this.processWorldTick(state);return{campaigns,combat:this.campaignCombatModifier(state)};
    }

    partyReaction(state,factionId,action,roster=[]){
      if(!root.MultiverseDomain?.PartyConsequencesEngine||!state.v19)return[];const rel=new root.MultiverseDomain.PartyConsequencesEngine(),f=state.v16?.factions?.[factionId];if(!f)return[];const results=[];for(const id of [...(state.party||[]),...(state.v19.benchIds||[])]){const r=state.v19.records?.[id];if(!r||['dead','departed','defected'].includes(r.status))continue;const t=r.profile?.traits||{},rebellious=Number(t.rebellious||0),disciplined=Number(t.disciplined||0),compassionate=Number(t.compassionate||0),ambitious=Number(t.ambitious||0);let changes={};if(action==='join'){if((f.ethos==='freedom'&&rebellious>=55)||(f.ethos==='order'&&disciplined>=55)||(f.ethos==='mercy'&&compassionate>=55)||(f.ethos==='ambition'&&ambitious>=55))changes={trust:4,respect:4,loyalty:2};else if((f.ethos==='order'&&rebellious>=70)||(f.ethos==='ambition'&&compassionate>=70))changes={trust:-4,resentment:6};}else if(action==='betray')changes={trust:-8,loyalty:-5,resentment:8};else if(action==='campaign-win')changes={respect:3,trust:2};else if(action==='campaign-loss')changes={fear:3,trust:-1};else if(action==='leave')changes={trust:-1,respect:1};if(Object.keys(changes).length){rel.adjust(state,id,changes,`${f.name}: ${action}`);results.push({characterId:id,changes});}}return results;
    }
    syncDefectors(state){if(!state.v19?.records)return;for(const r of Object.values(state.v19.records)){if(r.status!=='defected')continue;const factionId=r.defectedTo&&state.v16?.factions?.[r.defectedTo]?r.defectedTo:factionList(state)[hash32(`${r.id}|v21-defector`)%Math.max(1,factionList(state).length)]?.id;if(factionId)r.v21FactionId=factionId;}}
    syncNemeses(state){for(const n of Object.values(state.v16?.nemeses||{})){if(n.status==='broken')continue;if(!n.v21FactionId){const enemies=factionList(state).filter(f=>f.id!==state.v21.primaryFactionId);n.v21FactionId=enemies[hash32(`${n.id}|v21-faction`)%Math.max(1,enemies.length)]?.id||'';}if(n.v21FactionId&&hash32(`${n.id}|${tick(state)}|champion`)%11===0)n.v21Role='faction-champion';}}
    createExposureNemesis(state,factionId){const faction=state.v16?.factions?.[factionId];if(!faction)return;const id=`operative-${hash32(`${state.seed}|${factionId}|exposed`).toString(36)}`;if(!state.v16.nemeses[id])state.v16.nemeses[id]={id,name:`${faction.name} Counterintelligence`,universe:worldName(state),level:2,power:1.08,encounters:0,grudges:1,defeats:0,victories:0,stolenArtifacts:[],status:'active',lastSeenTick:tick(state),cause:'Your infiltration was exposed.',v21FactionId:factionId,v21Role:'counterintelligence'};}

    ending(state){const primary=this.primaryMembership(state),holds=Object.values(state.v21.strongholds),won=Number(state.v21.stats.campaignsWon||0),betrayals=Number(state.v21.stats.betrayals||0),controls=Object.values(state.v21.territories).filter(t=>t.controllerFactionId===state.v21.primaryFactionId).length;if(betrayals>=3)return{id:'faction-betrayer',title:'No Banner Left Unburned',text:'The multiverse remembers a strategist who treated every banner as temporary.'};if(primary?.rank>=8&&controls>=5)return{id:'faction-regent',title:'Regent of the Crossroads',text:'Authority became responsibility: worlds, routes, and strongholds now answer to the faction legacy you shaped.'};if(won>=3&&holds.some(s=>s.playerAligned&&s.status!=='occupied'))return{id:'faction-champion',title:'A Banner That Held',text:'Campaign victories and a surviving stronghold turned temporary allegiance into a durable multiversal legacy.'};if(!state.v21.primaryFactionId&&state.v21.stats.factionsJoined>0)return{id:'faction-independent',title:'No Throne, No Chain',text:'You worked beside factions but ended the road belonging to none of them.'};return{id:'faction-witness',title:'The Powers Remember',text:'The factions survived as living powers, and every campaign choice remained part of their history.'};}
    summary(state){this.ensure(state);const primary=this.primaryMembership(state),campaign=this.activeCampaign(state),territories=Object.values(state.v21.territories),strongholds=Object.values(state.v21.strongholds);return{primaryFaction:primary?clone(state.v16.factions[primary.factionId]):null,membership:clone(primary),rank:primary?clone(RANKS[primary.rank-1]):null,campaign:clone(campaign),campaigns:Object.values(state.v21.campaigns).map(clone),territories:territories.map(clone),fronts:Object.values(state.v21.fronts).map(clone),strongholds:strongholds.map(clone),facilities:Object.values(state.v21.facilities).map(clone),assignments:Object.values(state.v21.assignments).map(clone),diplomacy:clone(state.v21.diplomacy),infiltration:clone(state.v21.infiltration),stats:clone(state.v21.stats),ending:this.ending(state)};}

    remember(state,type,title,detail,factionId=''){try{return new root.MultiverseDomain.LivingMultiverseEngine().recordMemory(state,{type,title,detail,factionId,weight:5});}catch{return null;}}
    wallet(state){try{return new root.MultiverseDomain.EconomyCraftingEngine().wallet(state);}catch{return{credits:Number(state.credits||0),...(state.v18?.wallet||{})};}}
    pay(state,cost){try{return new root.MultiverseDomain.EconomyCraftingEngine().pay(state,cost);}catch{return false;}}
    addCurrency(state,key,amount){try{return new root.MultiverseDomain.EconomyCraftingEngine().addCurrency(state,key,amount);}catch{if(key==='credits')state.credits=Math.max(0,Number(state.credits||0)+Number(amount||0));return Number(state.credits||0);}}
  }

  function migrateV21(state={},artifacts=[],roster=[]){return new FactionCampaignEngine().ensure(state,artifacts,roster);}
  const api={V21_SCHEMA_VERSION,RANKS_V21:RANKS,CAMPAIGN_DEFS_V21:CAMPAIGN_DEFS,FACILITY_DEFS_V21:FACILITY_DEFS,SPECIALIST_ROLES_V21:SPECIALIST_ROLES,TECHNIQUES_V21:TECHNIQUES,FactionCampaignEngine,migrateV21};
  root.MultiverseDomain=Object.assign(root.MultiverseDomain||{},api);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:window);
