'use strict';
(function attachV28Engine(root,factory){const api=factory(root);root.MultiverseDomain=root.MultiverseDomain||{};Object.assign(root.MultiverseDomain,api);if(typeof module==='object'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:window,function(root){
const V28_SCHEMA_VERSION=28,clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v)),RARITY_ORDER={common:1,uncommon:2,rare:3,epic:4,legendary:5};
class AtlasExperienceEngine{
  constructor(){const Mega=root.MultiverseDomain?.WorldContentMegaEngine;this.mega=Mega?new Mega():null;}
  ensure(state={},artifacts=[],roster=[]){if(Number(state.v27?.schemaVersion||0)<27&&root.MultiverseDomain?.migrateV27)root.MultiverseDomain.migrateV27(state,artifacts,roster);state.v28=state.v28&&typeof state.v28==='object'?state.v28:{};const v=state.v28;v.schemaVersion=V28_SCHEMA_VERSION;state.v28Version=V28_SCHEMA_VERSION;state.schemaVersion=Math.max(Number(state.schemaVersion||0),V28_SCHEMA_VERSION);v.atlas={search:'',kind:'',group:'',rarity:'',sort:'name',favoritesOnly:false,discoveredOnly:false,page:0,pageSize:72,view:'grid',...(v.atlas||{})};v.atlas.page=Math.max(0,Number(v.atlas.page)||0);v.atlas.pageSize=Math.max(24,Math.min(96,Number(v.atlas.pageSize)||72));v.atlas.sort=['name','kind','rarity','newest'].includes(v.atlas.sort)?v.atlas.sort:'name';v.atlas.view=['grid','compact'].includes(v.atlas.view)?v.atlas.view:'grid';v.inspector={selectedAssetId:'',...(v.inspector||{})};v.stats={assetInspections:0,filterChanges:0,keyboardShortcuts:0,...(v.stats||{})};return state;}
  find(id){return this.mega?.find(id)||null;}
  sort(list,mode='name'){const rows=[...list];if(mode==='kind')return rows.sort((a,b)=>a.kind.localeCompare(b.kind)||a.name.localeCompare(b.name));if(mode==='rarity')return rows.sort((a,b)=>(RARITY_ORDER[b.rarity]||0)-(RARITY_ORDER[a.rarity]||0)||a.name.localeCompare(b.name));if(mode==='newest')return rows.sort((a,b)=>Number(String(b.path||'').startsWith('generated:v27/'))-Number(String(a.path||'').startsWith('generated:v27/'))||a.name.localeCompare(b.name));return rows.sort((a,b)=>a.name.localeCompare(b.name));}
  query(state,overrides={}){this.ensure(state);const prefs={...state.v28.atlas,...overrides},base=this.mega?.query({kind:prefs.kind,group:prefs.group,rarity:prefs.rarity,search:prefs.search})||[],favorites=new Set(state.v26?.favorites||[]),discovered=new Set(state.v27?.discoveries||[]);let rows=base;if(prefs.favoritesOnly)rows=rows.filter(a=>favorites.has(a.id));if(prefs.discoveredOnly)rows=rows.filter(a=>discovered.has(a.id));return this.sort(rows,prefs.sort);}
  updatePrefs(state,patch={}){this.ensure(state);const before=JSON.stringify(state.v28.atlas);state.v28.atlas={...state.v28.atlas,...patch};this.ensure(state);if(JSON.stringify(state.v28.atlas)!==before)state.v28.stats.filterChanges+=1;return clone(state.v28.atlas);}
  inspect(state,id){this.ensure(state);const asset=this.find(id);if(!asset)return null;state.v28.inspector.selectedAssetId=asset.id;state.v28.stats.assetInspections+=1;this.mega?.markDiscovered(state,asset.id);return clone(asset);}
  related(state,id,limit=6){const asset=this.find(id);if(!asset)return[];const tags=new Set(asset.tags||[]),targets=new Set(asset.usageTargets||[]);return (this.mega?.catalog()||[]).filter(a=>a.id!==asset.id).map(a=>({asset:a,score:(a.kind===asset.kind?5:0)+(a.tags||[]).filter(t=>tags.has(t)).length*2+(a.usageTargets||[]).filter(t=>targets.has(t)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.asset.name.localeCompare(b.asset.name)).slice(0,Math.max(1,Math.min(12,limit))).map(x=>x.asset);}
  summary(state){this.ensure(state);const rows=this.query(state);return{schemaVersion:28,visible:rows.length,selected:this.find(state.v28.inspector.selectedAssetId),prefs:clone(state.v28.atlas),stats:clone(state.v28.stats)};}
}
function migrateV28(state={},artifacts=[],roster=[]){return new AtlasExperienceEngine().ensure(state,artifacts,roster);}return{V28_SCHEMA_VERSION,AtlasExperienceEngine,migrateV28};
});
