'use strict';
(function attachV29Engine(root,factory){const api=factory(root);root.MultiverseDomain=root.MultiverseDomain||{};Object.assign(root.MultiverseDomain,api);if(typeof module==='object'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:window,function(root){
const V29_SCHEMA_VERSION=29,clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v)),uniq=list=>[...new Set((list||[]).map(v=>String(v||'').trim()).filter(Boolean))];
const PROFILES=Object.freeze({
  origin:{usageTarget:'world',roles:[['place','building','landmark'],['flora','fauna','transit'],['shop','npc','prop'],['resource','utility','technology']]},
  battle:{usageTarget:'operation',roles:[['place','interior','stronghold'],['hazard','vehicle','technology'],['weapon','armor','utility'],['prop','npc','transit']]},
  boss:{usageTarget:'crisis',roles:[['place','landmark','stronghold'],['hazard','vehicle','technology'],['weapon','armor','utility'],['prop','npc','resource']]},
  power:{usageTarget:'inventory',roles:[['technology','weapon','item'],['resource','utility','armor'],['shop','interior','furnishing'],['prop','vehicle','npc']]},
  transform:{usageTarget:'world',roles:[['landmark','place','technology'],['hazard','flora','resource'],['armor','utility','prop'],['transit','vehicle','npc']]},
  training:{usageTarget:'activity',roles:[['place','interior','activity'],['furnishing','technology','utility'],['npc','food','resource'],['prop','transit','vehicle']]},
  recruit:{usageTarget:'settlement',roles:[['place','settlement','building'],['npc','shop','interior'],['vehicle','transit','food'],['prop','furnishing','resource']]},
  artifact:{usageTarget:'shop',roles:[['shop','interior','landmark'],['item','technology','weapon'],['resource','utility','armor'],['furnishing','prop','npc']]},
  recovery:{usageTarget:'settlement',roles:[['interior','place','settlement'],['food','resource','flora'],['technology','utility','furnishing'],['npc','prop','transit']]},
  hazard:{usageTarget:'crisis',roles:[['hazard','place','crisis'],['vehicle','transit','technology'],['utility','resource','armor'],['npc','prop','landmark']]},
  rare:{usageTarget:'world',roles:[['landmark','place','building'],['technology','hazard','resource'],['vehicle','transit','fauna'],['prop','npc','utility']]},
  default:{usageTarget:'world',roles:[['place','building','landmark'],['npc','vehicle','transit'],['item','technology','resource'],['prop','utility','flora']]}
});
class DynamicSceneEngine{
  constructor(){const Mega=root.MultiverseDomain?.WorldContentMegaEngine;this.mega=Mega?new Mega():null;}
  ensure(state={},artifacts=[],roster=[]){if(Number(state.v28?.schemaVersion||0)<28&&root.MultiverseDomain?.migrateV28)root.MultiverseDomain.migrateV28(state,artifacts,roster);state.v29=state.v29&&typeof state.v29==='object'?state.v29:{};const v=state.v29;v.schemaVersion=V29_SCHEMA_VERSION;state.v29Version=V29_SCHEMA_VERSION;state.schemaVersion=Math.max(Number(state.schemaVersion||0),V29_SCHEMA_VERSION);v.settings={enabled:true,slots:4,avoidRepeat:12,historyLimit:24,...(v.settings||{})};v.settings.enabled=v.settings.enabled!==false;v.settings.slots=Math.max(3,Math.min(6,Number(v.settings.slots)||4));v.settings.avoidRepeat=Math.max(4,Math.min(24,Number(v.settings.avoidRepeat)||12));v.settings.historyLimit=Math.max(8,Math.min(40,Number(v.settings.historyLimit)||24));v.current=v.current&&typeof v.current==='object'?v.current:null;v.history=Array.isArray(v.history)?v.history.filter(x=>x&&Array.isArray(x.assetIds)).slice(0,v.settings.historyLimit):[];v.remixByEvent=v.remixByEvent&&typeof v.remixByEvent==='object'?v.remixByEvent:{};v.stats={scenesComposed:0,sceneRemixes:0,assetsStaged:0,historyViews:0,...(v.stats||{})};return state;}
  profile(type){return PROFILES[String(type||'').toLowerCase()]||PROFILES.default;}
  eventKey(state,event={}){return `${Number(state.spin||0)}:${String(event.type||'event')}:${String(event.ref||event.id||event.label||'unknown')}`;}
  context(state,event={}){const universe=String(state.v16?.currentUniverse||state.customCharacter?.homeworld||event.sub||'Earth-Prime'),rawDestination=state.v17?.currentDestination||state.v17?.destination||state.v17?.currentDestinationId||'',destination=String(typeof rawDestination==='object'?(rawDestination.name||rawDestination.label||rawDestination.id||''):rawDestination),membership=state.v21?.membership||{},faction=String(membership.primaryFactionId||membership.primaryFaction||membership.factionId||event.faction||'');return{universe,destination,faction,tags:uniq([universe,destination,faction,event.type]),words:uniq([event.label,event.sub,event.resultText,universe,destination,faction])};}
  recentAssetIds(state){this.ensure(state);const scenes=state.v29.history.slice(0,state.v29.settings.avoidRepeat);return uniq(scenes.flatMap(x=>x.assetIds||[]));}
  pick(state,event,roleKinds,index,variation,exclude=[]){if(!this.mega)return null;const profile=this.profile(event.type),ctx=this.context(state,event),salt=`${this.eventKey(state,event)}|${variation}|${index}`,blocked=uniq(exclude);let asset=this.mega.pick(state,{usageTarget:profile.usageTarget,kinds:roleKinds,tags:ctx.tags,words:ctx.words,salt,exclude:blocked,preferAdded:false});if(!asset&&blocked.length)asset=this.mega.pick(state,{usageTarget:profile.usageTarget,kinds:roleKinds,tags:ctx.tags,words:ctx.words,salt:`${salt}|fallback`,exclude:[],preferAdded:false});return asset||null;}
  compose(state,event={},options={}){this.ensure(state);if(!state.v29.settings.enabled||!event)return null;const key=this.eventKey(state,event),variation=Number(options.variation??state.v29.remixByEvent[key]??0)||0,current=state.v29.current;if(!options.force&&current?.eventKey===key&&Number(current.variation||0)===variation&&current.assetIds?.every(id=>this.mega?.find(id)))return clone(current);const profile=this.profile(event.type),ctx=this.context(state,event),recent=this.recentAssetIds(state),assetIds=[];for(let i=0;i<state.v29.settings.slots;i++){const roles=profile.roles[i%profile.roles.length],asset=this.pick(state,event,roles,i,variation,[...recent,...assetIds]);if(asset&&!assetIds.includes(asset.id))assetIds.push(asset.id);}if(!assetIds.length)return null;const scene={id:`scene:${key}:${variation}`,eventKey:key,spin:Number(state.spin||0),eventType:String(event.type||'event'),eventRef:String(event.ref||''),eventLabel:String(event.label||event.title||event.type||'Wheel Event'),universe:ctx.universe,destination:ctx.destination,faction:ctx.faction,usageTarget:profile.usageTarget,assetIds,variation,release:29};state.v29.current=scene;state.v29.history=[clone(scene),...state.v29.history.filter(x=>x.id!==scene.id)].slice(0,state.v29.settings.historyLimit);state.v29.stats.scenesComposed+=1;state.v29.stats.assetsStaged+=assetIds.length;for(const id of assetIds)if(!state.v27?.discoveries?.includes(id))this.mega?.markDiscovered(state,id);return clone(scene);}
  remix(state,event={}){this.ensure(state);const key=this.eventKey(state,event),variation=(Number(state.v29.remixByEvent[key])||0)+1;state.v29.remixByEvent[key]=variation;state.v29.stats.sceneRemixes+=1;return this.compose(state,event,{force:true,variation});}
  current(state,event=null){this.ensure(state);if(event&&state.v29.current?.eventKey!==this.eventKey(state,event))return null;return clone(state.v29.current);}
  assets(scene){return(scene?.assetIds||[]).map(id=>this.mega?.find(id)).filter(Boolean);}
  history(state,limit=12){this.ensure(state);return state.v29.history.slice(0,Math.max(1,Math.min(24,Number(limit)||12))).map(clone);}
  summary(state){this.ensure(state);return{schemaVersion:29,current:clone(state.v29.current),history:state.v29.history.length,settings:clone(state.v29.settings),stats:clone(state.v29.stats)};}
}
function migrateV29(state={},artifacts=[],roster=[]){return new DynamicSceneEngine().ensure(state,artifacts,roster);}return{V29_SCHEMA_VERSION,DynamicSceneEngine,migrateV29,V29_SCENE_PROFILES:PROFILES};
});
